### ISSUE TITLE
Reset the cropper and image preview

### ISSUE THREAD

**Issue by Lempkin** [Mawi137/ngx-image-cropper#101]
Hi!

I've forked your demo to show what I try to do :  
https://stackblitz.com/edit/image-cropper-dj1dtm

I want to be able to : 
 - add an image, 
 - then delete it  : at this time img preview in the <img> and the cropper must not show any image
 - add an image (same one or another one) at this time, cropper and <img> should show choosen img.

On my stackblitz as you can see, step 3 doesn't work, nothing is shown.
Is it a bug or should I proceed otherwise?

Thx and good job btw =)

**Comment by Mawi137** [comment]
Hi, it seems you set the `#inputFile` on the img and not on the input itself. After changing that it all works fine for me on your stackblitz.

**Comment by Lempkin** [comment]
Ah crap sry >_<   Thx :)
