### ISSUE TITLE
How to crop image manually on a button click

### ISSUE THREAD

**Issue by vijaynt** [Mawi137/ngx-image-cropper#102]
I need to crop the image on a button click  
@ViewChild('image-cropper') imageCropperSelector;

  ngAfterViewInit(): void {
    console.log(this.imageCropperSelector);
  }
when console logged the above is undefined. I have set autoCrop as false.
In documentation it is stated that
"**When set to true, the cropper will emit an image each time the position or size of the cropper is changed. When set to true, you can call the crop method yourself (use @ViewChild to get access to the croppers methods).**"

Thanks to any help.

**Comment by Mawi137** [comment]
Hi, you should use: `@ViewChild(ImageCropperComponent) imageCropper;` Then you can call `this.imageCropper.crop();` which will trigger the `imageCropped` output
