### ISSUE TITLE
The cropped image size is more than the original image size

### ISSUE THREAD

**Issue by philipjohn007** [Mawi137/ngx-image-cropper#103]
I wanted to limit the file upload size of the image and was using the cropped image size to check before sending to the server. It is ideal that the cropped image size should have lesser size than the original. Currently, if the user uploads an image of size 280kb, while the maximum permitted size of 300kb, the cropped image size is almost double ~530-550kb (`imageCroppedEvent.file.size`).

The main issue is that I cannot let the user know what the maximum upload size should be because of this. Or is there a way to determine the file size of the original image before cropping?

**Comment by philipjohn007** [comment]
I am using the file change event to get the original image size

**Comment by halilkalkan** [comment]
Hi Philip,

Did you find any solution for this problem? I'm experiencing the same issue. 

Thank you,
