### ISSUE TITLE
Internet Explorer 11 - ERROR IndexSizeError

### ISSUE THREAD

**Issue by tfilo** [Mawi137/ngx-image-cropper#104]
I have this issue with some images im my project.  I am working on fix. Problem origin is in crop() function where sometimes left + width is more than originalSize.width so index is out picture. Same can happen for top + height. I will submit pull request as soon as I test if my fix is working. Problem is only in IE, other browsers know how to handle this.

```
ERROR IndexSizeError
"ERROR" {
[functions]: ,
proto: { },
ABORT_ERR: 20,
code: 1,
constructor: { },
DATA_CLONE_ERR: 25,
DOMSTRING_SIZE_ERR: 2,
HIERARCHY_REQUEST_ERR: 3,
INDEX_SIZE_ERR: 1,
INUSE_ATTRIBUTE_ERR: 10,
INVALID_ACCESS_ERR: 15,
INVALID_CHARACTER_ERR: 5,
INVALID_MODIFICATION_ERR: 13,
INVALID_NODE_TYPE_ERR: 24,
INVALID_STATE_ERR: 11,
message: "IndexSizeError",
name: "IndexSizeError",
NAMESPACE_ERR: 14,
NETWORK_ERR: 19,
NO_DATA_ALLOWED_ERR: 6,
NO_MODIFICATION_ALLOWED_ERR: 7,
NOT_FOUND_ERR: 8,
NOT_SUPPORTED_ERR: 9,
PARSE_ERR: 81,
QUOTA_EXCEEDED_ERR: 22,
SECURITY_ERR: 18,
SERIALIZE_ERR: 82,
Symbol(rxSubscriber)_g.8byau33orns: undefined,
SYNTAX_ERR: 12,
TIMEOUT_ERR: 23,
TYPE_MISMATCH_ERR: 17,
URL_MISMATCH_ERR: 21,
VALIDATION_ERR: 16,
WRONG_DOCUMENT_ERR: 4
}
```

I have this problem with https://www.npmjs.com/package/ngx-image-cropper version 1.2.2

**Comment by vijaynt** [comment]
I also got the same issue when tried to crop an image with 3543x1311 dimension. The same image can crop in Firefox and chrome.

**Comment by tfilo** [comment]
I will fix it soon. For now you can test it from here https://github.com/tfilo/ngx-image-cropper but I will make pull request to this project as soon as this change will be tested in my project.

**Comment by vijaynt** [comment]
> 
> 
> I will fix it soon. For now you can test it from here https://github.com/tfilo/ngx-image-cropper but I will make pull request to this project as soon as this change will be tested in my project.

Thanks for your reply

**Comment by Mawi137** [comment]
Just made a new release including these changes: version 1.2.3
