### ISSUE TITLE
The cropped image size is more than the original image size

### ISSUE THREAD

**Issue by jigneshchudasama** [Mawi137/ngx-image-cropper#105]
If the user uploads an image of size 29kb, while the maximum upload size is 30kb. The cropped image size is almost getting double 70kb.

I have used below code in the template,

`<image-cropper [imageChangedEvent]="imageChangedEvent" [maintainAspectRatio]="false" format="jpeg" [cropper]="cropper (imageCroppedBase64)="imageCropped($event, currentSelectedFile)"></image-cropper>`

and in the controller,

`public cropper = { x1: 0, x2: 0, y1: 0, y2: 0 };`

I have used this plugin considering it will reduce the image size once user cropped the image and even if the user does not crop image, image size should be the same as original image size.

Let me know if you need more information.

**Comment by jigneshchudasama** [comment]
Any update?

**Comment by Mawi137** [comment]
If your output is jpeg, you can select the quality for the output image, default is 92, might have something to do with that. Lowering it to 80 will probably help `[imageQuality]="80"`

**Comment by Mawi137** [comment]
Hmm, well I simply put the image on a HTML canvas and use its `toDataURL` method to get the cropper image. So, I don't think there's anything I can do to lower the filesizes.

**Comment by Mawi137** [comment]
Here's some more info: https://stackoverflow.com/questions/41129735/html5-canvas-todataurl-output-size-bigger-than-original-image-size

**Comment by Joniras** [comment]
I am not really seeing how this SO answer solves the issue beacuse you would have to apply that funciton directly to the canvas (in the cropper-component). Is there any chance the snippet gets implemented as opt-in ?

**Comment by Mawi137** [comment]
The stackoverflow issue simply explains the why the size increases. I don’t have any fix for it. If you find one, let me know :)

**Comment by developerdesigner18** [comment]
Can anyone find any solution to it?
