### ISSUE TITLE
Is there zoom in/out functionality in cropper ? 

### ISSUE THREAD

**Issue by hmk18** [Mawi137/ngx-image-cropper#109]

**Comment by yduartep** [comment]
Hi. I would like to know if you are going to include the zoom functionality soon.

**Comment by Mawi137** [comment]
Hi, I won't be including it soon, but feel free to contribute!

**Comment by yduartep** [comment]
Great. I'll keep it in mind.
Regards

**Comment by fergardi** [comment]
Maybe not a zoom functionality, but how can I create the effect of "zooming-in" and "zooming-out" the image, by increasing and decreasing programatically the width and height of the cropper, and attach this functionality to a slider, for example?

Thanks in advance.

**Comment by fergardi** [comment]
@yduartep seems just what I need, hope the PR gets accepted ASAP! Thank you very much!

**Comment by niklissad** [comment]
So would you implement zoom? It's very important feature for cropping (if u a working with a big images)

**Comment by Mawi137** [comment]
As of version `3.0.0` you can zoom in and out. You will be able to move the image behind as well soon. More info: https://github.com/Mawi137/ngx-image-cropper/releases/tag/3.0.0
