### ISSUE TITLE
1x1 default empty image displayed when 'aspectRatio' provided in input

### ISSUE THREAD

**Issue by cuneytcalishkan** [Mawi137/ngx-image-cropper#110]
Hello,

I have just realized that with version 1.1.0 there has been a bug introduced which results in displaying a 1x1 default base64 image in the image preview area. It was introduced in version 1.1.0 with the following piece of code in ngOnChanges method: 
 ```
if (changes['aspectRatio']) {
        this.resetCropperPosition();
}
```

resetCropperPosition method sets the imageVisible to true. Thus, the styling is set to 'visible' for the default empty image.

Cheers,
Cuneyt

**Comment by Mawi137** [comment]
Hi @cuneytcalishkan 

This should be fixed in version 1.2.5!
