### ISSUE TITLE
How to set the initial cropper rectangular?

### ISSUE THREAD

**Issue by Herbert-Hotz** [Mawi137/ngx-image-cropper#115]
Hi, first of all: Thanks for your excellent work! 

Background:
I'm using _Angular 7_ with face detection tool and would have available the proposed rectangular to crop from original image.

My issue: 
I'm sorry but I could not find out how to set the initial cropper rectangular coordinates. And yes, I tried `cropper`, but no success :-(

This did NOT work as intended:
HTML:
`    <image-cropper ... [cropper]="cropper"></image-cropper>`
JS:
`  cropper:any = { 
    x1: 0, 
    y1: 0, 
    x2: 200, 
    y2: 300 
  };
`

Thank's for any hints!

Similar to #52

**Comment by Mawi137** [comment]
Do you have an aspectRatio set and if so, does that match those coordinates?
It's also possible that you'll need to use a setTimeout to set the new coordinates. I haven't found a solution to avoid that yet.

**Comment by Herbert-Hotz** [comment]
I have tried with:
```javascript
<image-cropper
      [imageBase64]='imageBase64'
      [imageChangedEvent]="imageChangedEvent"
      [resizeToWidth]="200"
      format="png"
      (imageCropped)="imageCropped($event)"
      (imageLoaded)="imageLoaded()"
      (loadImageFailed)="loadImageFailed()"
      [cropper]="cropper"
    ></image-cropper>
```

Could you eventually give me a link to a working example, or - even better - include such a thing in the **README.md** to complement what's already there? Thanks!

**Comment by Mawi137** [comment]
You have to wait for the `imageLoaded` event to have fired to overwrite the cropper's position. But even then, you might still need to wrap that in a `setTimeout` of 1 or 2 ms.

```
imageLoaded() {
    setTimeout(() => {
        this.cropper = {x1.... };
    }, 2);
}
```

**Comment by Herbert-Hotz** [comment]
Thank's! Your hint worked.

**Comment by anantksingh** [comment]
HI,
I am unable to set cropper position fix, it take full space
<image-cropper [imageChangedEvent]="imageChangedEvent"
                 [maintainAspectRatio]="true" 
                 [aspectRatio]="1/1"
                  [resizeToWidth]="0" 
                  [onlyScaleDown]="true" 
                  [roundCropper]="false"
                   format="fileExtention" 
                   outputType="both" 
                   (imageCropped)="imageCropped($event)"
                    (imageLoaded)="imageLoaded()"
                     (cropperReady)="cropperReady()"
                      (loadImageFailed)="loadImageFailed()"
                      [cropper] ="coordinates" 
                      [style.display]="showCropper ? null : 'none'">
                </image-cropper>            
Declare in two place   
  fileChangeEvent(event: any,templateUpload): void {        
            this.coordinates={x1: 161.5, y1: 34, x2: 360.5, y2: 233};            
        }
imageLoaded() {
       this.showCropper = true;
       setTimeout(() => {
        this.coordinates={x1: 161.5, y1: 34, x2: 360.5, y2: 233}; 
        console.log('Image loaded',this.coordinates)
        }, 1000);
       
    }

**Comment by Mawi137** [comment]
You should wait for the cropperReady event

**Comment by anantksingh** [comment]
Thank Mawi137

**Comment by NavjotKumar** [comment]
Cropper is not working

cropper = {
    x1: 0,
    y1: 0,
    x2: 410,
    y2: 546
  };

i have added timeout also
imageLoaded() {
    this.cropperReady = true;
    if (this.cropperReady === true) {
      setTimeout(() => {
        this.cropper = {
          x1: 0,
          y1: 0,
          x2: 410,
          y2: 546
        };
      });
      console.log(this.cropper );
    }
  }

this is html part

<image-cropper
            [imageChangedEvent]="imageChangedEvent"
            [maintainAspectRatio]="true"
            [aspectRatio]="selectedRatio"
            format="png"
            [imageQuality]="85"
            [resizeToWidth]="410"
            (imageLoaded)="imageLoaded()"
            (loadImageFailed)="loadImageFailed()"
            (imageCroppedBase64)="imageCropped($event)"
            [style.display]="cropperReady ? null : 'none'"            
            outputType="both"
            [cropper]="cropper"
            [autoCrop]=false
            ></image-cropper>
