### ISSUE TITLE
BMP format Not Supported

### ISSUE THREAD

**Issue by kapsrox** [Mawi137/ngx-image-cropper#116]
when i tried to upload bmp file format it is not working
i tried on your stackblitz demo
https://stackblitz.com/edit/image-cropper?file=app%2Fapp.component.html

**Comment by kaziupir** [comment]
Or just 
```
    const pattern = /image-*/;

    if (pattern.test(type)
```

**Comment by kapsrox** [comment]
@kaziupir actually he need to be rebuild package because i have to add bmp type in several locations in my project inside node-modules(ngx-image-cropper) directory i am just consume this library in my component

**Comment by Mawi137** [comment]
Just added BMP support in the wya @kaziupir suggested.
Available in version 1.2.5

Thanks!

**Comment by kapsrox** [comment]
Actually i found this missing functionality in library but no problem if you give credit to @kaziupir  
Happy coding.......

**Comment by Mawi137** [comment]
I simply stated that I added it in the way that kaziupir suggested. (` /image\/(png|jpg|jpeg|bmp|gif)/.test(type);`)
