### ISSUE TITLE
Cropper initial size in modal view

### ISSUE THREAD

**Issue by ron4548** [Mawi137/ngx-image-cropper#120]
Hello,
Thank for the great component!
I face a problem when using the image cropper inside bootstrap modal dialog - the initial size of the cropper is zero.
Here is an example that demonstrates this bug: https://stackblitz.com/edit/image-cropper-s6ahmz
Any idea how to solve it?
Thanks :)

**Comment by ron4548** [comment]
Thanks. We will keep investigating and will update here once we have a fix

**Comment by Mawi137** [comment]
Just released version 1.3.0 which fixes this problem. I tried with your example and it's working fine now!

**Comment by ron4548** [comment]
> Just released version 1.3.0 which fixes this problem. I tried with your example and it's working fine now!

Wow! Thank you very much for the quick update
