### ISSUE TITLE
x2: 1100 for images larger than that size

### ISSUE THREAD

**Issue by thanasparkgrid** [Mawi137/ngx-image-cropper#121]
![ngx-image-cropper](https://user-images.githubusercontent.com/23611152/50479825-7c1b0700-09fe-11e9-91c7-87be7221afad.JPG)

When I expand the cropper to full size of the image, the cropper values are not getting match with real sizes.
Example:
Image width : 2200
Image height: 1700

cropper x1: 0, y1: 0, x2:1100, y2: 1423

My problem is x2 & y2.

Hope you understand the issue. Is this because of the large image size or any restriction?

**Comment by Mawi137** [comment]
Hi, the cropper coordinates are relative to the scaled down image that is being displayed. However, I can indeed imagine that you'd want the coordinates relative to the original image. I'll add it to the output event. Just need a good name for it, maybe `imagePosition`?

**Comment by thanasparkgrid** [comment]
Thank you for the quickest replay @Mawi137 
`imagePosition `/ `cropperCordinates `would be a suitable name for the variable.

**Comment by Mawi137** [comment]
Hi, just created a new release that adds the `imagePosition` to the `imageCropped` output. Version: 1.3.0

**Comment by thanasparkgrid** [comment]
Great and  thank you again for the version update with the required configuration.
![capture](https://user-images.githubusercontent.com/23611152/50554463-d35ff680-0ce0-11e9-8ddb-e1aad9dc2b50.JPG)
