### ISSUE TITLE
set initial image and cropper coordinates

### ISSUE THREAD

**Issue by Awatatah** [Mawi137/ngx-image-cropper#122]
How can I set the default image (base64 or img src URL) with cropper coordinates?

I need the cropper to already have an image in place with the cropper set at previously cropped coordinates

**Comment by Awatatah** [comment]
@Mawi137 could you direct me? I guess I'm just not seeing it in the docs...

**Comment by Mawi137** [comment]
https://github.com/Mawi137/ngx-image-cropper then simply scroll down

**Comment by 1wiseash** [comment]
I don't see it in the documentation either. (I scrolled down as instructed.)

**Comment by Mawi137** [comment]
Set initial image: 
Readme -> API - Inputs -> imageChangedEvent or imageFileChanged or imageBase64

For the coordinates:
Readme -> API -> Inputs -> cropper

**Comment by muthukumaran25** [comment]
import CropperPosition in your component
In your component, define  cropper:CropperPosition = {x1:0,y1:0, x2:0,y2:0};
and in cropperReady(), add   this.cropper = {x1:0,y1:100, x2:100,y2:1000};
in html, <image-cropper [cropper]="cropper" ... </image-cropper>
