### ISSUE TITLE
The cropping is not accurrate, it crops a few pixels to the left

### ISSUE THREAD

**Issue by Yejielw** [Mawi137/ngx-image-cropper#124]
When im cropping an image, the output is the desired size but the actual crop happens a bit to the side , **
![image](https://user-images.githubusercontent.com/19639834/50832153-01cf7880-1356-11e9-9f32-e3dcdeea60d9.png)
**
note that in the cropping i can see the lights and in the cropped image i cannot.
Not a big deal, but i thoutgh i put it out here

EDIT: 
It would seem that the issue is only when using Base64

**Comment by miki995** [comment]
I'm working on it as we speak and cannot reproduce issue that you have. Can you explain to repo owner a bit what is your exact usage of library? @Yejielw

**Comment by Yejielw** [comment]
`    <image-cropper
    [imageBase64]="imageBase64"
    [maintainAspectRatio]="true"
    [aspectRatio]="4 / 4"
    [cropperMinWidth]="256"

    format="png"
    (imageCropped)="imageCropped($event)"
    (imageLoaded)="imageLoaded()"
    (loadImageFailed)="loadImageFailed()"
></image-cropper>

      
    fileChangeEvent(event: any): void {
      const fileReader = new FileReader();
          fileReader.onload = (event: any) => {
              this.imageBase64 = event.target.result;
          };
          fileReader.readAsDataURL(event.target.files[0]);
    }
imageCropped(event: any) {
  this.croppedImage = event.base64;
}
`

thats the code im using nothing fancy

**Comment by Yejielw** [comment]
@Mawi137  i'm ignoring it at the moment since its not really relevant , but i did not chose any alignment

**Comment by ignaciocasal** [comment]
In my case I had a `img: { display: block }`. Change it to  `img: { display: in-line}` solved the problem
