### ISSUE TITLE
Can't left align the control

### ISSUE THREAD

**Issue by blissi** [Mawi137/ngx-image-cropper#125]
Hallo,

I try to align the full image cropper control on the left by setting `text-align: left` on the image-cropper HTML element.

This has the effect, that the image is now aligned left, but the cropper-rectangle is not:

![image cropper](https://user-images.githubusercontent.com/13705486/50833572-e7939b80-1351-11e9-9bd7-66d9846e624b.jpg)

How can I fix this?

Thanks,
Blissi

**Comment by Mawi137** [comment]
Hi, just added a new input `alignImage` in version `1.3.5`. Set that to 'left' and it will be aligned to the left!

**Comment by blissi** [comment]
Wow, that was quick! Thank you, tried it and it works 👍
