### ISSUE TITLE
User-defined styling

### ISSUE THREAD

**Issue by jaco-terbraak** [Mawi137/ngx-image-cropper#126]
I'd love to be able to style the cropper. At the moment I either need to fork the repo (undesirable), or apply global styles to specific elements (somewhat doable, however !important attributes block this). It would be great if we could supply our own stylesheet.

**Comment by Mawi137** [comment]
I'm not sure I need the !important actually, so that would no longer keep you from using global styles. How would that work, providing your own style sheets? I can add inputs to change the colors, but full stylesheets, is that possible ?

**Comment by jaco-terbraak** [comment]
I'm not sure either. Inputs are a possibility, however that would require quite a lot of them. For now it would be nice if just the !important attributes could be removed.

**Comment by Mawi137** [comment]
Done! Upgrade to 1.3.6 and the !important flags will be gone.

**Comment by jaco-terbraak** [comment]
Thanks!

**Comment by jaco-terbraak** [comment]
How are you setting this style?
If you're trying to set this style by applying css to the containing component, I recommend you read up on Angular View Encapsulation.
