### ISSUE TITLE
Highlighting selected area

### ISSUE THREAD

**Issue by livthomas** [Mawi137/ngx-image-cropper#127]
Are there any plans to somehow highlight the selected area of an image? For example by blurring or darkening the rest of the image. Because the highlighted area is hard to spot and users might not notice the cropping feature in the application.

It looks great on this picture which you show everywhere. I initially thought the library worked this way but later realized it was not true.
![cropper-example](https://user-images.githubusercontent.com/2910853/51165596-05588780-18a1-11e9-915c-ccef5ac8d854.png)

**Comment by Mawi137** [comment]
It still does, this is a screenshot of the image cropper in the stackblitz example: (https://stackblitz.com/edit/image-cropper). It might look different depending on the image you upload. Maybe something isn't supported by the browser you're using?
![screenshot 2019-01-15 at 09 44 40](https://user-images.githubusercontent.com/5464100/51168679-3ab5a300-18aa-11e9-9d38-91e75aa47668.png)

**Comment by livthomas** [comment]
@Mawi137 Thanks. It seems that your example works with the images I use for testing. However, it does not work in our application. That's why I thought there is no such feature in this library.

You can check it out if you go to [https://www.mapotic.com/create](https://www.mapotic.com/create), click on image upload area in the sidebar and select some picture. Any ideas what might break it? I cannot find the blur effect anywhere. How is it implemented?

**Comment by livthomas** [comment]
I can see it now. `outline` CSS property which is used for this blur effect is overridden by our legacy CSS.
