### ISSUE TITLE
Can't bind to 'roundCropper' since it isn't a known property of 'image-cropper'.

### ISSUE THREAD

**Issue by akshatagawas123** [Mawi137/ngx-image-cropper#128]
after addind input for round crop this issue raised

**Comment by Mawi137** [comment]
Which version are you using? It's clearly there, so the only thing I can think of is that you're using an outdated version. Latesymt is 1.3.6

From source code:
`@Input() roundCropper = false;`

**Comment by jaco-terbraak** [comment]
Cannot reproduce this, it works fine for me with 1.3.4.
