### ISSUE TITLE
Grabbers render in the wrong place if box-sizing: border-box;

### ISSUE THREAD

**Issue by jaco-terbraak** [Mawi137/ngx-image-cropper#131]
![screenshot 2019-01-16 at 10 20 56](https://user-images.githubusercontent.com/34056076/51238974-71f28580-1978-11e9-83f0-5fedf8944fd7.png)

When `box-sizing` is set to `border-box` globally, the grabbers render like in the screenshot above. Maybe you could explicitly set it to `content-box` here, to avoid this issue.

**Comment by Mawi137** [comment]
Thanks added that to the styling!

**Comment by jaco-terbraak** [comment]
:+1:
