### ISSUE TITLE
Outline is too small

### ISSUE THREAD

**Issue by jaco-terbraak** [Mawi137/ngx-image-cropper#132]
![screenshot 2019-01-16 at 10 46 31](https://user-images.githubusercontent.com/34056076/51240520-24781780-197c-11e9-9466-fa5178f939c7.png)

The outline of the selection box is set at 1000px, which can be too small for larger components. I've personally overridden this to 100vw, to make sure it's never too narrow for the screen.

**Comment by Mawi137** [comment]
That should cover all landscape pages indeed, I also added a media query so it's set to 100vh when the orientation is portrait.

**Comment by jaco-terbraak** [comment]
Good point. Thanks!
