### ISSUE TITLE
Is there any way that I can give image to cropper as url, since I dont have any FileChangeEvent. I have Image already loaded on <img> tag.

### ISSUE THREAD

**Issue by vinishasasidharan** [Mawi137/ngx-image-cropper#135]

**Comment by Mawi137** [comment]
You can use a canvas to get the base64 encoded string which you can then pass to the image cropper using the `base64` input:
```
const c = document.getElementById("myCanvas");
const ctx = c.getContext("2d");
const img = document.getElementById("preview");
ctx.drawImage(img, 10, 10);
alert(c.toDataURL());
```

**Comment by farzaneHashemi** [comment]
thank you both very much for your useful conversation. 
I have the same issue and I have one additional question about this problem:
img is the image tag which our image is loaded on; but I don't understand the 'c'; I have to define an element with id='myCanvas' ? and it has to be hidden? 
could you plz put the html code as well? 
@Mawi137

**Comment by Mawi137** [comment]
This is a more complete solution:
To get the source of the image from the img tag use:
In your html: `<img #image src='http://image.com' />`
In your code
```
@ViewChild('image') image: ElementRef;

getBase64FromImageUrl(url: string) { 
    return new Promise((resolve) => {
      const img = new Image(); 
      img.onload = (imgData) => { 
        const canvas = document.createElement("canvas"); 
        canvas.width = imgData.width; 
        canvas.height = imgData.height;
        const ctx = canvas.getContext("2d"); 
        ctx.drawImage(imgData, 0, 0); 
        resolve(canvas.toDataURL("image/png"));
      }; 
    img.src = url; 
  });
}
```

//To use the function
```
getBase64FromImageUrl(image.nativeElement.url).then((imageBase64) => { ... });
```
Source: https://www.quora.com/Is-it-possible-to-convert-Image-tag-on-a-html-page-base64-string

**Comment by farzaneHashemi** [comment]
thank you for your response... 
but Intellij keeps throwing error and says there is no property width nor height on type Event! ( it assumes 'imgData' as an Event type... )
in addition it does not accept 'imgData' as an input property for drawImage method.
`Property 'width' is missing in type 'Event'.`

**Comment by farzaneHashemi** [comment]
I solved the problem with defining an image like this:
```
getBase64FromImageUrl2(url: string, callback) {
        let image = <HTMLImageElement>document.createElement('img');
        image.setAttribute('crossOrigin', 'anonymous');
        image.onload = function () {
            let canvas = <HTMLCanvasElement>document.createElement('canvas');
            canvas.width = image.width; // or 'width' if you want a special/scaled size
            canvas.height = image.height; // or 'height' if you want a special/scaled size
            canvas.getContext('2d').drawImage(image, 0, 0);
            callback(canvas.toDataURL('image/png'));
        };
        image.src = url;
    }
```
and the usage: 

```
this.getBase64FromImageUrl2(my_image_url, function(dataUri) {
                    scope.base64image = dataUri; 
});
```

**Comment by Mawi137** [comment]
Ah indeed I didn't test the code but apparently the onload function doesn't return anything, I updated my code so that should work. However, good to hear you found a solution !

**Comment by vinishasasidharan** [comment]
Thank you for the quick response. I will try it out. I have one more question, initially I dont want Cropper on my image. I know that I can set it with .cropper as display:none. But image gets autocropped on load, and I want full image without crop on load, and start cropping only on button click, else provide full image without cropped.

**Comment by Mawi137** [comment]
`aspectRatio` and `maintainAspectRatio` are two separate options, it's not the image's aspect ratio that is maintained, but the one you define with `aspectRatio`. You can set `autoCrop` to false then it will only crop if you call the crop function yourself. This is all in the README.md by the way..

**Comment by vinishasasidharan** [comment]
Okie, thanks for the reply. I tried using this and is working fine. But the problem that I am facing is, this plugin needs a canvas (without which it wont work according to me) on UI, if Iam passing base64String. What if I dont want this canvas (hiding is also fine)? I tried and this is throwing exception 

ERROR DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.

The problem statement is I already have image loaded on my page. And have to apply resize on that image. (without redrawing canvas on UI).

Please correct me if I am wrong

**Comment by Mawi137** [comment]
You either need a Blob (File) or base64. To get a base64 of the image, you'll need to pass it through a canvas. `const canvas = document.createElement("canvas");` won't show a canvas in your view.
