### ISSUE TITLE
Tips for noobs like me

### ISSUE THREAD

**Issue by Bonissauro** [Mawi137/ngx-image-cropper#141]
Although this lib helped my a lot (10x, Mawi), I've lost about SIX hours trying to understand the reason I was getting an error "TS2304: Cannot find name 'ImageCroppedEvent'". 

After reading the docs thousands of times (just to be sure I was doing everything I needed to make it work) and almost giving up, I realized this "little thing" I was missing: after registering in the app-module. ts, there's ALSO a need to import ngx-image-cropper to my component too:

import { ImageCroppedEvent } from 'ngx-image-cropper';

Only after that, I was able to use ngx-image-cropper.

I know it's a noob thing, but allow me to suggest you including this detail in the docs.

Best regards!

**Comment by Mawi137** [comment]
That's just basic TypeScript. When you use a type, class or interface, you'll have to import it. A decent editor like IntelliJ will find the import for you.
