### ISSUE TITLE
how to reselect the crop area

### ISSUE THREAD

**Issue by linbm** [Mawi137/ngx-image-cropper#142]
hello，
I want to reselect the selected area in the image area instead of dragging the checkbox.
Just like I can put the mouse in the area I want and start cutting directly from there.
Do I have to add any events?
thanks.

**Comment by Mawi137** [comment]
Just like you would in Photoshop for example?

**Comment by linbm** [comment]
Probably like that. Just like when we mouse over the picture, there will be a crosshair (cursor: crosshair), which makes it easy to reselect the target area.

**Comment by Mawi137** [comment]
Well it isn't supported yet, but can be added, I'd add a mousedown and touchevent on the sourceImage to start selecting the cropper position and then use rxjs' fromEvent operator for the move and up events.

**Comment by ShinRai1090** [comment]
Hey @bostondevin / @Mawi137, have you guys been able to do it? I'm also facing lot of issues with the cropper dragging. I'm still trying to get the cropper position values to work, and selecting the required area from the 4 corners of the image always is slowing the entire process a lot.

**Comment by IsaacHub** [comment]
@Mawi137 @bostondevin @ShinRai1090 
Any update on this feature? I desperately need this feature. 

It's unbelievable that this primary feature is not implemented yet. Do you have any workaround code, or ideas ?

**Comment by axos88-da** [comment]
Umm, not sure why I got tagged here
