### ISSUE TITLE
how can we fix width and height of cropper

### ISSUE THREAD

**Issue by KK220794** [Mawi137/ngx-image-cropper#148]
i tried fixing width and height of the cropper to certain pixels but was unable to get the results

**Comment by Mawi137** [comment]
Using max-width and max-height should work.

**Comment by KK220794** [comment]
I couldn't find any attribute named max-width and max-height. 
I tried fixing cropperMinWidth but then i am unable to fix height and also the cropper is flexible which doesn't fix the dimensions.

**Comment by Mawi137** [comment]
They are css styles

**Comment by savan2323** [comment]
I have tried to apply below CSS style on class cropper to make cropper size not adjustable, but it causes issues in cropping of the image, it would be cropping another area of an image, can anyone having a solution for this issue I have to make cropper size fix which is not adjustable?

```
.cropper { 
max-width : 357px;
min-width : 357px;
max-height : 280px;
min-height : 280px;
}
```
