### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by phamtranquocviet** [Mawi137/ngx-image-cropper#149]
Hi,
I successfully integrated your image cropper into my project. Works beautifully. Thanks a bunch.

One question: My image loaded in the cropper is a legend, and it has symbols to be cropped. However, some of the symbols are too small. How do I make the symbols (or the whole legend inside the cropper) bigger to make it easier to crop? Thanks in advance.

**Comment by Mawi137** [comment]
Do you maybe have a screenshot to clarify what you mean?

**Comment by phamtranquocviet** [comment]
<img width="119" alt="screen shot 2019-02-19 at 10 13 40 am" src="https://user-images.githubusercontent.com/10841811/53037451-1d3aa280-342f-11e9-8db6-1ffda1532b8e.png">

Please see attachment. Thanks for replying.

**Comment by Mawi137** [comment]
Ah yes now I understand, well the cropper loads the image and fills the available space. So in other words, it depends on screen size and the css styling you give it.
Another option would be being able to zoom in, but that's not supported yet.

**Comment by phamtranquocviet** [comment]
I have tried multiple packages, but none could help me zoom. Do you know a workaround? A package that works? Thanks.

**Comment by Mawi137** [comment]
It's not supported by this image cropper, but there are others out there that do.
