### ISSUE TITLE
Make resize squares bigger on mobile 

### ISSUE THREAD

**Issue by jbojcic1** [Mawi137/ngx-image-cropper#15]
@Mawi137 would it make sense to make resize squares a bit bigger on touch devices? It's really hard to point to it with finger currently with this size.

**Comment by Mawi137** [comment]
Hi, yes, but maybe not increase the squares' size itself, but increase the touch area round them.

**Comment by jbojcic1** [comment]
Even better

**Comment by jsitu** [comment]
This seems doesn't work on mobile browsers.

**Comment by victorivens05** [comment]
Another problem is that users can't scroll the page above the cropper, even if they're not "touch moving" above a specific element to resize or reposition.

A Mobile Improviment PR should be nice, I will try to do something, if someone wants to help I will appreciate.
