### ISSUE TITLE
Crash page on chrome 72

### ISSUE THREAD

**Issue by parys** [Mawi137/ngx-image-cropper#150]
Starting from 72 ( current 72.0.3626.109) and in this 72.0.3626.97 same crash. I think some API in browser changes that this library use. 

Steps: 
1 Try to load photo via input type=file, after selecting file browser Page crashes.

**Comment by Mawi137** [comment]
Does the example work?
https://stackblitz.com/edit/image-cropper

I'm using Chome 72 and it works fine for me.

**Comment by parys** [comment]
@Mawi137  thanks for quick answer. My bad, angular-cli unexpectedly break library work. Locally and you example works. Sorry that took you time.

**Comment by parys** [comment]
Found the cause of issue. Updated from old version, and still has own img tag that shows cropping elem. In production build it starts to be a cause of page crashes.
