### ISSUE TITLE
Invalid images not triggering loadImageFailed

### ISSUE THREAD

**Issue by Twista** [Mawi137/ngx-image-cropper#151]
Hello, 

I have found a few of our users is trying to upload fake images (renamed PDF to PNG).

Is there a way how to catch it? I mean, `loadImageFailed` is not triggered.

thanks for the great library! :)

**Comment by Mawi137** [comment]
It seems there's a better way than checking the blob type:
https://stackoverflow.com/a/42983450/2235443

I'll try to add it when I get the time

**Comment by Twista** [comment]
FYI I have solved it by this kind of snippet before I pass the event to the cropper

```typescript
 export function isValidImage(file: File): Promise<void> {
    return new Promise((resolve, reject) => {
        const imgElement = new Image();
        imgElement.onload = () => {
            resolve();
        };

        imgElement.onerror = () => {
            reject();
        };

        if (file) {
            imgElement.src = URL.createObjectURL(file);
        } else {
            reject();
        }
    });
}
```

**Comment by Mawi137** [comment]
Looks like a good solution. Thanks!

**Comment by Mawi137** [comment]
I decided not to implement this in the cropper, because if a user changes the extension and the app breaks, it's his problem :) To prevent malicious images to be uploaded, I've read that an easy way is to slightly resize the image on the backend.
