### ISSUE TITLE
event.width and event.height keep changing as I move the cropping window

### ISSUE THREAD

**Issue by Boussenna** [Mawi137/ngx-image-cropper#157]
I noticed that when I fix the cropping window and try to move it around the picture, the height and width of the cropping window keep changing with some pixels. Is there any way to fix that ?

**Comment by Mawi137** [comment]
Where it's maps the cropper position onto the actual image size, I use Math.round, so sometimes it will round up and sometimes it will round down. The larger the source image, the larger the difference probably is. Using Math.floor or Math.ceil instead might solve the problem, but only if the difference is only 1px now?

```
private getImagePosition(): CropperPosition {
        const sourceImageElement = this.sourceImage.nativeElement;
        const ratio = this.originalSize.width / sourceImageElement.offsetWidth;
        return {
            x1: Math.round(this.cropper.x1 * ratio),
            y1: Math.round(this.cropper.y1 * ratio),
            x2: Math.min(Math.round(this.cropper.x2 * ratio), this.originalSize.width),
            y2: Math.min(Math.round(this.cropper.y2  * ratio), this.originalSize.height)
        }
    }
```

**Comment by Boussenna** [comment]
I indeed used Math.ceil instead of Math.round. I also re-calculate the width and height using cropperPosition. Doesn't totally solve the issue so far, but it's the best work around I found.
