### ISSUE TITLE
Different paths on mobile devices

### ISSUE THREAD

**Issue by rafalschmidt97** [Mawi137/ngx-image-cropper#158]
Hi, 
Great library! Hope you have a great day.

Today I've encountered problem with paths depending on platforms. It works perfectly on any ios devices which return the name of url like:

```
DDD11EAB-BA2A-484E-82A5-F5E7A71EDF95.png
```

but on the other hand  android devices return weird path which is not recognised by this lib:

```
https_%2F%2Fspecials-images.forbesimg.com%2Fdam%2Fimageserve%2F42977075%2F960x0.jpg_fit=scale
```

I'm not sure is this even a problem of this library, but you may have any idea how to resolve this path and swap it before processing event.

**Comment by Mawi137** [comment]
Hi, this lib doesn't accept urls, only a file changed event, file or base64.

**Comment by rafalschmidt97** [comment]
Thanks @Mawi137. But the problem is that the event broadcasted by android devices is not valid (probably) and editor is blank. Any idea why? The url part I was talking about was just my investigation into why this might not work.

**Comment by Mawi137** [comment]
Sorry no, when I open my example on an Android device it works just fine: https://image-cropper.stackblitz.io

**Comment by rafalschmidt97** [comment]
Ahhh... The problem was with a photo. Sorry for that 🚀
