### ISSUE TITLE
TIFF format image isn't visible in html on Chrome

### ISSUE THREAD

**Issue by pragyasharma7** [Mawi137/ngx-image-cropper#159]
While the cropper support TIFF format but it doesn't display the image on Chrome browser.

**Comment by Mawi137** [comment]
It indeed seems that it doesn't work. Apparently Chrome & FireFox don't support drawing tiff images on HTML canvasses yet.

**Comment by pragyasharma7** [comment]
Isn't there anything we can do about it? Like converting tiff images in jpeg?

**Comment by Mawi137** [comment]
There's a min called Tiff.js that can do that, but I prefer not having it in this component because it makes the package size a lot larger and not many people will use Tiff. What you can do is convert the image yourself before giving it the the cropper.
