### ISSUE TITLE
What should i do to add direct source?

### ISSUE THREAD

**Issue by rennymroy** [Mawi137/ngx-image-cropper#16]
I have an image like (http://3.bp.blogspot.com/-yP2cOsXJrQI/VfmLlTDJSJI/AAAAAAAAAEA/UzhCbhwnWdE/s1600/indeks3.png). What should I do to crop this image?

**Comment by Mawi137** [comment]
You could transform the image url to a base64 string, which you can then give to the image cropper. An example of how you could transform the image url can be found here: https://forum.ionicframework.com/t/need-to-convert-image-url-to-base64-string/74449

**Comment by rennymroy** [comment]
I already did this. But there are some CORS issue.

**Comment by Mawi137** [comment]
CORS or mixed content? I copied the code from the URL I posted and it works fine: https://stackblitz.com/edit/angular-7fkrid?file=app%2Fapp.component.ts

Now if your site is HTTPS, you can only load images that are HTTPS. If not, you'll get a mixed content error.
