### ISSUE TITLE
Browser Crashes on load of ngx-image-cropper (Chrome 72)

### ISSUE THREAD

**Issue by tythambi** [Mawi137/ngx-image-cropper#160]
I have the last 3 daysto isolate the problem. It seems the moment you go from version 1.0.2 to 1.1.0+ produces the issue where I can see from my angular application logs that there is an unhandled errors:

TypeError: Cannot read property 'instance' of undefined
TypeError: Cannot read property 'subscribe' of undefined

Running the code locally works perfectly fine, as soon as its compiled to production and deployed the page with this component crashes. As soon as i downgrade to 1.0.2 or less. The issue is resolved.

I am upgrading so that i can use the change that you implemented from version 1.1.0 which handles resetting the aspect ratio. Is there any way u can point me to local fix until this is resolved. Otherwise your component works perfectly fine until upgrading.

**Comment by Mawi137** [comment]
Neither instance or subscribe is used in my code so I'm not sure where this is coming from. Latest version is `1.3.8`. It's possible that some inputs or outputs have changed and have a new name.

**Comment by tythambi** [comment]
I tried to upgrade to a handful of versions.. but any version including and after 1.1.0 is throwing this error had crashing my chrome. I use this component in 2 places... what i do notice as a clue, as soon as i remove the following event "(imageCropped)="imageCropped($event)" the page loads. As a short term, can you point me to a workaround to resetCropperPosition when i change aspectratio.. that is the only reason i am upgrading. This is a production issue, your help would be hugely appreciated.

**Comment by Mawi137** [comment]
What happens if you replace your imageCropped function with:
```
imageCropped(event) {
    console.log(event);
}
```
Does that work and print out the event to the console?

**Comment by tythambi** [comment]
I am not able to reach this event. As soon as the page loads with this control, it hangs and then crashes. Currently, I am on version 1.0.2... locally running works perfect, as soon as I compile for production and then deploy, on the production server the page crashes.. it happens in both pages that use it so i can narrow the issue to this component.

**Comment by Mawi137** [comment]
Well it doesn't matter whether you have `"(imageCropped)="imageCropped($event)"` or not, that doesn't affect what the image cropper does. So that means the issue is in the `imageCropped` method you implemented. Since version 1.1.0 `imageCropped` output changed and emits an object instead of just a base64 string: https://github.com/Mawi137/ngx-image-cropper#imagecroppedevent

**Comment by tythambi** [comment]
So I have followed every step to be very sure in the last 3 days.

1. npm install ngx-image-cropper --save (Installs 1.3.8)

2. Changed the function imageCropped
imageCropped($event: ImageCroppedEvent) {
    console.log($event);
    this.croppedImage = $event.base64;
  }

3.  Changed function in html (imageCropped)="imageCropped($event)"

This works perfectly locally. Then compiling this for production and deploying fails with browser crashing. Then if i remove the line from html, the page loads again. Secondly, if i revert back to older version 1.0.2 then page loads again.

**Comment by Mawi137** [comment]
Then I'm out of idea's, I've got it working fine in a prod build here..

**Comment by tythambi** [comment]
Is there any way u can give me an idea to change aspectRatio and reflect that in the cropper component for version V1.0.2 ? I see in another closed request that same question was asked, but the fix is in a newer version. This will be a short term until i can pinpoint on whats preventing me from upgrading

**Comment by Mawi137** [comment]
I don't think there's a workaround for that, it needs to call the `resetCropperPosition` method, but it's private so you cannot access it.
