### ISSUE TITLE
Can not file is not grabbed after ng build

### ISSUE THREAD

**Issue by s-triar** [Mawi137/ngx-image-cropper#161]
I am successfully crop the image then preview it using css background-image: url.  When I running it on local using `ng serve` it successful to upload. But when I deploy it failed to upload the file. It can crop and preview as well but it can not grab the file when I upload. it says File is not exist. I build my angular project using ` ng build --prod --aot --extract-css --build-optimizer --optimization` 

BTW I dont include the code in section **Polyfill for IE and Edge** in my code.

**Comment by Mawi137** [comment]
No specific error? What happens if you log the ImageCroppedEvent? It works fine for me when I run a build with all those flags

**Comment by s-triar** [comment]
yes it work well. I preview as after cropped as well. but if I send it, I got error file does not exist in my back end (laravel).

but I somehow fixed it. I think because the version of php on my web host ( i use 000webhost). so it didn't catch the file and give error file does not exist.

thank you. sorry for not confirm it. and close the issue. I forget that i asked here
