### ISSUE TITLE
Not able to build module

### ISSUE THREAD

**Issue by imbdb** [Mawi137/ngx-image-cropper#162]
```
WARNING in ../ngx-image-cropper/node_modules/@angular/core/fesm5/core.js 4982:15-36
Critical dependency: the request of a dependency is an expression

WARNING in ../ngx-image-cropper/node_modules/@angular/core/fesm5/core.js 4994:15-102
Critical dependency: the request of a dependency is an expression
```

Got this error after trying to use the local build of module.

**Comment by Mawi137** [comment]
This is after running `npm install` and then `npm build`?

**Comment by imbdb** [comment]
Yes.
I built the module and then tried using it in a demo project but got this error.

**Comment by Mawi137** [comment]
```
npm install
npm run build
npm run pack-lib
```
That should give you a *.tgx file you can use locally. I just deleted my node_modules folder and ran these command which works fine, so I've no idea what's going wrong for you.

**Comment by imbdb** [comment]
That worked.
Can you please update readme with the instructions to build and contribute.
