### ISSUE TITLE
compress image

### ISSUE THREAD

**Issue by Songux** [Mawi137/ngx-image-cropper#164]
Hello guys.
I think you should add image compression feature in the next version. that is nice.
Thanks

**Comment by Mawi137** [comment]
Hi @Songux, I don't think that should be part of this library. You could simply take the output of this component and use another library to compress that image before submitting it.

**Comment by Songux** [comment]
Thanks for what you do. I like it.

**Comment by Mawi137** [comment]
You're welcome ;)

**Comment by Jalil-Irfan** [comment]
> Hello guys. I think you should add image compression feature in the next version. that is nice. Thanks

I too felt it would be great if the compressing option comes with the cropper. Struggling to make the cropped image to 20kb
