### ISSUE TITLE
Cropped Image Poor Quality

### ISSUE THREAD

**Issue by anikets43** [Mawi137/ngx-image-cropper#165]
@Mawi137 I tried adding imageQuality, adjusting aspect ratio, but the cropped image is still blur.. Is there any workaround to preserve the image quality

![image](https://user-images.githubusercontent.com/7136799/56076543-2a9d5900-5df0-11e9-8a6b-46cf5a6fcbf2.png)

**Comment by Mawi137** [comment]
Hi @anikets43
You can remove the resizeToWidth, that should improve the image quality.

**Comment by anikets43** [comment]
Thanks @Mawi137 
It worked :)
