### ISSUE TITLE
Croped images do not maintain aspect ratio

### ISSUE THREAD

**Issue by vytautas-petrikas** [Mawi137/ngx-image-cropper#167]
Cropped images do not maintain aspect ratio in some cases.

For example when 300x300 image is cropped and resized to 360x270 the result dimensions do not maintain the provided aspect ratio `4 / 3`.

<img width="267" alt="chrome_DSTgGtKRkF" src="https://user-images.githubusercontent.com/46673460/56351209-41b7be80-61d5-11e9-938a-bf01aaf61342.png">

This is the image I used for testing:
<img width="150" alt="300x300" src="https://user-images.githubusercontent.com/46673460/56350530-a2de9280-61d3-11e9-879c-957643b02ad3.png">

I have created a stackblitz app for troubleshooting;
Stackblitz example: https://stackblitz.com/edit/angular-qzyrrw

I will try to find the main cause and open a pull request. (I'll update this issue)

**Comment by Mawi137** [comment]
Hi there,
I don't know whether that will be easy to achieve. When cropping the width and height are rounded (you can't have a half pixel) and then the image is scaled up or down (up in your case) and again the height will be rounded, else you'll get a white pixel line. Feel free to open a PR if you find a good solution!

**Comment by vytautas-petrikas** [comment]
@Mawi137 sorry, for late reply.
I have submitted a pull request containing a work-around I am currently using.

Let me know if I can improve the code in any way.
