### ISSUE TITLE
Add EXIF orientation handling

### ISSUE THREAD

**Issue by jordanro** [Mawi137/ngx-image-cropper#17]
Currently uploaded images are not properly oriented according to the exif data

**Comment by Mawi137** [comment]
Hi jordanro, not sure what you mean. Could you elaborate a little?

**Comment by jordanro** [comment]
Uploading an image with Portrait orientation would display in landscape.
Usually orientation data can be obtained from the EXIF data on the image file.

<img width="448" alt="screen shot 2018-02-22 at 9 53 51" src="https://user-images.githubusercontent.com/892929/36526337-8c640a70-17b6-11e8-9812-d89aa5c0215b.png">

**Comment by franknwankwo** [comment]
different mobile devices orient the image at different degrees. You have to manually handle each case. If you want an example of how  this is doe you can check what they did in this angular 2 image cropper: https://github.com/cstefanache/angular2-img-cropper/blob/master/src/exif.ts

**Comment by noilly** [comment]
+1

**Comment by Lizonchik** [comment]
I have this problem only with photos which made with help iOS devices

**Comment by Mawi137** [comment]
Hi, the image cropper now checks for the EXIF rotation and rotates the image accordingly. Seems to be working fine for me now! (version 0.2.8)

**Comment by Godsonalex12** [comment]
Hi, in some mobile devices some images get flips automatically after uploading, due to EXIF rotation, I guess. How to override manually or in the image-cropper after uploading?
