### ISSUE TITLE
Rotating inside angular modal

### ISSUE THREAD

**Issue by KieranMcKeefery** [Mawi137/ngx-image-cropper#172]
This is an excellent module and I've got it setup for the cropping to happen in an angular module but for some reason I can't get rotating working inside of NgbModal. Cropping works a treat but nothing else does.

Has anyone got any ideas please?

**Comment by KieranMcKeefery** [comment]
I've actually had a brain fart here and managed to sort it myself so for anyone out there that wants a fix for this please take a look at the following code:

`<button type="button" (click)="imageCropper.rotateLeft()">Rotate Left</button>`

`<image-cropper #imageCropper [imageChangedEvent]="imageChangedEvent" [maintainAspectRatio]="true" [aspectRatio]="1" [resizeToWidth]="500" [cropperMinWidth]="500" [cropperMinHeight]="500" format="jpg" [onlyScaleDown]="true" (imageCropped)="imageCropped($event)" (imageLoaded)="imageLoaded()" (cropperReady)="cropperReady()" (loadImageFailed)="loadImageFailed()"></image-cropper>`

Instead of using viewChild I'm instead using the component functions directly.

**Comment by Mawi137** [comment]
Glad you found a fix! I'll close this issue.
