### ISSUE TITLE
Issue with loadImageFailed in the StackBlitz demo when the component is styled as hidden. Unable to autocrop

### ISSUE THREAD

**Issue by calebjonasson** [Mawi137/ngx-image-cropper#173]
Angular: 5.2
Node: 8.12

In the demo there is the following code:

`[style.display]="showCropper ? null : 'none'"`

By hiding the element this way the component is not able to be used correctly. The underlying code base performs the function `checkImageMaxSizeRecursively` but is unable to find the container which emits an error to load the image. This prevents images from being loaded correctly even though an event is being thrown that the image has loaded because the code is unable to apply the image to a container in the DOM.

I think a correct solution would be to make the `loadImageFailed` output more verbose and pass an error through it. This would give the implementing developer more information as to why the image failed to load since the document just says that it is thrown when the file type is incorrect.
 
Another possible solution would be to create an input to prevent the cropper from rendering although I believe this would require work to be done in the underlying library.

Also, thanks for maintaining this package. It's pretty slick!

**Comment by Mawi137** [comment]
The cropper is hidden until the image is loaded and emits `imageLoaded`. That should show the cropper and then the `checkImageMaxSizeRecursively` should go to work and will emit `cropperReady`. The stackblitz works fine for me btw or are you maybe using a very large image?
