### ISSUE TITLE
File explorer window always opens when imageCropped($event) executes

### ISSUE THREAD

**Issue by jason-jason-h** [Mawi137/ngx-image-cropper#174]
Thanks for this lib.  I like it very much, but here is my issue:

I have the cropper working nicely for the most part.  However, with an image loaded via:
`<input type="file" (change)="fileChangeEvent($event)" />
      <image-cropper [imageChangedEvent]="imageChangedEvent" [maintainAspectRatio]="true" [aspectRatio]="17 / 4"
          [resizeToWidth]="595" format="png" (imageCropped)="imageCropped($event)" (imageLoaded)="imageLoaded()"
          (cropperReady)="cropperReady()" (loadImageFailed)="loadImageFailed()" [autoCrop]="true">
      </image-cropper>
`
Then user moves the crop indicators and releases the mouse.

Should trigger:
`imageCropped(event: ImageCroppedEvent) {
    this.croppedImage = event.base64;
}`

but it is also re-opening the HTML file upload dialog again. 

Everything else works, but there is this extra step to close that second dialog...

**Comment by Mawi137** [comment]
That's very odd, does the example on stackblitz have the same issue for you? - https://stackblitz.com/edit/image-cropper

**Comment by jason-jason-h** [comment]
No, it does no do the same on THAT Stackblitz.

Here's a demo of the issue...
[https://stackblitz.com/edit/angular-yzmme6](https://stackblitz.com/edit/angular-yzmme6)

**Comment by Mawi137** [comment]
In your image template html, you're using `<label></label>` to wrap the label + image cropper, so no matter what you click within that label, will trigger the file input. To fix, simply move the `</label>` tag up a little to this line: `<label><span class="label">{{data.instruction}}</span></label>`

**Comment by jason-jason-h** [comment]
Couldn't ask for a better answer than that!  Your suggestion worked 100%.  

It's always nice to have an extra set of eyes...

I will reiterate my previous comment, "Thanks for this lib. I like it very much."
