### ISSUE TITLE
Rotate image based on exif data when setting via imageBase64

### ISSUE THREAD

**Issue by lukaskupczyk** [Mawi137/ngx-image-cropper#175]
Thank you for maintaining this great package.

Somehow when I set an image via [imageBase64] the orientation (portrait/landscape) setting via the exif data doesn't work. Is it possible this feature is only implemented on the imageChangedEvent/input side?

Thank you.

**Comment by Mawi137** [comment]
Hi there, just fixed that, it only checked the exif rotation when using the imageChangedEvent input, it should work for imageBase64 now as well (version `1.3.10`). Thanks for reporting this!

**Comment by lukaskupczyk** [comment]
Working great! Thank you!
