### ISSUE TITLE
Metadata version mismatch found version 4, expected 3?

### ISSUE THREAD

**Issue by dawidlipinski** [Mawi137/ngx-image-cropper#176]
Hi folks,

I have set up image cropper but I can't compile my app because of the following error:

**ERROR in Error: Metadata version mismatch for module [...] found version 4, expected 3.**

Could you please advise on how to resolve that?

My dependencies:

`		"@angular/animations": "^4.4.3",
		"@angular/common": "^4.4.3",
		"@angular/compiler": "^4.4.3",
		"@angular/core": "^4.4.3",
		"@angular/forms": "^4.4.3",
		"@angular/http": "^4.4.3",
		"@angular/platform-browser": "^4.4.3",
		"@angular/platform-browser-dynamic": "^4.4.3",
		"@angular/platform-server": "^4.4.3",
		"@angular/router": "^4.4.3",
		"@types/bootstrap": "^3.3.36",
		"angular-confirmation-popover": "^3.4.0",
		"angular2-datatable": "^0.6.0",
		"blueimp-canvas-to-blob": "^3.14.0",
		"bootstrap-confirmation2": "^2.4.0",
		"classlist.js": "^1.1.20150312",
		"core-js": "^2.5.1",
		"font-awesome": "^4.7.0",
		"intl": "^1.2.5",
		"jquery": "^3.2.1",
		"moment": "^2.22.2",
		"ng2-ckeditor": "1.1.9",
		"ng2-datepicker": "^1.8.3",
		"ng2-daterangepicker": "^2.0.12",
		"ng2-file-input": "0.1.13",
		"ngx-image-cropper": "^1.3.10",
		"ngx-pagination": "^3.0.1",
		"npm": "^6.7.0",
		"rxjs": "^5.4.3",
		"uglify-js": "^2.8.29",
		"web-animations-js": "^2.3.1"`

Thanks a lot

**Comment by Mawi137** [comment]
I have no idea to be honest.
