### ISSUE TITLE
Allow free ratio

### ISSUE THREAD

**Issue by Joniras** [Mawi137/ngx-image-cropper#177]
Is there any way we are allowed to **freely choose our aspect ratio** ?

If you drag the orange-circled edges it really only moves this line and not the others too:

![image](https://user-images.githubusercontent.com/8112178/58954784-69211580-879a-11e9-9ed2-e2adffa16a78.png)

This could be achieved with something similar to this:
`[apsectRation]="'free'"` or even better `[apsectRation]="'¯\_(ツ)_/¯'"`

**Comment by Mawi137** [comment]
Hi there,
`maintainAspectRatio` is set to `true` by default, setting that to `false` should solve the issue?

**Comment by Joniras** [comment]
Im sorry if i wasted your time with this issue, i oversaw this feature. 
Closing
