### ISSUE TITLE
Not working on touch devices

### ISSUE THREAD

**Issue by nileshbhagwat** [Mawi137/ngx-image-cropper#18]
Currently not working on these browsers 
1. iPad safari
2. Android Chrome

Any workaround/updates?

**Comment by Mawi137** [comment]
It works on Android Chrome for me, I don't have an iPad, so I can't test that.
There is another issue open to increase the touch area around the dots.
You have to be quite precise to move them now indeed.

**Comment by nileshbhagwat** [comment]
Current demo on stackblitz working, previous plunker example was not working. 

Thank you, this module is really useful.
