### ISSUE TITLE
Extreme Lags and Unresponsive since Chrome for Android version >75

### ISSUE THREAD

**Issue by picciama** [Mawi137/ngx-image-cropper#181]
After Chrome for Android version 75 came out a few days ago, the crop area is randomly unresponsive to dragging and resizing and one instead scrolls up and down the page/modal when dragging up/down. 
When it works, it is extremely laggy on the other hand: After each crop, it takes a few seconds until it reacts to further touch events.  

Chrome 75 on Debian and Win 10 are not affected it seems.
Might have to do sth. with scrolling while an image is loaded.

**Comment by Mawi137** [comment]
Hi tested it on Chrome 75 and I don't have any issues, so I'm not sure what I can do to help here

**Comment by picciama** [comment]
Hi Mawi, sth. seems to be wrong with the ngsw-worker.js serviceworker on android devices. I had many more troubles and after deactivating the serviceworker, everything went back to normal. The angular ngsw-worker package seems to be very buggy on android. The image cropper always worked flawlessly when the ngsw-worker wasn't registered so it isn't a problem with ngx-image-cropper.
