### ISSUE TITLE
How to get the cropped data as File

### ISSUE THREAD

**Issue by ashish-dirkmedia-de** [Mawi137/ngx-image-cropper#182]
I am using event (imageCropped)="imageCropped($event)" to get the data. It returns event of type ImageCroppedEvent with base64 data.
I want the output as File to upload on server directly.
Can you please guide me

**Comment by Mawi137** [comment]
Simply set `outputType` to `file' or `both` and you'll get a blob in the output. It's all in the readme.

**Comment by Vo0Do0** [comment]
event.base64 is giving the cropped file but  event.file object is giving the actual file not the cropped file. Please Help me out.

**Comment by initplatform** [comment]
Has this changed?

`core.js:12626 Can't bind to 'outputType' since it isn't a known property of 'image-cropper'.`

I am only getting the Base64 as well

**Comment by bragsoufian** [comment]
The same here :(

**Comment by ReaperTech** [comment]
I have the same issue. outputType is not a valid property. The ImageCroppedEvent only has base64, and no file?

**Comment by Mawi137** [comment]
Update instructions can be found here: https://github.com/Mawi137/ngx-image-cropper/releases
