### ISSUE TITLE
Transparent background is converted to Black when using jpeg format

### ISSUE THREAD

**Issue by robinnau** [Mawi137/ngx-image-cropper#183]
When uploading a Picture of type .png and convert them to .jpeg to save memory it gets converted to black pixels.
Is there a way to change the color the background gets changed to?

**Comment by robinnau** [comment]
i forked it and added the ability to change the background color
https://github.com/robinnau/ngx-image-cropper

**Comment by Mage111** [comment]
I'm still getting black background when the original background is transparent. I'm using version: "ngx-img-cropper": "11.0.0",
how can I keep the original background color?
