### ISSUE TITLE
Support for Angular 4

### ISSUE THREAD

**Issue by miraxes** [Mawi137/ngx-image-cropper#186]
Best way to do it is welcome 🙇

**Comment by captaincaius** [comment]
Hi neighbor :wave: 
I was using it on angular 4 before I upgraded to 7 with no issues.  What problem are you having?

**Comment by miraxes** [comment]
when you are trying to build it with AoT it throws metadata mismatch error like described in https://github.com/Mawi137/ngx-image-cropper/issues/176

**Comment by Mawi137** [comment]
It indeed appears that something changed between Angular 4 and 5. This package is build with Angular 6, which makes it incompatible with Angular 4 appearantely. 
Is there any reason why you are still using Angular 4? Updating to Angular 5 should be fairly easy which would solve this problem. Also, Angular 4 and 5 are no longer supported by the Angular team, so upgrading to an even higher version would even be better, so you still receive all bugfixes and security patches.

**Comment by miraxes** [comment]
@Mawi137 @captaincaius 
Thank you guys. I will upgrade my Angular ASAP, but now it is not a way. Also, I built your lib on lower versions of ng-pakgr so lets leave link here in case if someone needs it too. https://github.com/miraxes/ngx-image-cropper
