### ISSUE TITLE
Reset to original

### ISSUE THREAD

**Issue by ashish-dirkmedia-de** [Mawi137/ngx-image-cropper#187]
Is their a way to reset the image to original. Like after flip etc and then reset will reset back to original

**Comment by justvovus** [comment]
I would also like to have such method, I think it is pretty logical addition to flip, rotate, etc.
Button to reset a cropper to its initial state with a current image.

**Comment by albert-hoffman** [comment]
store original source and click on reset button just put it back.

**Comment by Mawi137** [comment]
Just added `resetImage` in version `2.0.2`.

**Comment by NimishDavid** [comment]
> 
> 
> store original source and click on reset button just put it back.

Are you referring to the `safeImgDataUrl`? I need to do something similar where I want to restore the previously opened image if a choose file dialog is cancelled. I tried restoring `safeImgDataUrl` of the previous image, and it restores the image. But, if I crop the image, the crop doesn't apply on the restored image, instead it applies on the opened image. Any idea on how to do this?
