### ISSUE TITLE
Portrait image fails to crop in iPhone (Safari). Seeing negative width/height.

### ISSUE THREAD

**Issue by KrishnaSharmaCC** [Mawi137/ngx-image-cropper#188]
Hi @Mawi137 ,
I am having this issue wherein if i select a portrait image to crop, the cropper behaves in a weird way.
[This is the link to the screen recording which depicts the behavior.](https://drive.google.com/file/d/1KBGPiOLxTEvJsGimAzvxTyfePscibhR9/view?usp=sharing)
if i try to move the crop area, It shows the width/height in negative numbers. Also nothing happens when i try to call the crop() function when i am in one of those regions. I am facing this issue primarily in iPhone iOS 12.1+. I was just wondering if this issue is caused by the **canvas size limitation** in iPhones because of which it is not able to draw the image on canvas properly? [More about it here.](https://stackoverflow.com/questions/6081483/maximum-size-of-a-canvas-element)
Just to add a note: I am limiting the image that is being fed into the cropper to be <= 12 MP which is well within the canvas limit.
Steps to reproduce: 
1. Implement the cropper
2. Try to upload a **Portrait** image file from **iPhone** into the cropper.
3. Move the crop area.

**Comment by Mawi137** [comment]
Are you using `resizeToWidth` or `resizeToHeight`?

I don't have an iPhone myself and in my emulator I'm unable to reproduce it.

**Comment by KrishnaSharmaCC** [comment]
@Mawi137 , Sorry for the late reply.  The `resizeToWidth = 0`.  
My cropper options are:
![Code_2019-06-28_15-20-10](https://user-images.githubusercontent.com/42341447/60334059-3c86a500-99b8-11e9-87c4-c74c55d83ab6.png)

Since, i do not have a iOS emulator, i had to dump the cropper data to view itself. This is what the imagePosition and cropperPosition is:

```
width: 2144
height: -477

imagePosition: {
x1: 751,
y1: 2925,
x2: 2895,
y2: 2448
}
cropperPosition" {
x1: 55,
y1: 214.21,
x2:212,
y2: 296.84,
}
```

![Image from iOS](https://user-images.githubusercontent.com/42341447/60333992-1c56e600-99b8-11e9-8eaa-b81d487b2944.png)

Hope it helps :)

**Comment by Mawi137** [comment]
Hmm very odd, the cropperPosition is correct y1 < y2. The imagePosition isn't because y1 > y2. This is the code that transforms the cropperPosition to the imagePosition:
```
private getImagePosition(): CropperPosition {
        const sourceImageElement = this.sourceImage.nativeElement;
        const ratio = this.originalSize.width / sourceImageElement.offsetWidth;
        return {
            x1: Math.round(this.cropper.x1 * ratio),
            y1: Math.round(this.cropper.y1 * ratio),
            x2: Math.min(Math.round(this.cropper.x2 * ratio), this.originalSize.width),
            y2: Math.min(Math.round(this.cropper.y2 * ratio), this.originalSize.height)
        };
    }
```
So the same functions are applied to x and y. x is correct, y isn't.. Do you only have this issue with large images or always with portrait images?

**Comment by KrishnaSharmaCC** [comment]
> Hmm very odd, the cropperPosition is correct `y1 < y2`. The imagePosition isn't because `y1 > y2`. This is the code that transforms the cropperPosition to the imagePosition:
> 
> ```
> private getImagePosition(): CropperPosition {
>         const sourceImageElement = this.sourceImage.nativeElement;
>         const ratio = this.originalSize.width / sourceImageElement.offsetWidth;
>         return {
>             x1: Math.round(this.cropper.x1 * ratio),
>             y1: Math.round(this.cropper.y1 * ratio),
>             x2: Math.min(Math.round(this.cropper.x2 * ratio), this.originalSize.width),
>             y2: Math.min(Math.round(this.cropper.y2 * ratio), this.originalSize.height)
>         };
>     }
> ```
> 
> So the same operations are applied to `x` and `y`. `x` is correct, `y` isn't...
> 
> Do you only have this issue with large images or always with portrait images?

@Mawi137, sorry for the late reply. I am having this problem with very large images and also portrait images.
