### ISSUE TITLE
cropper shifts to the right

### ISSUE THREAD

**Issue by wtondu** [Mawi137/ngx-image-cropper#189]
After an image is loaded the image and cropper are lined up over each other ok but the entire image has shifted to the right because of this 'margin-left':   How do I stop this movement?

element.style {
    top: 0px;
    left: 0.25px;
    width: 415.5px;
    height: 554px;
    margin-left: calc(50% - 208px);
    visibility: visible;
}

**Comment by Mawi137** [comment]
You can use the `alignImage` input and set it to `left`. By default the image is centered

**Comment by wtondu** [comment]
Cool that sets the cropper lines to the left but the image stays in the same place; right shifted. Any ideas?  Thanks for such a quick response!

--
Walter Tondu

**Comment by wtondu** [comment]
Is there a fix for the issue noted in my last post?

**Comment by Mawi137** [comment]
Hi sorry can you add a screenshot, I don't quite understand the problem.

**Comment by wtondu** [comment]
I"m unable to attach a file here but here's a link to the images.  After adding the alignImage input the cropper moves left but the image stays centered, hence they are not overlapping correctly.   http://tondu.com/rv8a/wp-content/uploads/2019/07/cropper.png

**Comment by wtondu** [comment]
Does the image help to identify what is happening?

**Comment by Mawi137** [comment]
Is there maybe any of your css overwriting the styles of the cropper?

**Comment by wtondu** [comment]
Nope I’ve extracted if from everything just to make sure.  
There seems to be additional padding being placed on left and right sides in order to make the element be a square instead.
The cropper is shifted to the left side of that padding but the image remains.

**Comment by Mawi137** [comment]
In my example here it works fine: https://stackblitz.com/edit/image-cropper
So some external css styling is all I can think of.
