### ISSUE TITLE
"The source width is 0" error message

### ISSUE THREAD

**Issue by roothema** [Mawi137/ngx-image-cropper#190]
Hi, 

i have a regular image with .PNG extension and for some reason after the image loading i got the following error: 

`ERROR DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at resizeCanvas`

I have no idea about this error because i've tested the cropper with a few image and it worked. 

This is the image what i used to trigger the error.

![embed (1)](https://user-images.githubusercontent.com/3306657/60608357-94118000-9dbf-11e9-9894-632ef04105d3.PNG)

Thanks in advance

**Comment by albert-hoffman** [comment]
No one is providing any solution for this bug.

**Comment by oldschoolbg** [comment]
I have this as well...

**Comment by oldschoolbg** [comment]
UPDATE:

https://github.com/Mawi137/ngx-image-cropper/issues/143

this fixed it for me :)
