### ISSUE TITLE
It is possible to add zooming with transform: scale property?

### ISSUE THREAD

**Issue by albert-hoffman** [Mawi137/ngx-image-cropper#193]
Have added this module for crop and rotate and now the issue is that if I want to zoom in or out, then I have to add a new module. it is not a good idea. if possible can we add zoom in/out using transform: scale?

**Comment by Mawi137** [comment]
Hi there, zooming in and out isn't an easy task because of how this image cropper is built. How would you move the image when it's zoomed in? The cropper itself sits in front of the image..

**Comment by shashivnaad** [comment]
can i  add it

**Comment by albert-hoffman** [comment]
We don't have to move an image, we have to just zoom it, then cropper will move here and there.

**Comment by Mawi137** [comment]
Hi @albert-hoffman, as of version `3.0.0` the zoom in and out functionality has been added. More info: https://github.com/Mawi137/ngx-image-cropper/releases/tag/3.0.0
