### ISSUE TITLE
Uploading Image more then 5 MB It's Slower the processing

### ISSUE THREAD

**Issue by AyazBelim** [Mawi137/ngx-image-cropper#194]
When i am uploading image more then 5 MB it's taking longer time to show and processing.. and cropping area also slow down for cropping.
Please let me know if there any alternate way to how to deal such high MB Images ?

**Comment by Mawi137** [comment]
What you could do is set `autoCrop` to false and then use the `crop` method to get the resulting image. About the loading itself, there's not much to do as far as I know. It simply loads the image into a base64 and shows it.

**Comment by AyazBelim** [comment]
Hi @Mawi137 
I really appreciate your help and rather to set [autoCrop] to false.
i have founded much better solution to deal with High MB images by compressing before sending to cropper and it worked smoothly for any size of Image.
if any want that compressor just text me i will provide here.

**Comment by fernandopioli** [comment]
Ayazbelim, could you provide us the compressor? I’m in same problem.

**Comment by AyazBelim** [comment]
Sure @fernandopioli 

import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
@Injectable({
    providedIn: 'root'
})
export class compressService {

    constructor() { }
    compress(file: File): Observable<any> {
        const width = 600; // For scaling relative to width
        const reader = new FileReader();
        reader.readAsDataURL(file);
        return Observable.create(observer => {
            reader.onload = ev => {
                const img = new Image();
                img.src = (ev.target as any).result;
                (img.onload = () => {
                    const elem = document.createElement('canvas'); // Use Angular's Renderer2 method
                    const scaleFactor = width / img.width;
                    elem.width = width;
                    elem.height = img.height * scaleFactor;
                    const ctx = <CanvasRenderingContext2D>elem.getContext('2d');
                    ctx.drawImage(img, 0, 0, width, img.height * scaleFactor);
                    ctx.canvas.toBlob(
                        blob => {
                            observer.next(
                                new File([blob], file.name, {
                                    type: 'image/jpeg',
                                    lastModified: Date.now(),
                                }),
                            );
                        },
                        'image/jpeg',
                        1,
                    );
                }),
                    (reader.onerror = error => observer.error(error));
            };
        });
    }
}

**Comment by AyazBelim** [comment]
You can use by below example


 if (mimeType.match(/image\/*/)) {
      const compress = this.recursiveCompress(
        event.target.files[0],
        0,
        event.target.files
      ).pipe(
        expand(res => {
          return res.index > res.array.length - 1
            ? EMPTY
            : this.recursiveCompress(
              event.target.files[res.index],
              res.index,
              event.target.files
            );
        })
      );
      this._compress = compress.subscribe(res => {
        if (res.index > res.array.length - 1) {
          $("#processCard").modal("hide");
          //Code block after completing all compression
          this.trackImgCardValue = 1;
          $("#myModal").modal({ backdrop: "static", keyboard: false });
          this.imageChangedEvent = res.data;
          $("#imgFrontInput").val(null);
        }
      });




recursiveCompress = (image: File, index, array) => {
    return this.compressor.compress(image).pipe(
      map(response => {
        //Code block after completing each compression
        console.log("compressed " + index + image.name);
        return {
          data: response,
          index: index + 1,
          array: array
        };
      })
    );
  };
