### ISSUE TITLE
Set cropper height and width as fixed

### ISSUE THREAD

**Issue by vivek1996** [Mawi137/ngx-image-cropper#196]
May i know how can i set the cropper width and height as fixed. 
In my case there are 2 input fields height and width respectively. after image is chose the user can enter the height and width the image need to be. How this can be achieved ?
Thank You.

**Comment by code-vagabond** [comment]
There seems to be no interface for this yet but you can overwrite the [CSS of resize cursors](https://github.com/Mawi137/ngx-image-cropper/blob/master/src/component/image-cropper.component.scss#L79) to make them invisible or fork the component and get rid of all the event handlers for the resize action ([e.g](https://github.com/Mawi137/ngx-image-cropper/blob/master/src/component/image-cropper.component.html#L20))

**Comment by priyarajagopal1126** [comment]
Is there any way to give fixed width and height to cropper, so that it should not allow to resize.

**Comment by KrishnaSharmaCC** [comment]
@Mawi137, is it possible to add support for this feature? Requirement in our project slightly changed and i couldn't figure out a way to enable this with the current implementation. Any help is highly appreciated. Thanks :)
