### ISSUE TITLE
Should be able to disable resize with locked aspect ratio

### ISSUE THREAD

**Issue by Zackazt** [Mawi137/ngx-image-cropper#198]
If I have an image that I need to end up at some specific resolution (ex: 1200 x 350), I would want to disable the ability to change the size of the cropper. It should instead be a fixed height and width, and the user could then move the cropper around the image to find the area they want to be cropped.

A boolean input called resizable is a solution. Then if resizable is false, we would need to require the aspect ratio input, and use it to calculate the dimensions for the cropper. Then of course disable the controls for resizing.

**Comment by ashish-dirkmedia-de** [comment]
Can you let me also know how you fixed this. I require this too.

**Comment by adityatyagi** [comment]
@Zackazt Please let us know how were you able to accomplish the use-case as even I am stuck for the past 2 days.
Thanks!
