### ISSUE TITLE
IE + Edge Polyfill - Where to add the code

### ISSUE THREAD

**Issue by ninjavis** [Mawi137/ngx-image-cropper#199]
Hi there! Thank you so much for this awesome tool.

I have one question though, I'm not quite certain where/how to include the Edge Polyfill for the toBlob method you mention in the README file.

Would you kindly assist? Many thanks!

**Comment by GhazanfarKhan** [comment]
Yes I also has the same question. I add in index file but no preview is showing

**Comment by TPJ11** [comment]
Within the `polyfills.ts` file
