### ISSUE TITLE
BUG: Angular 8 - Resize To Width Causes Image Corruption

### ISSUE THREAD

**Issue by JMooreo** [Mawi137/ngx-image-cropper#200]

**Comment by JMooreo** [comment]
THE PROBLEM
Sometimes, when cropping an image, the resulting event.base64 image comes back corrupted or doesn't display at all. Other times, it works perfectly.

WHAT I'VE TRIED
In my own troubleshooting, I think I isolated the issue. Cropping the image using [resizeToHeight] or [resizeToWidth] causes corruption somehow. I think it might have something to do with file size. On bigger photos, if the crop area is too large, it seems to fail, but if the crop area is smaller it seems to work okay.

Testing with 6MB photos, removing the [resize] options led to MUCH slower, but more reliable cropping.

But the performance is too slow for me to subject my users to. Using width=128px is also far too small, but I can't get by without using some sort of resizing or compression. Please let me know if there is a better way to get around this issue. Thanks!

Here is a code sample where corruption is happening:
HTML

<image-cropper *ngIf="image" 
    [imageBase64]="image" 
    [maintainAspectRatio]="true" 
    [aspectRatio]="4 / 9"
    [autoCrop]="false" 
    [resizeToWidth]="256" 
    [style.display]="isImageLoaded ? null : 'none'" 
    (imageLoaded)="imageLoaded()"
    (imageCropped)="save($event)"  
    (cropperReady)="cropperReady()">
</image-cropper>
TS

import { ImageCropperComponent, ImageCroppedEvent } from "ngx-image-cropper";

export class CapturedImageModalPage implements OnInit {
  @ViewChild(ImageCropperComponent, null) imageCropper: ImageCropperComponent;

  image = null;
  isImageLoaded = false;
  isCropperReady = false;

  constructor(
    private navParams: NavParams,
    private modalCtrl: ModalController,
  ) {}

  ngOnInit() {
    this.image = this.navParams.get("base64Image");
  }

  imageLoaded() {
    this.isImageLoaded = true;
  }

  cropperReady() {
    this.isCropperReady = true;
  }

  crop() {
    this.imageCropper.crop();
  }

  save(event: ImageCroppedEvent) {
    this.modalCtrl.dismiss({ croppedImage: event.base64 });

**Comment by Mawi137** [comment]
Hi there!
Not sure if you need a file or base64 as output, but you can set `outputType` to `base64`. That will speed up the cropping significantly. It's set to `both` by default, but I can't change it because that might break the cropper for some users, unless I change the major version.

There might indeed be some rounding errors when resizing a large image, thanks for the hint ;)

**Comment by JMooreo** [comment]
Changing the output type to jpeg & base64 is performing much better. Thanks!

For further app performance improvements, I'm using the Sharp library to resize the images after they are cropped.

**Comment by Mawi137** [comment]
Indeed a good idea to use another library that is specialised in resizing :D
