### ISSUE TITLE
BUG: recent update causes a bug when "cropper" input object is set

### ISSUE THREAD

**Issue by kkrasnobayev** [Mawi137/ngx-image-cropper#208]
Hello, found  bug after recent update. 

HOW TO REPRODUCE: just pass [cropper] object to component:

<image-cropper #imageCropper *ngIf="isImageLoaded === true"
                 [imageBase64]="imageBase64"
                 format="jpeg"
                 (imageCropped)="imageCropped($event)"
                 [maintainAspectRatio]='false'
                 [outputType]="'base64'"
                 [cropper]="cropper"
  ></image-cropper>

and you will get "Cannot read property 'nativeElement' of undefined" bug.

MY THOUGHTS: This is more likely due to {static: false} option, added to sourceImage. ngOnChanges runs before sourceImage is actually initialized and if you have [cropper] property set, then "setMaxSize" is run before sourceImage is available.

This does not "break" the plugin though.

**Comment by Mawi137** [comment]
Hi there!
This should be fixed in `1.5.1`. Can you confirm?

**Comment by kkrasnobayev** [comment]
Yep, it's fixed. Thanks.
