### ISSUE TITLE
Angular Universal Error

### ISSUE THREAD

**Issue by caglarturkurka** [Mawi137/ngx-image-cropper#209]
Hi, I used ngx-image-cropper for my project. Before it is works with my Angular Universal Project but today it gives an error like at Module../node_modules/ngx-image-cropper/ngx-image-cropper.ngfactory.js please helpe about this problem. Because it is important for me

**Comment by Mawi137** [comment]
Which version of Angular are you using? 
If there are more details you can share, they are more than welcome because there not much to go on now :)
Also, you don't have to upgrade, you can keep using the previous version if the issue remains.

**Comment by caglarturkurka** [comment]
I use Angular 7 


package.json
    "ngx-image-cropper": "^1.3.11",
    "@angular/animations": "^7.2.14",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/http": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/platform-server": "~7.2.0",
    "@angular/router": "~7.2.0",

**Comment by musacavus** [comment]
Hello there

I have the same angular version I have the same problem

**Comment by caglarturkurka** [comment]
Now, I try to use old version like 1.3.11 or 1.3.8 but also it does not work. Please tell me which version I can use

**Comment by Mawi137** [comment]
1.4.1 was the previous version

**Comment by caglarturkurka** [comment]
Okey I tried to use it but also it gives same error. Please tell me how can solve this problem

**Comment by Mawi137** [comment]
I just released version `2.0.0` which now follows the latest Angular guidelines to create a library. There are some breaking changes though: https://github.com/Mawi137/ngx-image-cropper/releases

Hopefully that helps.
