### ISSUE TITLE
Cropped image quality is not good. 

### ISSUE THREAD

**Issue by salih0313** [Mawi137/ngx-image-cropper#21]
I have tried with png and jpeg format. Both image quality are not good. Anyway is there to improve cropped image quality?

**Comment by Mawi137** [comment]
Hi, if you don't add a `resizeToWidth`, it will keep the original quality.
Haven't found (or looked for) a solution to get good quality when resizing yet.

**Comment by shantilal-narola** [comment]
I'm facing this issue as well. When i upload a small image, its clear. But the large image gets blurred. I would appreciate any help on this. Thanks!

**Comment by Coffee-Tea** [comment]
Maybe it can be useful
https://stackoverflow.com/questions/18547042/resizing-a-canvas-image-without-blurring-it

**Comment by troydcthompson** [comment]
Same here. This tool is great, but the resized image is clearly less quality than the one input.

**Comment by kaziupir** [comment]
Just use bigger image or call CSI: Crime Scene Investigation

**Comment by emko** [comment]
anyone figure this out? i am using  large image and when cropping the result looks really bad

**Comment by Mawi137** [comment]
Hi used the code from this repository: https://github.com/viliusle/Hermite-resize/blob/master/src/hermite.js
Image quality of resized image should be a lot better now! (Version 1.3.2)

**Comment by Saad-Rasheed** [comment]
If you want to improve the quality of picture so remove **[resizeToWidth]="128"** in your Html file. 

<input type="file" (change)="fileChangeEvent($event)" />
<image-cropper
    [imageChangedEvent]="imageChangedEvent"
    [maintainAspectRatio]="true"
    [aspectRatio]="4 / 3"
    format="png"
    (imageCropped)="imageCropped($event)"
    (imageLoaded)="imageLoaded()"
    (cropperReady)="cropperReady()"
    (loadImageFailed)="loadImageFailed()"
></image-cropper>

<img [src]="croppedImage" />
Regards,
**Saad Rasheed**.

**Comment by Mawi137** [comment]
> Hi, if you don't add a `resizeToWidth`, it will keep the original quality.
> Haven't found (or looked for) a solution to get good quality when resizing yet.

As mentioned here ;)
