### ISSUE TITLE
Zoom functionality

### ISSUE THREAD

**Issue by NilsMinor** [Mawi137/ngx-image-cropper#211]
Hi,
first of all thanks for creating this cropper tool for angular :)

I would like to ask for a feature or help to solve my problem. We have images like this:

![grafik](https://user-images.githubusercontent.com/8598107/65961175-4f48c400-e456-11e9-8072-e1d766eeba19.png)
The ratio of the imag is not 1/1, when using your cropper We would like to create a 1/1 aspect ratio.  For this pupose we would need a zoom function to zoom back so that the image would fit into the 1/1 ratio. here is an image of our problem :

![grafik](https://user-images.githubusercontent.com/8598107/65961376-b8303c00-e456-11e9-83aa-d6fb47c9b880.png)

Thanks for your help,
- Nils

**Comment by Mawi137** [comment]
Hi Nils, there already an option to achieve that! It's called `containWithinAspectRatio`. Setting that to `true` should solve your issue. Not the most descriptive name for the option, so if you know a better one ;)

**Comment by NilsMinor** [comment]
Hi,
this perfectly solved my problem :D
I think the name is ok, it was my fault for not reading the docs that well ^^

Thanks,
- Nils
