### ISSUE TITLE
Cropped area is reset after rotation

### ISSUE THREAD

**Issue by bedizm** [Mawi137/ngx-image-cropper#215]
Thanks for the component, it is great! 
I have been trying to make rotation and cropping work together. The rotation seems like resetting all the crop information. Wondered if there is any way to crop and then rotate the cropped image. I even tried to manage the crop/rotate states outside the component. Unfortunately, seems like rotate always resets. Wondered, if there is a way?
Thanks a lot for any comments in advance!

**Comment by Mawi137** [comment]
Yes this is intentional because it's possible that the cropping position falls outside of the image when rotating (e.g. when using 4:3 images). If you want to overwrite the cropper position, you should wait for the `cropperReady` event to have fired after rotating.

**Comment by bedizm** [comment]
Thanks a lot for the message. If I am not mistaken when you are referring cropperReady event solution, the scenario you are thinking is to apply crop and rotation at once. Sorry, I think I wasn't clear. 
Here is what I am trying to do:
I have a rotation button as in the sample demo. 
1. User opens the image and crops it
2. After cropped area is displayed, user can click on Rotate button.
3. Image is rotated, but the final cropped box is not matching the original cropped position on the image. (I am attaching pictures for each step, that I have been trying)
Thanks again, your help is very much appreciated
![1 after_loading_the_image](https://user-images.githubusercontent.com/35242960/66956358-44835700-f032-11e9-99b3-f4d974a8f86f.jpg)
![2 after_cropping](https://user-images.githubusercontent.com/35242960/66956375-4c42fb80-f032-11e9-8e9c-f61fdb2841f5.jpg)
![3 after_rotating](https://user-images.githubusercontent.com/35242960/66956390-506f1900-f032-11e9-9f45-4c752b321e32.jpg)
![4 after_rotating_EXPECTED](https://user-images.githubusercontent.com/35242960/66956396-536a0980-f032-11e9-8f62-813b544c9de2.jpg)

**Comment by Mawi137** [comment]
I see what you mean, you can switch the x and y coordinates I think.
However, that only works if you have `maintainAspectRatio` set to false.
You can get the current cropper position by passing your own instance of a CropperPosition to the `cropper` input. That way you'll have access to the position.
When rotating, you'll have to make a copy of that object, switch the x and y coordinates and assign that object again as the cropper position after `cropperReady` was fired.

**Comment by bedizm** [comment]
Sorry I couldn't reply as I didn't have a chance to try what you suggested, though it made sense. I was going to update with my test results, didn't have a chance yet. Thanks again for all the help!

**Comment by i-am-the-slime** [comment]
Why shouldn't this be the default? When do you **not** want that?
