### ISSUE TITLE
How to make fixed Height and Width Of Cropper on Initial Load 

### ISSUE THREAD

**Issue by hasnentai** [Mawi137/ngx-image-cropper#216]
Hi @Mawi137 and Hi to all the reader 

First of all thanks for the image cropper which works totally fine,but need some enhancement as well
Please take a look on my situation and please give me a solution how can I do that by modifying the existing code.

> First image will show the current behavior of a cropper and second image will show you the behavior which i need on page load .

**====================First Image========================**

![image](https://user-images.githubusercontent.com/26821037/66476563-8a30a480-eab3-11e9-8936-3361230bb842.png)

The above image is with following code in HTML
```

<image-cropper [imageChangedEvent]="imageChangedEvent" [maintainAspectRatio]="false" [roundCropper]="false"
            outputType="file" (imageCropped)="imageCropped($event)" (imageLoaded)="imageLoaded()"
            (loadImageFailed)="loadImageFailed()" [style.display]="showCropper ? null : 'none'" [alignImage]="'center'" >
          </image-cropper>
```

So when I use `[maintainAspectRatio]="false"` the cropper will take the full height and width of the image but I don't want that to be happen. I know its possible but its really hard for me to understand the whole code and then modify the feature.I tried couple of time but it din worked for me.

What I need is on the page load the cropper should look like the below image when i use `[maintainAspectRatio]="false"` .So that user can easily understand the cropping layer. 

**=======================Second Image=============================**
![image](https://user-images.githubusercontent.com/26821037/66477123-ea741600-eab4-11e9-884a-5c82ae9e86d3.png)

Please let me know how can I do that.

**Comment by hasnentai** [comment]
That was the stupid question . I found a way in documentation 
thanks

**Comment by SMK-GIT** [comment]
What is the **solution** please ?
