### ISSUE TITLE
How to set aspect ratio depending on input image portrait or landscape?

### ISSUE THREAD

**Issue by Herbert-Hotz** [Mawi137/ngx-image-cropper#217]
Hi,

Please give me a hint on how to detect input image is portrait/landscape and set cropper's aspectRatio automatically!

Examples:
landscape: 
`aspectRatio="1.414"`
protrait: 
`aspectRatio="0.707"`

Thanks in advance!

BTW: I'm using Angular 8

Best regards, 
Herbert

**Comment by Mawi137** [comment]
You can do something like this:
```
const image = new Image();
image.onload = () => {
    const width = this.originalImage.naturalWidth;
    const height = this.originalImage.naturalHeight;
    this.aspectRatio = width > height ? 1.414 : 0.707;
};
image.src = imageBase64;
```
