### ISSUE TITLE
Is it possible to show loading symbol till the image is loaded into the cropper.

### ISSUE THREAD

**Issue by Sruthi-Dintakurty** [Mawi137/ngx-image-cropper#218]

**Comment by Mawi137** [comment]
Hi there
You can easily implement this yourself by showing a loader once an image is chosen and hiding it when the `cropperReady` event is fired.
Not everyone wants to use the same loader, so I won't be adding it to this component.

**Comment by Sruthi-Dintakurty** [comment]
Hi, Thanks for the reply ! I actually implemented my own loader for it, but I guess this is the case with only when new image is clicked using mobile devices' camera, not the already existing images.

Is the cropper slow on mobile devices ? The rotation of such images also has some delay..

**Comment by Mawi137** [comment]
`cropperReady` should be triggered for every new image you give it?

Did you set the `outputType` to `base64`? That should be quite fast.
