### ISSUE TITLE
Post base64 data to server

### ISSUE THREAD

**Issue by vinayistar** [Mawi137/ngx-image-cropper#22]
Hello, I want to know hot post the cropped image to server?
Im having a Upload Image button and want to post that cropped image to server. Can you post some sample code for post the image data in base64.
Thanks.

**Comment by Mawi137** [comment]
The Base64 string returned by the image cropper can be handled as you would with any other string. So if the image is part of a form, you can also add a `FormControl` and assign the Base64 string to its value.

**Comment by vinayistar** [comment]
Can you post some sample code that post the cropped data.

**Comment by shubham-negi** [comment]
I'm having the same requirement. and @Mawi137 I tried sending the whole string to server. But the image file had nothing to preview. How to transform this base64 to image file? There aren't javascript built in functionality for this specific.

**Comment by sbirendorf** [comment]
Just send it as a string to the server, and decode it on the server side
http://php.net/manual/en/function.base64-decode.php

**Comment by shubham-negi** [comment]
@sbirendorf I know buddy that can be done on the server side.
I'm not talking about storing the image into the file system, that browser cannot do. I'm asking if there is any method through which I can store the **base64**  string on some object that can be saved easily or use further.

**Comment by Mawi137** [comment]
https://stackoverflow.com/questions/4998908/convert-data-uri-to-file-then-append-to-formdata

**Comment by vinayistar** [comment]
Cannot find name 'unescape'. Please Post some working code so that we can work on it

**Comment by Mawi137** [comment]
After your imports you can add this to remove that error/warning:
`declare var unescape;`

**Comment by vinayistar** [comment]
Using this resolved my problem.
```
function dataURLtoBlob(dataurl) {
    var arr = dataurl.split(','), mime = arr[0].match(/:(.*?);/)[1],
        bstr = atob(arr[1]), n = bstr.length, u8arr = new Uint8Array(n);
    while(n--){
        u8arr[n] = bstr.charCodeAt(n);
    }
    return new Blob([u8arr], {type:mime});
}
```

And use this function like this:
```
var dataurl = canvas.toDataURL('image/jpeg',0.8);
var blob = dataURLtoBlob(dataurl);
var fd = new FormData();
fd.append("myFile", blob, "thumb.jpg");
```
