### ISSUE TITLE
Can not set coordinates relative to image size

### ISSUE THREAD

**Issue by axel1200** [Mawi137/ngx-image-cropper#220]
I wanna preset coordinates for the cropper but i can only set coordinates relative to the cropper size.

**Comment by Mawi137** [comment]
I can have the cropperReady output emit the displayed image size. With that you can calculate the actual cropper position you need.

**Comment by axel1200** [comment]
Yeah would be an option. Well I started using private variables to calculate it. I could check wich ones I used

**Comment by Mawi137** [comment]
Hi, the image cropper now outputs the displayed image width and height in the `cropperReady` output. Version `2.1.2`.
