### ISSUE TITLE
Issue on cropper initialization with base64 image from server

### ISSUE THREAD

**Issue by adrienpitz** [Mawi137/ngx-image-cropper#221]
I have an issue with the cropper. 

This is my HTML:
```
<div *ngIf="this.showCropperTool === true">
          <image-cropper
            (imageCropped)="imageCropped($event)"
            (imageLoaded)="imageLoaded()"
            (cropperReady)="cropperReady()"
            (loadImageFailed)="loadImageFailed()"
            [alignImage]="'center'"
            [imageBase64]="this.largePicture"
            [imageChangedEvent]="imageChangedEvent"
            [maintainAspectRatio]="false"
            format="png"
            outputType="base64">

          </image-cropper>
</div>
```

I retrieve the image from server as a Blob file and then set it in base 64 in my form with this procedure:
```
const readerLarge: FileReader = new FileReader();
    readerLarge.onloadend = (e) => {
      this.largePicture = readerLarge.result;
      this.showCropperTool = true;
    };

readerLarge.readAsDataURL(this.route.snapshot.data['pictures'][1]);
```
The image is well retrieved from server and is even displayed in the "source-image" img item of the cropper
![image](https://user-images.githubusercontent.com/28534041/67755604-bb5c1f00-fa38-11e9-8fe2-666575af63c9.png)

The image at server side has the 'jpg' format.

However, if I open the modal where the cropper is supposed to appear, I see nothing:
![image](https://user-images.githubusercontent.com/28534041/67755791-08d88c00-fa39-11e9-831b-1dee94321801.png)

Note that the modal is correctly sized with the `largePicture` size.

Note also that the events `imageLoaded` and `loadImageFailed` are thrown one after the other. But the `cropperReady` event is never triggered (certainly because of the failure).
![image](https://user-images.githubusercontent.com/28534041/67756019-87cdc480-fa39-11e9-8411-015032458b67.png)

After further investigation, the `loadImageFailed` is triggered because the value of  `this.sourceImage.nativeElement.offsetWidth` is always 0 when arriving in the function `checkImageMaxSizeRecursively` in the cropper's code. 

Am I doing something wrong with the options I gave to the cropper? Or with the initialization of the image?

Note that it isn't an image size issue, the images I sent to the cropper are pretty convenient (max 700x700)

Have a nice day

**Comment by adrienpitz** [comment]
Note that it isn't an image size issue, the images I sent to the cropper are pretty convenient (max 700x700)

**Comment by Mawi137** [comment]
Hi there

When do you show the image cropper dialog, it should be after `imageLoaded`. The image will then  be shown and the image cropper can calculate its size and fire `cropperReady`.
