### ISSUE TITLE
If i have croped some area on image and have option to reposition the cropper. the resetCropperposition method needed.

### ISSUE THREAD

**Issue by manikandanm143** [Mawi137/ngx-image-cropper#222]

**Comment by Mawi137** [comment]
So you want `resetCropperPosition` to be public?

**Comment by manikandanm143** [comment]
Yes correct 😊.

**Comment by Mawi137** [comment]
A little late, sorry, but the method is now public. Version `3.0.1`. There are some breaking changes though: https://github.com/Mawi137/ngx-image-cropper/releases/tag/3.0.0
