### ISSUE TITLE
Angular Universal Error: ReferenceError: File is not defined.

### ISSUE THREAD

**Issue by santhoshraju621** [Mawi137/ngx-image-cropper#223]
Hi 

 i am getting this issue while from this plugin. while following this procedure.

-> I took universal build npm run build:ssr
-> Then i copied the dist folder and package.json and placed in another folder
-> Then i used npm i to install
-> Then i run npm run serve:ssr Then the below error is appearing in my system. so that i am unable deploy application.

D:\serverbuildrun\test2\node_modules\ngx-image-cropper\bundles\ngx-image-cropper
.umd.js:968
            __metadata("design:type", File),
                                      ^

ReferenceError: File is not defined
    at D:\serverbuildrun\test2\node_modules\ngx-image-cropper\bundles\ngx-image-
cropper.umd.js:968:39
    at D:\serverbuildrun\test2\node_modules\ngx-image-cropper\bundles\ngx-image-
cropper.umd.js:1106:6
    at Object.setPrototypeOf.__proto__ (D:\serverbuildrun\test2\node_modules\ngx
-image-cropper\bundles\ngx-image-cropper.umd.js:2:68)
    at Object.<anonymous> (D:\serverbuildrun\test2\node_modules\ngx-image-croppe
r\bundles\ngx-image-cropper.umd.js:5:2)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)

can any one help me to resolve the issue.

**Comment by Mawi137** [comment]
Hi, I have no experience with universal so I have no idea how to fix this.

**Comment by kryne** [comment]
> Hola, no tengo experiencia con universal, así que no tengo idea de cómo solucionar esto.

This means they never plan to fix it?

**Comment by Mawi137** [comment]
Hi @kryne. As far as I know, based on the platform, you should skip the initialisation of the image cropper when it’s being run on the server side (ngIf). The image cropper needs to know your window size to render so it will not work on the server side.

**Comment by santhoshraju621** [comment]
no it is working fine when ever we are running the project on the existing node modules folder. if we copy only dist folder and package.json there we are trying to install the node_modules. then only the issue is happening. please refer the first comment

**Comment by Mawi137** [comment]
Can you provide me a git repo so I can reproduce the error?

**Comment by santhoshraju621** [comment]
sure i will provide.

**Comment by santhoshraju621** [comment]
Hii you can try with this repo. and add your plugin dependencies follow the process on first comment
https://github.com/angular/universal-starter

**Comment by friou** [comment]
Hello,

I'm facing the exact same error when I'm trying to deploy my project on my server (node server).

`/app/dist/server.js:249859
        Object(tslib__WEBPACK_IMPORTED_MODULE_0__["__metadata"])("design:type", File),
                                                                                ^

ReferenceError: File is not defined
    at /app/dist/server.js:249859:81
    at Module.<anonymous> (/app/dist/server.js:249997:2)
    at __webpack_require__ (/app/dist/server.js:20:30)
    at Object.iqKW (/app/dist/server.js:152385:18)
    at __webpack_require__ (/app/dist/server.js:139381:30)
    at Object.SVWe (/app/dist/server.js:148349:10)
    at __webpack_require__ (/app/dist/server.js:139381:30)
    at Object.h8dT (/app/dist/server.js:151995:10)
    at __webpack_require__ (/app/dist/server.js:139381:30)
    at Object.V7fC (/app/dist/server.js:149064:11)`

Otherwise, there is no problem. On my own computer I'm able to run the node server.

**Comment by friou** [comment]
Hi,

I finally found a solution for my problem. The differences were between my package.json (8.2.14) and the current download version of angular's dependencies (8.2.13). To be sure about the version download do not forget to rm -rf node_modules/ and rm -rf package-lock.json.

I found the solution by comparing the two versions of server.js of the angular-universal builds and searching for the Angular version used to build the server dist.

**Comment by maddy2894** [comment]
Hey @friou Can you provide more details? How did you find angular-universal build version?

**Comment by kryne** [comment]
@friou please, if you have any more precise information about what the problem is or how to solve it, I thank you.

This is my package.json dependecies
`"dependencies": {
    "@angular/animations": "~8.2.4",
    "@angular/cdk": "~8.2.0",
    "@angular/common": "~8.2.4",
    "@angular/compiler": "~8.2.4",
    "@angular/core": "~8.2.4",
    "@angular/forms": "~8.2.4",
    "@angular/material": "^8.2.0",
    "@angular/material-moment-adapter": "^8.2.0",
    "@angular/platform-browser": "~8.2.4",
    "@angular/platform-browser-dynamic": "~8.2.4",
    "@angular/platform-server": "~8.2.4",
    "@angular/router": "~8.2.4",
    "@nguniversal/express-engine": "8.1.1",
    "@nguniversal/module-map-ngfactory-loader": "8.1.1",
    "angulartics2": "^8.1.0",
    "core-js": "^2.5.4",
    "express": "^4.15.2",
    "hammerjs": "^2.0.8",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.26",
    "ngx-cookie": "^4.0.2",
    "ngx-image-cropper": "^1.4.1",
    "rxjs": "~6.5.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.10.2"
  },`

**Comment by friou** [comment]
@kryne the best advice I can give you, will be to compare your local (and working) server.js with the (bugged) one on your server. I manage to find my problem like this (I'm running with  angular@8.2.13).

**Comment by kryne** [comment]
@friou well, I understood that. But what made me solve it? thanks

**Comment by friou** [comment]
@kryne as I said: check the differences, be, sure to use the same version of Angular on both (take a look at your node_modules, mine were not at the right version, as mention in package.json/package-lock.json).

If everything is fine, that's not the problem.

But my SSR build is currently running and deployed with angular@8.2.13.

**Comment by kryne** [comment]
Following the advice of @friou and comparing between a project in which ngx-image-cropper works well and one in which it works poorly I could see that using version "1.4.1" of ngx-image-cropper I have no problems.

I advise to indicate in package.json:
> "ngx-image-cropper": "1.4.1"

Do not use ^, since this installs version 1.5.1 (or higher in the future) which did not work for me.

@friou many thanks !!

**Comment by maddy2894** [comment]
Hey @friou, Any guide for deploying SSR? currently I have deployed angular 8.2.8 app without SSR into aws and it runs fine. Anything to change before deploying SSR app? Should I run npm run serve:ssr at the end of build to start the server on deployment?

**Comment by friou** [comment]
Congrats @kryne !

@maddy2894 I manage to run it with the help of this example: https://github.com/NickToony/universal-starter-leaflet-example.
For each error related to one of my modules, I've take a look on stackoverflow/github to find the solution. It takes a lot of time but I'm sure you'll manage to run it.

I'll send you my angular-universal's version and process when I'll have access to my code !

**Comment by friou** [comment]
@maddy2894 here is my angular-universal's versions:
```
   "@nguniversal/express-engine": "^8.1.1",
    "@nguniversal/module-map-ngfactory-loader": "8.1.1",
```

To deploy my app with SSR version I used the following command: `npm run build:ssr`.
And this is my commands in my package.json:
```json
    "compile:server": "webpack --config webpack.server.config.js --progress --colors",
    "serve:ssr": "node dist/server",
    "build:ssr": "npm run build:client-and-server-bundles && npm run compile:server",
    "build:client-and-server-bundles": "npm run build-prod && ng run trackevent:server:production",
```
You do not need to run server:ssr because you need to deploy this SSR version on a node server.

Hope it'll help you.

**Comment by maddy2894** [comment]
Thank you @friou, I guess your script to start server will be
“start”: “node server.js”

**Comment by friou** [comment]
@maddy2894 I'm not using any start command because I'm running this on a node docker-service, but yes, I think that is the way to do.

**Comment by maddy2894** [comment]
Did your process.env.NODE_ENV set to none after deployment? if so how did you tackle it?

**Comment by friou** [comment]
@maddy2894 I do not set anything, just building then running the server.js on the node server.

**Comment by maddy2894** [comment]
Okay cool, Appreciate your help
