### ISSUE TITLE
Missing bounds check when setting new cropper?

### ISSUE THREAD

**Issue by rtpHarry** [Mawi137/ngx-image-cropper#224]
I have a row of buttons for up down left right to move the cropper by 10px each time.

I'm trying to set the new cropper by adding / subtracting 10px at a time:

```
  move(x, y) {
    let updatedCropper: CropperPosition = {
      x1: this.angularCropper.cropper.x1 + x,
      y1: this.angularCropper.cropper.y1 + y,
      x2: this.angularCropper.cropper.x2 + x,
      y2: this.angularCropper.cropper.y2 + y
    };

    this.angularCropper.cropper = updatedCropper;
    this.angularCropper.crop();
  }
```

If I drag the mouse about then it automatically protects me from going out of bounds, but when I try to set it this way it does not protect me.

The cropper slowly moves off the image, and then the crop breaks because it tries to crop the square but crops out a rectangle instead. 

Eg this has square aspect ratio but moving the cropper of to the side gives me this rectangle:

![image](https://user-images.githubusercontent.com/1038062/68396677-d41bb180-0169-11ea-8d66-44ae3132117c.png)

Adding the resizeToWidth="256" keeps it square but then stretches it instead:

![image](https://user-images.githubusercontent.com/1038062/68396813-0e854e80-016a-11ea-9cc7-002fd3aba94f.png)

Now, I appreciate I am asking it to go off the image but as the mouse clamps it and also the other features all start to break, I'm left wondering:

Am I doing this the wrong way or is it a limitation / bug in the component?

**Comment by Mawi137** [comment]
It just assumes the coordinates are not out of bounds when calculating the resulting image. It stretches because that's how the HTML canvas works, I guess. Adding a bounds check when overwriting the cropper position would indeed solve that.
