### ISSUE TITLE
Profile picture mode?

### ISSUE THREAD

**Issue by rtpHarry** [Mawi137/ngx-image-cropper#225]
I'm trying to figure out if its possible to get it to work as a profile picture selection. 

I would image it like this:

  - The profile picture is loaded into the component as a draggable background image.

  - A fixed, pre-defined cropper is displayed in the middle of the screen.

  - There are buttons to zoom in and out, or you can pinch/grab. This affects the underlying image.

Basically you line up the photo to the cropper to show what you want in your profile picture.

At the moment when you load an image into the component it can vary wildly on the page.

Flipping the mode around like this lets you have a single portal which you move the image around underneath to fit the required crop.

**Comment by Mawi137** [comment]
Indeed, like the one on Facebook. Quite some changes would have to be made in to code to allow it to do that though.
