### ISSUE TITLE
in Chrome the size of image-cropper changes for the same loaded image

### ISSUE THREAD

**Issue by henryyue2010** [Mawi137/ngx-image-cropper#227]
My image-cropper is
```
<image-cropper [imageChangedEvent]="imageChangedEvent" 
                      [imageFile]="imageFile" 
                      [maintainAspectRatio]="true"
                      [aspectRatio]="4 / 4" 
                      [resizeToWidth]="256" 
                     [cropperMinWidth]="128" 
                     [onlyScaleDown]="true" 
                     [roundCropper]="true"
                     format="png" 
                     outputType="base64" 
        (imageCropped)="imageCropped($event)" (imageLoaded)="imageLoaded()"
        (cropperReady)="cropperReady()" (loadImageFailed)="loadImageFailed()"
        [style.display]="showCropper ? null : 'none'" [alignImage]="'center'">
      </image-cropper>
```

I set the size of image-cropper as
```
image-cropper {
    max-height: 60vh;
    max-width: 90vw;
  }
```
I upload an image. The size of image-cropper is ok. Then I try a smaller image. The image-cropper becomes smaller which is fine. Now I go back to the first image. I upload it, but the size of image-cropper doesn't become bigger. Why the size of image-cropper is different for the same image? Did I miss anything in image-cropper configuration?
It seems the problem happens only in Chrome, no such problem in IE.

**Comment by Mawi137** [comment]
Hi, the image cropper takes the space that is given to it. Maybe wrapping the image-cropper in a div and setting that css there solves the problem or maybe set a min-width as well.
