### ISSUE TITLE
High Resolution Vertical Images take a lot of space

### ISSUE THREAD

**Issue by all2pie** [Mawi137/ngx-image-cropper#230]
I want to fix the height of the display image so rest of my template is not disturbed. I have tried applying css properties but they only cut off the image rather than scaling it down. Please help

**Comment by Mawi137** [comment]
Hi in the stackblitz you can find in the readme, I have the max height set to 33vh which works fine. Is your approach the same?

**Comment by all2pie** [comment]
![Screen Shot 2019-12-01 at 12 01 12 PM](https://user-images.githubusercontent.com/34629684/69910768-672acd00-1432-11ea-8e90-8e713fa79018.png)


Check the image the image crroper above has max-height set to 18vh but its not showing correctly

The croper below has no max-height set, its displaying correctly but its taking a lot of height

**Comment by Mawi137** [comment]
Still having issues? My guess it that you're overwriting or adding css of the image within.
