### ISSUE TITLE
Image cropper not working on IE 11 (tried polyfill as well provided by ngx-image-cropper)

### ISSUE THREAD

**Issue by deepaksabharwal2211** [Mawi137/ngx-image-cropper#231]
![image](https://user-images.githubusercontent.com/12709471/69125548-0c0ce800-0acc-11ea-9153-8bd6b6252715.png)

HI
We are facing very unique issue in which Cropper is not working in IE 11 browser environment,
some time out of stack space is coming ,some time no errors come but cropper also does not generated.
Screenshot attached of how its looking in IE11 this is the screen after selecting the image to upload.

**Comment by Mawi137** [comment]
Hi, since version `3.0.0`, the image cropper no longer outputs the image as a Blob, which might be the cause of the issue. https://github.com/Mawi137/ngx-image-cropper/releases/tag/3.0.0. It might also be related to the size of the image you are trying to load.
