### ISSUE TITLE
CSS isnt working

### ISSUE THREAD

**Issue by ZoXlike** [Mawi137/ngx-image-cropper#232]
Hi ive implemented the cropper but it seems like the complete CSS is missing. I dont see the overlay and cant select a area. 

Ive used the git guide to implement.

Im using Anuglar 7.2.5

**Comment by Mawi137** [comment]
Normally importing the module and adding the component html should be all. It will only show if you pass it a correct image though.

**Comment by ozer0306** [comment]
For the clarification I need multiple cropper on same **Image**. Thank you...
