### ISSUE TITLE
Keyboard accessibility

### ISSUE THREAD

**Issue by dj7266** [Mawi137/ngx-image-cropper#233]
Hello, this is Donghoon Jung from Capital One, and I would like to contribute to this repo so that it can have a keyboard accessibility. We are trying to use the angular version of image cropping tool, but the keyboard accessibility is a required functionality.

From this PR, user will be able to tab into the image and use "arrow keys" to move and "shift + arrow keys" to resize the cropping tool. This will fix the accessibility issue that users who only have keyboard will be able to use the tool.

Would it be okay if I make a PR?

**Comment by Mawi137** [comment]
Sure! PRs are always welcome ;)

**Comment by Mawi137** [comment]
Released in version 2.1.0
