### ISSUE TITLE
imageCropped() is triggered as soon as loaded

### ISSUE THREAD

**Issue by TLKG** [Mawi137/ngx-image-cropper#234]
As soon as a file is loaded, imageCropped() is triggered. I can play some workaround in the load event, meanwhile wondering if this behavior can be addressed natively by this great tool.
Thank you!

**Comment by Mawi137** [comment]
Hi, yes this is intentional. It will crop on load and each time the cropper size changes. However, you can set ‘autoCrop’ to false and you’ll have to call the ‘crop’ function yourself. More about it in the read me.
