### ISSUE TITLE
Grow up size 

### ISSUE THREAD

**Issue by progtarek** [Mawi137/ngx-image-cropper#235]
I just forked the demo attached in the documentation and remove the (resizeToWidth) input, I found out that the size of the cropped area grow up from to 26MB, although the image size in total is 11MB.

![Screenshot from 2019-11-27 13-18-09](https://user-images.githubusercontent.com/18407645/69719150-8ff05100-1118-11ea-85fd-4ce0f60b56af.png)

here is the forked [demo](https://stackblitz.com/edit/image-cropper-zzeywf)

**Comment by Mawi137** [comment]
This is normal because it uses base64 images which are uncompressed.

**Comment by AyushG25** [comment]
@Mawi137  is there any way to stop this or a workaround, as in my case the cropped image is 7 times bigger than the original images and it is significantly impacting my website performance.

**Comment by Mawi137** [comment]
You could use another lib to first resize the image to a smaller size. Using jpg as outputType might help as well
