### ISSUE TITLE
Disabled input parameter

### ISSUE THREAD

**Issue by itPiligrim** [Mawi137/ngx-image-cropper#236]
Please add disabled input, to prevent change cropper area.

**Comment by savan2323** [comment]
There is no disabled input parameter added yet but you can overwrite the CSS of resizing cursors to make them invisible using below CSS,

```
::ng-deep .cropper span  {
    display: none !important;
  } 
```
you can write CSS to component's CSS where the image cropper package component used, and it works as expected, it will prevent to change cropper area.

**Comment by Mawi137** [comment]
The `disabled` input has been added in version `2.0.4`.
