### ISSUE TITLE
Cannot get it working with Ivy

### ISSUE THREAD

**Issue by jmesa-sistel** [Mawi137/ngx-image-cropper#237]
Maybe it is my fault but I'm trying to get it working with angular9-rc4 and I get the error:
`ERROR in Tried to overwrite ./node_modules/ngx-image-cropper/lib/component/image-cropper.component.d.ts.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.`
Anyone else is testing with Ivy?

**Comment by kolkov** [comment]
What version of RC you are using?

**Comment by jmesa-sistel** [comment]
@kolkov It is in the first line of the issue: angular9-rc4

**Comment by Mawi137** [comment]
Hi there, once Angular 9 is released I'll also build this lib with Angular 9. Hopefully somewhere soon :)

**Comment by jmesa-sistel** [comment]
@Mawi137 I just was testing to be sure my project was fine. The error is weird because I see you use ng-packagr so in theory is Ivy compatible, that is the reason I was asking. I suspect the problem is on my side.

**Comment by kolkov** [comment]
I use this package with Ivy enabled in my project, this works fine with Angular 9.0.0-rc.5.
Thanks.

**Comment by jmesa-sistel** [comment]
@kolkov I know you just tell that Ivy is enabled, but if you use ng-update the updater disable Ivy in tsconfig.app.json by default, can you verify that Ivy is not disabled?
Have you try to compile node_modules for Ivy?
[ngcc-compilation](https://next.angular.io/guide/ivy#speeding-up-ngcc-compilation) The error happens in postinstall script also. (npm run postinstall)

**Comment by kolkov** [comment]
@jmesa-sistel Ivy enabled by default in next 9 version.
My project compiled with ngcc. And I see Ivy code in source files.

**Comment by jmesa-sistel** [comment]
@kolkov Thks for confirmation. 
I'll check my project again.
