### ISSUE TITLE
outputType not working?

### ISSUE THREAD

**Issue by vandinhabc** [Mawi137/ngx-image-cropper#238]

**Comment by vandinhabc** [comment]
i want outputType is file (bob). but not working?

**Comment by Mawi137** [comment]
Hi in the StackBlitz you can find in the readme it isn't working either, but locally at is. I read something about it not working in an iframe..
What you can do as well is take the base64 and transform it to a Blob yourself: https://stackoverflow.com/questions/16245767/creating-a-blob-from-a-base64-string-in-javascript
