### ISSUE TITLE
Listen to cropper changes

### ISSUE THREAD

**Issue by marco-primiceri** [Mawi137/ngx-image-cropper#239]
Is there a way to listen to changes in the cropper dimensions/position?
The use case would be to display to the user how big is the crop area in pixels.
Would this feature appeal to anyone else?

Unless there is something that I am missing, currently the only way to achieve that would be to listen to mouse events and poll the `cropper` method each time.

Thanks!

**Comment by Mawi137** [comment]
Each time you move the cropper, the imageCropped output returns an instance of `ImageCroppedEvent`. It contains the width and height of the cropped image, more in the readme. Is this what you need?

**Comment by marco-primiceri** [comment]
Thanks for the prompt reply!

> Each time you move the cropper, the imageCropped output returns an instance of ImageCroppedEvent. It contains the width and height of the cropped image, more in the readme. Is this what you need?

Well, sort of.
The `imageCropped` event fires off when the user has completed moving the cropper, I would need to display the cropper size in real time as the user wants to know how big is the cropper without having to release the mouse click. See example below.
![Dec-06-2019 10-16-40](https://user-images.githubusercontent.com/1748778/70315454-839f7e80-1811-11ea-91d8-f499dce14798.gif)

Here is a snippet of my code:

    this.cropperWidthScalingFactor = this.imageCropper.sourceImage.nativeElement.naturalWidth / this.imageCropper.sourceImage.nativeElement.width
    this.cropperHeightScalingFactor = this.imageCropper.sourceImage.nativeElement.naturalHeight / this.imageCropper.sourceImage.nativeElement.height

```
  @HostListener("mousemove", ["$event"])
  @HostListener("touchmove", ["$event"])
  updateCropDisplaySize(): void {
    const cropperPosition = this.imageCropper.cropper
    this.cropWidthLabelPixels = Math.round((cropperPosition.x2 - cropperPosition.x1) * this.cropperWidthScalingFactor)
    this.cropHeightLabelPixels = Math.round((cropperPosition.y2 - cropperPosition.y1) * this.cropperHeightScalingFactor)
  }
```

**Comment by Mawi137** [comment]
Ah that is indeed something else. At the moment these is no such event. This could be a nice addition to the image-cropper, to have an output that returns the cropper position with our without the actual position.
