### ISSUE TITLE
How do I store the base64 string that I got as parameter in imageCropped listener?

### ISSUE THREAD

**Issue by shubham-negi** [Mawi137/ngx-image-cropper#24]
Rearranging the cropping emit an event passing the base64 string of cropped section and displayed into view by just assigning the src value to the variable.

how to store the cropped section local or on server.?

**Comment by sbirendorf** [comment]
The base64 is a string, you will need to decode the string on the server. 
In php it will be  
$image = base64_decode($base64_string);

**Comment by shubham-negi** [comment]
@sbirendorf What if we need to do it on the client-side.?

**Comment by Mawi137** [comment]
I suppose you'll need to convert the Base64 string back to a file and send that to the server: https://stackoverflow.com/questions/4998908/convert-data-uri-to-file-then-append-to-formdata

**Comment by Mawi137** [comment]
This is probably the same as #22
