### ISSUE TITLE
Template error when using version 2.0.2

### ISSUE THREAD

**Issue by taiwoobe** [Mawi137/ngx-image-cropper#240]
Hello,

I am making use of Angular 8 with the ngx-image-cropper and anytime I run the app, I get this error: 
Template error: Can't bind to 'imageChangedEvent' since it isn't a known property of 'image-cropper'.
If I remove the imageChangeEvent from the HTML binding, it goes to the next one which is maintainAspectRatio and also gives the same error. I tried using the version 1.4.1 but it gives that error too once in a while. 

How can this be resolved please?

I have attached screenshots of my code snippet and the error in the console 
![capture4](https://user-images.githubusercontent.com/9431878/70524939-87e7d680-1b46-11ea-84aa-f5e46771310f.PNG)
for your view.

![capture 1](https://user-images.githubusercontent.com/9431878/70524795-3d665a00-1b46-11ea-8bf7-4e6e829f7d22.PNG)
![capture 3](https://user-images.githubusercontent.com/9431878/70524870-6686ea80-1b46-11ea-8f40-0b4e96f346bb.PNG)
![Capture2](https://user-images.githubusercontent.com/9431878/70524871-671f8100-1b46-11ea-80b6-a5a9d55f1148.PNG)

Thanks

**Comment by Mawi137** [comment]
Hi, are you still having problems? That error means that Angular doesn't know the component, but I can see you have the import there of the ImageCropperModule..
