### ISSUE TITLE
Reset the source image to previously cropped image.

### ISSUE THREAD

**Issue by NimishDavid** [Mawi137/ngx-image-cropper#241]
What I want to do is:

-  I want to show the cropper inside a modal on selecting a file.
- The modal has a crop button on clicking which the image will be cropped (no autocrop) and a cancel button which can be used to close the modal without cropping the image.
- After the image is cropped, the modal will be closed and there will be an edit button which can be used to recrop the image (On clicking crop, I essentially crop the image and hide the modal. So on clicking edit, I just show the hidden modal again.).
- If another file is selected from the file input, the modal will be shown with the new image. The user can either crop or cancel. If it is cancelled, I want to reset the source image of the cropper to the previous image. How can I do that?

I have tried the following, but doesn't work:

```
lastCropperPosition: CropperPosition;
lastCroppedImage: any;

crop() {
    this.imageCropper.crop();
    this.lastCropperPosition = this.getCurrentCropperPosition();
    this.lastCroppedImage = new ElementRef(
      this.imageCropper.sourceImage.nativeElement
    );
    this.logoModal.hide();
}

cancelCrop() {
    if (this.lastCroppedImage) {
      this.imageCropper.sourceImage = this.lastCroppedImage;
    }

    if (this.lastCropperPosition) {
      this.imageCropper.cropper = this.getLastCropperPosition();
    }

    this.logoModal.hide();
}

getCurrentCropperPosition() {
    return {
      x1: this.imageCropper.cropper.x1,
      x2: this.imageCropper.cropper.x2,
      y1: this.imageCropper.cropper.y1,
      y2: this.imageCropper.cropper.y2
    };
}

getLastCropperPosition() {
    return {
      x1: this.lastCropperPosition.x1,
      x2: this.lastCropperPosition.x2,
      y1: this.lastCropperPosition.y1,
      y2: this.lastCropperPosition.y2
    };
}
```

Is using the `sourceImage` property the right way to do what I want to do? I change the `this.lastCroppedImage` only inside crop() method. But it seems to be changing whenever a new image is selected in the file input. Why does that happen?

PS: I have already tried assigning the `sourceImage` directly without creating a new `ElementRef`. That doesn't work either.

Stackblitz: https://stackblitz.com/edit/image-cropper-r5pyqh

Steps to reproduce in Stackblitz:

1. Browse and crop an image.
2. Browse again and select new image.
3. Click cancel in the crop window.
4. Click recrop. Observe that the image in crop window is the second one. Instead I want the first one.

**Comment by NimishDavid** [comment]
I am blocked on this. Can you please look into this?

**Comment by Mawi137** [comment]
Hi you should only use `imageChangedEvent`, `imageBase64` or `imageFile`. So in your case you could store the previous `imageChangedEvent`. Then you can can replace the current one with the previous one after pressing cancel.

**Comment by NimishDavid** [comment]
I tried storing the previous `imageChangedEvent`. But, when a new image is loaded, the previous  `imageChangedEvent` is replaced with the new one. Please find the relevant code below:

`crop() {
    this.imageCropper.crop();
    this.lastCropperPosition = this.getCurrentCropperPosition();
    this.lastImageChangedEvent = this.imageChangedEvent;
  }`

`cancelCrop() {
    if (this.lastImageChangedEvent) {
      this.imageChangedEvent = this.lastImageChangedEvent;
    }

    if (this.lastCropperPosition) {
      // this.imageCropper.cropper = this.getLastCropperPosition();
    }
  }`

**Comment by Mawi137** [comment]
Shoudn't the lastImageChangedEvent be set after selecting a new image? Now you so after cropping the image.

**Comment by NimishDavid** [comment]
I won't be able to achieve what I intend to do if I do that. I want to load the previous image if the user cancels without cropping.

**Comment by Mawi137** [comment]
Ok I see what you're doing now. Then I suggest you use the `imageFile` input instead. You'll have to get the file from the event yourself: `imageChangedEvent.target.files[0]`. Simply store the `lastImageFile` and replace it with the current one on cancel.

It makes sense that the imageChangedEvent changes because it refers to the file input field and therefore also the file that is selected at that moment.
