### ISSUE TITLE
Exif Transformation cases implemented incorrectly resulting in mirrored images

### ISSUE THREAD

**Issue by Kademlia** [Mawi137/ngx-image-cropper#244]
Hey,
we encountered a problem with Iphone images being mirrored in ngx-image-cropper uploads. This problem would always occur with the original image but not if we manually fixed the exif data. 
In the end we were able to track down the cause to the function **getTransformationsFromExifRotation(exifRotationOrBase64Image: number | string)** from **ngx-image-cropper/src/lib/utils/exif.utils.ts**

We believe the switch-statement is not correctly implemented. In our scenario the rotation written by the Iphone was "Rotate 90 CW". This will execute **case 6** ultimately resulting in a mirrored image.

We fixed this by changing
`case 6: return {rotation: 1, flipH: true,  flipV: false};`
to
`case 6: return {rotation: 1, flipH: false, flipV: false};`

As far as we can tell case 6,7,8 are incorrect and expect these values to work (untested for 7,8)
```
case 6: return {rotation: 1, flipH: false, flipV: false};
case 7: return {rotation: 3, flipH: false, flipV: true};
case 8: return {rotation: 3, flipH: false, flipV: false};
```

Thanks,
Kademlia

**Comment by Mawi137** [comment]
According to this site: https://sirv.com/help/resources/rotate-photos-to-be-upright/
You are correct :) I’ll fix it ASAP

**Comment by Kademlia** [comment]
Thanks for the fast response. One small correction to the initial report, case 5 should be changed as well. The website somehow says something different in the text than the pictures? Under "EXIF orientation values" case 6 mentions mirrored but the image below has number 6 not mirrored.

Page 18 of the offical exif document http://www.exif.org/Exif2-2.PDF
The camera-models here were helpful: https://www.impulseadventure.com/photo/exif-orientation.html
```
export function getTransformationsFromExifRotation(exifRotationOrBase64Image: number | string): Transformations {
    if (typeof exifRotationOrBase64Image === 'string') {
        exifRotationOrBase64Image = getExifRotation(exifRotationOrBase64Image);
    }
    switch (exifRotationOrBase64Image) {
        case 1: return {rotation: 0, flipH: false, flipV: false};
        case 2: return {rotation: 0, flipH: true,  flipV: false};
        case 3: return {rotation: 2, flipH: false, flipV: false};
        case 4: return {rotation: 2, flipH: true,  flipV: false};
        case 5: return {rotation: 1, flipH: false, flipV: true};
        case 6: return {rotation: 1, flipH: false, flipV: false};
        case 7: return {rotation: 3, flipH: false, flipV: true};
        case 8: return {rotation: 3, flipH: false, flipV: false};
    }
    return {rotation: 0, flipH: false, flipV: false};
}
```

**Comment by Mawi137** [comment]
I just created a new release `2.0.3` which contains the fix. I tested all possibilities withan  example image for each exif rotation, so it should be correct now :)
