### ISSUE TITLE
Mobile Left and Right cropper not moving at second time.

### ISSUE THREAD

**Issue by AyazBelim** [Mawi137/ngx-image-cropper#246]
I found that when i try to move my cropper left to right first time its moving but when i set to its original position and again try to move its not moving . same problem occur with right to left. Please help me out with this. i noticed after a 6 month near to deliver a project.
Any setting required to do that ? bcz same working on desktop.

alignImage= center;

 <image-cropper [imageFileChanged]="imageChangedEvent" [maintainAspectRatio]="false" [aspectRatio]="4 / 3"
                [alignImage]="alignImage" format="webp" (imageCropped)="imageCropped($event)"
                [backgroundColor]="backgroundColor"
                (imageLoaded)="imageLoaded()" (loadImageFailed)="loadImageFailed()"></image-cropper>

**Comment by Mawi137** [comment]
Can you provide a git repo or stackblitz and the steps to reproduce the issue?

**Comment by AyazBelim** [comment]
I would like to to share you first gif file of issue from mobile device if it will not a make sense then I will provide git repo.

**Comment by AyazBelim** [comment]
Hey @Mawi137  Stackblitz Demo where you have given link in npm package 
i also tried to move left to right same problem found too. https://stackblitz.com/edit/image-cropper

**Comment by Mawi137** [comment]
I don't seem to have that issue. Anyway you can see the console? Maybe it throws an error that may help.

**Comment by AyazBelim** [comment]
@Mawi137 
**I don't seem to have that issue**. --- Yes , I can't say that can be issue but you think
What if I want to set cropping again ?  It should be ideally working again right?

**Anyway you can see the console?** --- No any error displaying in console.

**Comment by Mawi137** [comment]
It seems you changed the css styling, maybe it's related to that?

**Comment by AyazBelim** [comment]
Yes @Mawi137 i tried to apply cropping in my admin panel which doesn't have any extra css styling and it's working fine.
Probably it can be due to css styling.
I will change my css  and let's see if it work for me.

**Comment by AyazBelim** [comment]
Hey, @Mawi137  sorry for reopening it.
 I tried with removing CSS style but I couldn't solve this.
AS far as I found  **imageCropped** Output event returning me below result when I move cropper from left to right or vice versa.
it may be helpful to you understand the issue
base64:"data:,"
cropperPosition: Object
x1: null
x2: null
y1: 6.33331298828125
y2: null
height: null
imagePosition: Object
x1: null
x2: null
y1: 17
y2: null
__proto__: Object
transform: Object
flipH : false
flipV: false
rotation : 0
width: null

**Comment by Mawi137** [comment]
You must be getting a JavaScript error if this is the output. I'll need either that or something so I can reproduce the error. You said you get the same with the StackBlitz (https://stackblitz.com/edit/image-cropper). That can show a console on the bottom of the preview screen.

**Comment by AyazBelim** [comment]
Yes same issue I have found with stackblitz link https://stackblitz.com/edit/image-cropper
You just have to follow steps which I have commented previously to reproduce.

Thanks!

**Comment by Mawi137** [comment]
Like I already said, it works fine when I try it. In stackblitz you can open the console which might show an error for you.

**Comment by AyazBelim** [comment]
![Record_2020-01-15-14-58-01](https://user-images.githubusercontent.com/34475248/72424453-0b32c280-37ac-11ea-9e56-d688c05a6380.gif)

Hey @Mawi137  Look above GIF I have shown console.


Thanks !

**Comment by Mawi137** [comment]
I was able to reproduce this on my Android phone finally, but I really had to swipe very fast to get the issue. But, I think I found the problem and after fixing it, I was no longer getting the empty image. Version `2.1.1`.

**Comment by AyazBelim** [comment]
Thank you so much.
