### ISSUE TITLE
Getting error in cropper image

### ISSUE THREAD

**Issue by smartHasmukh** [Mawi137/ngx-image-cropper#247]
image-cropper.component.ts(780,23): error TS2741: Property 'offsetImagePosition' is missing in type '{ width: number; height: number; imagePosition: CropperPosition; cropperPosition: { x1: number; y1: number; x2: number; y2: number; }; transform: { rotation: number; flipH: boolean; flipV: boolean; }; }' but required in type 'ImageCroppedEvent'.

```
const output: ImageCroppedEvent = {
          width,
          height,
          imagePosition,
          cropperPosition: { ...this.cropper },
          transform: { ...this.transformations }
};
```

**Comment by Mawi137** [comment]
Are you using the latest version? Line 780 doesn't exists and the `offsetImagePosition` property is optional now.

**Comment by smartHasmukh** [comment]
@Mawi137 I am using latest version and I just fixed that issue.

Thanks
