### ISSUE TITLE
Image as url

### ISSUE THREAD

**Issue by raresgaia** [Mawi137/ngx-image-cropper#251]
Can an image be added using a URL as src attribute?

**Comment by Mawi137** [comment]
Hi, you can easily handle that outside of the image cropper. See the last comment here: #100

**Comment by raresgaia** [comment]
Thank you, @Mawi137 !

Another question will be, if I want to override the cropper position, you said in documentation that we should set the cropper value when the cropperReady event is fired. I've tried that but I recieve this error: TypeError: Cannot read property 'nativeElement' of undefined. It seems that it doesn't wait until the image is loaded to have the `nativeElement` property.

**Comment by raresgaia** [comment]
in my html:
`        <image-cropper
          [aspectRatio]="4 / 3"
          [imageBase64]="imageBase64"
          (cropperReady)="cropperReady($event)"
          [cropper]="cropper"
        ></image-cropper>`

and in my function: 
`      this.cropper = {
        x1: 0,
        y1: 0,
        x2: 200,
        y2: 300
      };`

**Comment by raresgaia** [comment]
I've checked the code and in the `crop` method, you should add 
if (`this.sourceImage && `this.sourceImage.nativeElement && this.transformedImage != null) {...}

This is how I've managed to fix that error.

**Comment by Mawi137** [comment]
Hi yes thanks,  just release version 3.0.0 and with the changes I made, I encountered the same issue :) More info: https://github.com/Mawi137/ngx-image-cropper/releases/tag/3.0.0
