### ISSUE TITLE
Add brightness and contrast adjustments

### ISSUE THREAD

**Issue by diegoarantes** [Mawi137/ngx-image-cropper#253]
It would look great if it had the brightness and contrast functions.

Example: https://scaleflex.github.io/filerobot-image-editor/

**Comment by dlportel** [comment]
Yes! It will be a great improve!!

**Comment by Mawi137** [comment]
I could add a new input `filter` that will apply these kind of effects like described here: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/filter

**Comment by dylanvdmerwe** [comment]
@Mawi137 Did you ever manage to look into adding filters?
