### ISSUE TITLE
How to use base64ToFile?

### ISSUE THREAD

**Issue by damsorian** [Mawi137/ngx-image-cropper#256]
I read the last version and I don't find the base64ToFile method ... how to use it? I need the file object instead of the base64. Thanks!

**Comment by dlportel** [comment]
@damsorian I used this method, You only need to pass a base64 file that export the module, and you get the FILE object. Regards.

static b64ToFile(b64Data: string, type: string = 'image/jpeg'): File {
    let data;
    // evaluating if come in format:  data:image/png;base64,iVBORw0KGgoAA
    const aux = b64Data.split(',');
    if (aux.length > 1) `{`
      data = aux[1]
    } else {
      data = b64Data;
    }
    const byteString = atob(data);
    const ab = new ArrayBuffer(byteString.length);
    const ia = new Uint8Array(ab);
    for (let i = 0; i < byteString.length; i += 1) {
      ia[i] = byteString.charCodeAt(i);
    }
    const blob = new Blob([ab], {type});
    if (!blob) {
      return null;
    }
    return new File([blob], 'file_name', {type});
  }

```

**Comment by ravindrap123** [comment]
I use this:

```
  base64ToBlob(base64: string) {
    const binary = atob(base64.split(',')[1])
    const content = []
    for (let i = 0; i < binary.length; i++) {
      content.push(binary.charCodeAt(i))
    }
    return new Blob([new Uint8Array(content)], { type: 'image/png' })
  }
```

**Comment by damsorian** [comment]
@Mawi137 when you say _"Instead this package provides a method called base64ToFile which can be called to create a new Blob based on the base64 image"_  what do you mean?

**Comment by Mawi137** [comment]
It means you should be able to use the method called `based64ToFile`, which takes a base64 string and returns you a Blob. 
```
import { base64ToBlob } from 'ngx-image-cropper';
```

**Comment by PiotrFr** [comment]
import { base64To***File*** } from 'ngx-image-cropper'

not base64ToBlob  :-)

**Comment by maddy2894** [comment]
> It means you should be able to use the method called `based64ToFile`, which takes a base64 string and returns you a Blob.
> 
> ```
> import { based64ToFile } from 'ngx-image-cropper';
> ```

For anyone copy-pasting the import, kindly change **_based64ToFile_** to **_base64ToFile_**. I spent 30 minutes finding this.
