### ISSUE TITLE
I keep seeing 'rotate' undefined if I send the same imageBase64 again.

### ISSUE THREAD

**Issue by ravindrap123** [Mawi137/ngx-image-cropper#257]
Hi,
My code
```
<image-cropper 
      [style.display]="showCropper ? null : 'none'"
       [imageBase64]="imageBase64ToCrop" 
       [maintainAspectRatio]="false"
       [canvasRotation]="canvasRotation" 
      format="png" 
      (imageCropped)="imageCropped($event)">
</image-cropper>
```
However, I am not seeing on the first time when I send _imageBase64_ in both browsers. But if I open the image cropper with same _imageBase64_ I see the errors.

I am not sure, it is related to **[canvasRotation]** or not. But if I remove that input, I see no errors. 

I see two two different console errors: 

**Windows Chrome** Version 79.0.3945.130 (Official Build) (32-bit)
![ngx-image-cropper](https://user-images.githubusercontent.com/16688456/73040860-4b72f000-3dff-11ea-805c-73eb9c0f88a1.jpg)

**Linux MInt 17.3 Firefox**  Version 66.0.3
![linux firefox](https://user-images.githubusercontent.com/16688456/73041155-6e51d400-3e00-11ea-8b00-8164c9dd5f84.jpg)

Thank you for your time on this.

**Comment by Mawi137** [comment]
Hi there, can you try again with version`3.0.3`?

**Comment by ravindrap123** [comment]
Sorry for the late response, that worked!
Thank you again.
