### ISSUE TITLE
cropper size cannot be increased

### ISSUE THREAD

**Issue by JulidaRocks** [Mawi137/ngx-image-cropper#258]
After having loaded a new image, the cropper size cannot be increased unit I run one of the transformation methods (e. g. rotate right). Then it increases to the image's size.

![N3MK4D8pL1](https://user-images.githubusercontent.com/39371377/73057744-912cc880-3e92-11ea-85a4-3b3de3e83050.gif)

The cropper's max width and height is set correctly to the image's initial width and height. However I cannot increase it.

Here's the implementation:

                <image-cropper
                    class="image"
                    #cropper
                    [imageChangedEvent]="imageChangedEvent"
                    [maintainAspectRatio]="true"
                    [aspectRatio]="1 / 1"
                    cropperMinWidth="100"
                    cropperMinHeight="100"
                    format="png"
                    onlyScaleDown="true"
                    (imageCropped)="imageCropped($event)"
                    (loadImageFailed)="loadImageFailed()"
                ></image-cropper>

**Comment by dlportel** [comment]
@JulidaRocks try with  onlyScaleDown="false", maybe is this. Regards

**Comment by Mawi137** [comment]
How do you rotate the image? I can't see that in the code you provided? Or are you still using version 2 of the image cropper?

**Comment by JulidaRocks** [comment]
Yes, I was using version 2. I know updated to version 3, deleted some obsolete css classes and it works :-)
