### ISSUE TITLE
RTL Support?

### ISSUE THREAD

**Issue by nileshbhagwat** [Mawi137/ngx-image-cropper#26]
![image](https://user-images.githubusercontent.com/22997240/37631191-8c4779c0-2c0e-11e8-9a79-cb3abdb6cc31.png)

Cropper resizer distorted in RTL

**Comment by nileshbhagwat** [comment]
@Mawi137 any update on this?

**Comment by Mawi137** [comment]
Now I use `:after` to draw the dots, but to fix this I'll have to do that another way. That should also make it easier to solve #15.

**Comment by Mawi137** [comment]
Could you try updating the image cropper to 0.2.1? It should solve your problem.

**Comment by nileshbhagwat** [comment]
@Mawi137 **0.2.2** looks good to me. Thanks
