### ISSUE TITLE
Usage in case of Multiple images

### ISSUE THREAD

**Issue by ShaileshNandkule** [Mawi137/ngx-image-cropper#260]
can we use this library as a carousel in case of multiple images ??
I want a carousel that provides area select functionality. 

Thanks

**Comment by Mawi137** [comment]
Hi yes you can use this component as many times as you want on a page.

**Comment by ShaileshNandkule** [comment]
Hi, thanks.
as you said I used multiple components, but I am facing issue to distinguish which image iamgeCropped event emitted, as imageCropped event does not contain any image-specific data like id or image name.
Is it possible to identify image on which imageCropped event emitted in case of multiple components??

Thanks

**Comment by Mawi137** [comment]
You can do all that outside the component like this for example in the HTML: `(imageCropped)="imageCropped($event, YOUR_ID)"`
