### ISSUE TITLE
Rotation of Image is not working 

### ISSUE THREAD

**Issue by satish666** [Mawi137/ngx-image-cropper#262]
I am using online example from  [https://stackblitz.com/edit/image-cropper]()  .I copied all files and made a component in my project. 
Cropping  is working but flipping and rotating are not working.
![image](https://user-images.githubusercontent.com/46818771/73458490-61525900-439b-11ea-8a93-ebf42fc74959.png)
cropping is not showing in console that's the only difference from Online example .
I want the rotating effect also.
Please Help

**Comment by Mawi137** [comment]
Why do you copy all the files instead of using it as a lib?

**Comment by satish666** [comment]
I need cropping behavior like ony x shift when using right left and only y shift when using top bottom.
Like WhatsApp has. I deleted  checkAspectRatio() function to get that

**Comment by satish666** [comment]
After Cropping base 64 size becomes 10 times.

**Comment by Mawi137** [comment]
You can set maintainAspectRatio to false to skip that function
