### ISSUE TITLE
imageCropped($event) is not getting called for Ionic 3 iOS App

### ISSUE THREAD

**Issue by Sagarkhenat** [Mawi137/ngx-image-cropper#263]
Hello, I have used the ngx-image-cropper for our event-based web app, the cropper was working fine until we updated our ionic cordova iOS platform to 5.1.1 and cordova-plugin-ionic-webview plugin to latest version as the function of imageCropped($event) is not getting called. The cropper works fine for android and web. But does not work on iOS devices. Here is my image cropper html and ts code:
<image-cropper
  [imageChangedEvent]="imageChangedEvent"
  [maintainAspectRatio]="true"
  [aspectRatio]="(aspectRatioValue ? aspectRatioValue : 3.02/1)"
  [cropperMinWidth]="(cropperMinWidthValue ? cropperMinWidthValue : 1366)"
  [resizeToWidth]="(resizeToWidthValue ? resizeToWidthValue : 1366)"
  format="png"
  (imageCropped)="imageCropped($event)" 
  (imageLoaded)="imageLoaded()"
  (cropperReady)="cropperReady()"
  (loadImageFailed)="loadImageFailed()"
></image-cropper>    

My .ts file 
export class ImageCropComponent{
  @ViewChild(ImageCropperComponent) imageCropper: ImageCropperComponent;
  imageChangedEvent: any = '';
  croppedImage: any;
  aspectRatioValue: any = 3.02/1;
  cropperMinWidthValue: any = 1366;
  resizeToWidthValue: any = 1366;
  croppedNewImage:any = '';
  constructor( public navCtrl: NavController, public navParams: NavParams, public viewCtrl: ViewController ) {
    console.log('ionViewDidLoad ImageCropComponent');
  }

imageCropped(event: ImageCroppedEvent) {
    console.log("imageCropped =============================>",event);
    this.croppedImage = event.base64;
  }

P.S: The cropper works when I am selecting Image from the library, but it does not load when I am selecting an image from phone camera, i.e. loading an image taken from back camera. Is there any workaround for this.
Any kind of help would be really helpful.

**Comment by Mawi137** [comment]
Which version of the cropper are you using?

The reason the cropper doesn’t work with the images of the back camera is probably because they are too big for the html canvas to handle.

**Comment by Sagarkhenat** [comment]
Hello @Mawi137, I am using version 1.3.9 of ngx-image-cropper, yes, the issue is happening when we are trying to load images from the camera, or even trying to load an image of large size, I am using format=" png" as an output. The back camera is opened only on iOS I think, is there a way we can disable opening the back camera?

**Comment by Mawi137** [comment]
Could you give version 3.0.3 a try? Changelog can be found here: https://github.com/Mawi137/ngx-image-cropper/releases

I don't think you can disable the backcamera. The OS decides that I guess.

**Comment by edn9** [comment]
I got a similar issue, it work perfect in web, but in IOS 13 I only get "isTrusted:true", I tried to fix it but the final result was to use base64 in the ngx module.
