### ISSUE TITLE
How to use it with a File parameter

### ISSUE THREAD

**Issue by dvcarrillo** [Mawi137/ngx-image-cropper#264]
Hi,

Due to restrictions in my application, I can't use an input element. I would like to know if it's possible to use the image cropper from a image file directly.

Thanks!

**Comment by Mawi137** [comment]
Hi there, yes you can also pass a file and base64, more info in the readme

**Comment by dvcarrillo** [comment]
Can I please ask you for an example ?

I'm not really familiar with Angular. I tried passing the image file (as File type) as a parameter in `fileChangeEvent(event: any): void` from another function, but it does not seem to work.

**Comment by Mawi137** [comment]
Simply use `imageFile` instead of `imageFileChanged` in the html

**Comment by dvcarrillo** [comment]
Thank you very much, it's working perfectly!
