### ISSUE TITLE
Version 3.0.3 broken, in angular 8/9

### ISSUE THREAD

**Issue by weihsth** [Mawi137/ngx-image-cropper#266]
First of all... it's extremely hard to update a module, which does not have any change log / history or info about breaking changes. Besides that, it's (it was) a nice module..

Since upgrade to version 3.0.3 nothing works anymore. No errors are thrown. It's just not doinf anything else than triggering "imageLoaded" Event and a fews seconds after that it's triggering the "loadImageFailed" Event without any payload or message.

**Comment by Mawi137** [comment]
The changelog can be found under releases: https://github.com/Mawi137/ngx-image-cropper/releases

**Comment by weihsth** [comment]
Ohh sorry, my fault. Thank you!!
