### ISSUE TITLE
Add a cancel button if image is uploaded

### ISSUE THREAD

**Issue by gitalvininfo** [Mawi137/ngx-image-cropper#267]
How do I add a cancel button if ever the image is already uploaded and reset the image to previous image. 

Thank you. Great library.

**Comment by Mawi137** [comment]
You should use the `imageFile` input and then store the current and previous one in a variable so you can switch it back.

**Comment by gitalvininfo** [comment]
Thanks. Do you have any stack blitz sample for this one? If none, it's OK thanks again

**Comment by Mawi137** [comment]
I don’t have an example for that no :)

**Comment by gitalvininfo** [comment]
Nevermind already solved thanks CLOSED
