### ISSUE TITLE
setting width and height to manual numbers

### ISSUE THREAD

**Issue by dolphinsd** [Mawi137/ngx-image-cropper#268]
For some reason this code does not work, as it jumps around to different height and width then set. In image, height was set to 400 in edit field, but it was rendered 526

`  <image-cropper
                                           [imageChangedEvent]="imageFileChanged"
                                           [maintainAspectRatio]="false"
                                           [containWithinAspectRatio]="containWithinAspectRatio"
                                           format="png"
                                           outputType="file"
                                           imageQuality="92"
                                           [canvasRotation]="canvasRotation"
                                           [style.display]="showCropper ? null : 'none'"
                                           [transform]="transform"
                                           [cropper]="cropper"
                                           #imageCropper
                                           (imageLoaded)="imageLoaded()"
                                           (cropperReady)="cropperReady($event)"
                                           (imageCropped)="imageCropped($event)"
                                           (loadImageFailed)="loadImageFailed()"
                                           ></image-cropper>`
`  updateHeight() {
        if (this.cropperIsReady) {
            this.cropper = {
                x1 : this.cropper.x1,
                y1:  this.cropper.y1,
                x2 : this.cropper.x2,
                y2 : this.cropper.y1 + this.imageHeight
            };
        }
    }
    updateWidth() {
        if (this.cropperIsReady) {
            this.cropper = {
                x1 : this.cropper.x1,
                y1:  this.cropper.y1,
                x2 : this.cropper.x1 + this.imageWidth,
                y2 : this.cropper.y2
            };
        }
    }

![7c8f38ee100c1480dfedbc38cbad7e59](https://user-images.githubusercontent.com/3460517/74496842-c7a5a400-4e90-11ea-8567-002b5aee0e47.png)

**Comment by Mawi137** [comment]
You shouldn’t use display: none on the image cropper, it needs the view to be visible to calculate its positions

**Comment by dolphinsd** [comment]
@Mawi137 , that did it!
