### ISSUE TITLE
imageCropped() function is not called at all on iOS devices

### ISSUE THREAD

**Issue by Sagarkhenat** [Mawi137/ngx-image-cropper#269]
Hi, after @Mawi137  suggestions to use the latest version of ngx-image-cropper, it works fine on android and browser.But the imageCropped() function is not called on iOS device.I am developing an hybrid app on ionic3 and use wkwebview in my project(cordova-plugin-ionic-webview).I wanted to know why the function is not called on iOS and the cropper loads empty.I am using the below code:

<image-cropper [imageChangedEvent]="imageChangedEvent"
               [maintainAspectRatio]="true"
               [aspectRatio]="(aspectRatioValue ? aspectRatioValue : 3.02/1)"
               [cropperMinWidth]="(cropperMinWidthValue ? cropperMinWidthValue : 1366)"
               [resizeToWidth]="(resizeToWidthValue ? resizeToWidthValue : 1366)"
               format="jpeg"
               (imageCropped)="imageCropped($event)"
               (imageLoaded)="imageLoaded($event))" 
               (cropperReady)="cropperReady()" 
               (loadImageFailed)="loadImageFailed()"></image-cropper>

 imageCropped(event: ImageCroppedEvent) {
    console.log("imageCropped event called================================>",event),
    this.croppedImage = event.base64;
  }
  imageLoaded() {
      // show cropper
   
  }

Any kind of suggestions would be helpful.Thanks.

**Comment by Mawi137** [comment]
Are you able to do some remote debugging and maybe see an error in the console?

**Comment by Sagarkhenat** [comment]
Hi @Mawi137, I did write the console.log  functions for (imageCropped)="imageCropped($event)" (cropperReady)="cropperReady()", it works well for browser website view, when I am using the same on iOS or Android devices, the imageCropped and the cropperReady functions are not getting called.
My .ts function is:
imageCropped(event: ImageCroppedEvent) {
    console.log("imageCropped =============================>",event);
    this.croppedImage = event.base64;
  }

**Comment by Mawi137** [comment]
Okay and so it’s not showing any errors in the console?

**Comment by Sagarkhenat** [comment]
@Mawi137 Yes it is not showing any errors on the console, and the imageCropped function is not called on mobile devices.

**Comment by Mawi137** [comment]
Can you provide a repo to reproduce this? I can start up an iOS emulator.

**Comment by Sagarkhenat** [comment]
@Mawi137 Sure, I'll create a repo and will inform you for the same, thanks.
