### ISSUE TITLE
Unable to publish angular 4 app, it works fine in local just not working with webpack publish

### ISSUE THREAD

**Issue by kolte** [Mawi137/ngx-image-cropper#27]
$$_gendir\node_modules\ngx-image-cropper\ngx-image-cropper.ngfactory.ts Unexpected token (13:40)
    You may need an appropriate loader to handle this file type.
    | import * as i2 from '@angular/common';
    | import * as i3 from '@angular/platform-browser';
    | export const ImageCropperModuleNgFactory:i0.NgModuleFactory<i1.ImageCropperModule> = i0.╔╡cmf(i1.ImageCropperModule,
    |     ([] as any[]),(_l:any) => {
    |       return i0.╔╡mod([i0.╔╡mpd(512,i0.ComponentFactoryResolver,i0.╔╡CodegenComponentFactoryResolver,
     @ ./$$_gendir/ClientApp/app/components/client/updateclient.component.ngfactory.ts 12:0-106
     @ ./$$_gendir/ClientApp/app/app.module.server.ngfactory.ts
     @ ./ClientApp/boot.server.ts

any ideas please?
Thank you
Girish

**Comment by Mawi137** [comment]
Hi,
Sorry I have no idea to be honest. I only use the angular CLI.
