### ISSUE TITLE
Cropped image from image cropper is bigger in size than the original image

### ISSUE THREAD

**Issue by AyushG25** [Mawi137/ngx-image-cropper#270]
Hi, I uploaded a 3.02MB image and cropped some portion of the image using image cropper, when I checked the cropped image size it was around 7 times bigger than the original image around 21MB.
Is there any property or resize code that needs to be added to image cropper ? 

I am using image cropper in a bootstrap modal popup, and below mentioned properties only 
[imageChangedEvent]="imageChangedEvent"
[aspectRatio]="(aspectRatioX)/(aspectRatioY)"                         
(imageLoaded)="imageLoaded()"
(imageCroppedFile)="imageCroppedFile($event)"
(loadImageFailed)="loadImageFailed()"

Is there any way to limit the cropped image size ?

**Comment by Mawi137** [comment]
You can try to use jpg as output type instead of the default which is png. If that doesn’t help, maybe there is another lib that can help you with reducing the size.
