### ISSUE TITLE
New Feature, ngx-image-cropper return file object.

### ISSUE THREAD

**Issue by pavang-bs** [Mawi137/ngx-image-cropper#273]
ngx-image-cropper is not returned file object in running version from image cropper and Internet Edge and Internet Explorer do not support to convert base64 to file object.
That's why I request to add new features to return the file object at image crop time.

**Comment by Mawi137** [comment]
Hi, the image cropper exposes a method called `base64ToFile` which does exactly that. Before, the image cropper returned the file in the imageCropped output, but that resulted in poor performance. Instead you can use that method to covert it whenever you see fit.

**Comment by pavang-bs** [comment]
I already try it, but it does not work for Internet explorer.

**Comment by Mawi137** [comment]
And does it show an error in the console?

**Comment by pavang-bs** [comment]
![erro](https://user-images.githubusercontent.com/59996240/75003761-f9b99600-548e-11ea-9cd0-368dd5527ce6.png)

**Comment by Manuel210398** [comment]
hi, excuse me where is that method base64ToFile or how can i use it?

**Comment by Mawi137** [comment]
Just tested it on IE 11 and Edge, both work fine: https://image-cropper.stackblitz.io
The error you have points to an error in your `dataURLToFile` function? You sure the `event.base64` is a valid base64?

**Comment by Mawi137** [comment]
@Manuel210398 `import { base64ToFile } from `ngx-image-cropper';

**Comment by shing1630** [comment]
I upgrade from 2 to 3 and find out that the event.file is not working.
But after the code change
It works

```
imageCropped(event: ImageCroppedEvent) {
    this.croppedImage = base64ToFile(event.base64);
  }
```

Thanks Martijn!

**Comment by Mawi137** [comment]
I just added a CHANGELOG.md file that points to the releases of the repo. All info on breaking changes can be found there. That way I hope it's easier to find that info :)

**Comment by axitpoojara** [comment]
@Mawi137 i want to save cropped image as a  File but i can't so how to do please guide
