### ISSUE TITLE
missing previous feature rotateLeft & rotateRight

### ISSUE THREAD

**Issue by loadmi** [Mawi137/ngx-image-cropper#276]
Hello,

First of all great package it really helped me with development. I have seen you updated the package a month ago and just about since then the rotate buttons in my project don't work anymore. I see there are new features for image rotation but i can't seem to get them to work. I can assign a number to the image cropper instance's property .transform.rotate but that doesn't seem to do anything. It isn't a function call but rather a assignment i can do there.

What i'm trying to do is when a user clicks on a button i want to either rotate my image 90 degrees to the left or to the right depending what button the user clicked. i'm using the (click) event of angular for this.

EDIT: I have found out i can use the transform.rotate feature by adding it as an input. i can then set this input to a variable that i can change at runtime. I'll still leave the question up in case there's a more clean approcach

**Comment by Mawi137** [comment]
Hi, you should use the `canvasRotation` input instead. A number from 0 to 3 which indicates the number of rotations by 90deg.
