### ISSUE TITLE
Cannot upload previous uploaded image.

### ISSUE THREAD

**Issue by gitalvininfo** [Mawi137/ngx-image-cropper#278]
Every time I upload an image(*Image A), then upload another image (Image B),  (Image A) is replaced which is the exact behavior. So currently the uploaded image is (Image B), then if I upload the previous image which is (Image A), Image A is not uploaded, I have to pick another image for example (Image C), then that's the time I can upload Image A.

Please let me know if I miss something. 

Thanks, Great Library.

**Comment by gitalvininfo** [comment]
I have a method uploadFile($event) and this event is trigger in (change) and imageChangedEvent handle this event like this one.

This is my image cropper component.
`<image-cropper style="width: 100%; height: 200px;" [imageChangedEvent]="imageChangedEvent" [maintainAspectRatio]="true" [aspectRatio]="1 / 1" format="jpg" [onlyScaleDown]="true" [resizeToWidth]="128" [roundCropper]="true" (imageCropped)="imageCropped($event)" (loadImageFailed)="loadImageFailed()"></image-cropper>`

`  uploadFile(event) {
    this.imageChangedEvent = event;
    console.log(event)
  }
`
Please let me know if I miss something. Thank you.

**Comment by Mawi137** [comment]
Maybe you can try to extract the image from the event and use the `imageFile` input instead?
