### ISSUE TITLE
first time i am getting image fail error on ngx-image-cropper

### ISSUE THREAD

**Issue by SachinSureshBS** [Mawi137/ngx-image-cropper#279]
first time onload i am getting image fail error on ngx-image-cropper and im using angular2. Kindly let me know how to resolve this error. NOTE:  I cannot change my angular version

error_handler.js:61 Error: Uncaught (in promise): [object Event]
    at resolvePromise (zone.js:468)
    at zone.js:445
    at Image.fail (ngx-image-cropper.js:458)
    at Image.wrapFn [as _onerror] (zone.js:698)
    at ZoneDelegate.invokeTask (zone.js:265)
    at Object.onInvokeTask (ng_zone.js:266)
    at ZoneDelegate.invokeTask (zone.js:264)
    at Zone.runTask (zone.js:154)
    at Image.ZoneTask.invoke (zone.js:335)
ErrorHandler.handleError @ error_handler.js:61
next @ application_ref.js:367
schedulerFn @ async.js:100
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:86
NgZone.triggerError @ ng_zone.js:335
onHandleError @ ng_zone.js:296
ZoneDelegate.handleError @ zone.js:236
Zone.runGuarded @ zone.js:131
_loop_1 @ zone.js:412
drainMicroTaskQueue @ zone.js:421
ZoneTask.invoke @ zone.js:339
error (async)
scheduleEventListener @ zone.js:770
ZoneDelegate.scheduleTask @ zone.js:245
Zone.scheduleEventTask @ zone.js:174
zoneAwareAddListener @ zone.js:824
addEventListener @ VM35763:3
desc.set @ zone.js:703
(anonymous) @ ngx-image-cropper.js:476
ZoneAwarePromise @ zone.js:518
ImageCropperComponent.checkExifAndLoadBase64Image @ ngx-image-cropper.js:444
set @ ngx-image-cropper.js:289
Wrapper_ImageCropperComponent.check_imageBase64 @ /ImageCropperModule/ImageCropperComponent/wrapper.ngfactory.js:56
View_CheckinDetailPage35.detectChangesInternal @ /CheckinModule/CheckinDetailPage/component.ngfactory.js:2238
AppView.detectChanges @ view.js:438
ViewContainer.detectChangesInNestedViews @ view_container.js:71
View_CheckinDetailPage23.detectChangesInternal @ /CheckinModule/CheckinDetailPage/component.ngfactory.js:2465
AppView.detectChanges @ view.js:438
ViewContainer.detectChangesInNestedViews @ view_container.js:71
View_CheckinDetailPage22.detectChangesInternal @ /CheckinModule/CheckinDetailPage/component.ngfactory.js:2534
AppView.detectChanges @ view.js:438
ViewContainer.detectChangesInNestedViews @ view_container.js:71
View_CheckinDetailPage19.detectChangesInternal @ /CheckinModule/CheckinDetailPage/component.ngfactory.js:2609
AppView.detectChanges @ view.js:438
ViewContainer.detectChangesInNestedViews @ view_container.js:71
View_CheckinDetailPage17.detectChangesInternal @ /CheckinModule/CheckinDetailPage/component.ngfactory.js:3652
AppView.detectChanges @ view.js:438
ViewContainer.detectChangesInNestedViews @ view_container.js:71
View_CheckinDetailPage0.detectChangesInternal @ /CheckinModule/CheckinDetailPage/component.ngfactory.js:5847
AppView.detectChanges @ view.js:438
AppView.internalDetectChanges @ view.js:423
View_CheckinDetailPage_Host0.detectChangesInternal @ /CheckinModule/CheckinDetailPage/host.ngfactory.js:36
AppView.detectChanges @ view.js:438
ViewContainer.detectChangesInNestedViews @ view_container.js:71
View_ProvModal0.detectChangesInternal @ /ProvModalModule/ProvModal/component.ngfactory.js:228
AppView.detectChanges @ view.js:438
AppView.internalDetectChanges @ view.js:423
View_TestCenter0.detectChangesInternal @ /ProctorConsoleModule/TestCenter/component.ngfactory.js:322
AppView.detectChanges @ view.js:438
AppView.internalDetectChanges @ view.js:423
View_ProctorConsole0.detectChangesInternal @ /ProctorConsoleModule/ProctorConsole/component.ngfactory.js:366
AppView.detectChanges @ view.js:438
AppView.internalDetectChanges @ view.js:423
View_ProctorConsole_Host0.detectChangesInternal @ /ProctorConsoleModule/ProctorConsole/host.ngfactory.js:36
AppView.detectChanges @ view.js:438
ViewContainer.detectChangesInNestedViews @ view_container.js:71
View_Pages0.detectChangesInternal @ /PagesModule/Pages/component.ngfactory.js:113
AppView.detectChanges @ view.js:438
AppView.internalDetectChanges @ view.js:423
View_Pages_Host0.detectChangesInternal @ /PagesModule/Pages/host.ngfactory.js:31
AppView.detectChanges @ view.js:438
ViewContainer.detectChangesInNestedViews @ view_container.js:71
View_App0.detectChangesInternal @ /AppModule/App/component.ngfactory.js:59
AppView.detectChanges @ view.js:438
AppView.internalDetectChanges @ view.js:423
View_App_Host0.detectChangesInternal @ /AppModule/App/host.ngfactory.js:27
AppView.detectChanges @ view.js:438
ViewRef_.detectChanges @ view_ref.js:175
(anonymous) @ application_ref.js:644
ApplicationRef_.tick @ application_ref.js:644
(anonymous) @ application_ref.js:563
ZoneDelegate.invoke @ zone.js:232
onInvoke @ ng_zone.js:275
ZoneDelegate.invoke @ zone.js:231
Zone.run @ zone.js:114
NgZone.run @ ng_zone.js:144
next @ application_ref.js:563
schedulerFn @ async.js:100
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:86
NgZone.checkStable @ ng_zone.js:240
NgZone.onLeave @ ng_zone.js:316
onInvokeTask @ ng_zone.js:269
ZoneDelegate.invokeTask @ zone.js:264
Zone.runTask @ zone.js:154
ZoneTask.invoke @ zone.js:335
Show 64 more frames
zone.js:388 Unhandled Promise rejection: Event {isTrusted: true, type: "error", target: img, currentTarget: img, eventPhase: 2, …} ; Zone: angular ; Task: HTMLImageElement.addEventListener:error ; Value:

**Comment by Mawi137** [comment]
Hi, can you provide a StackBlitz or git repo so I can reproduce the issue?

**Comment by Mawi137** [comment]
Same as #285, fixed in version 3.1.2
