### ISSUE TITLE
Cropper aligns left when alignImage center and image is small

### ISSUE THREAD

**Issue by nirlob** [Mawi137/ngx-image-cropper#280]
When an small image loaded that don't fill the width of  `<image-cropper>` component and the alignImage is set to 'center' the cropper aligns to left and don't move to all right of the image.

![image](https://user-images.githubusercontent.com/9349965/75916250-48d0d500-5e58-11ea-901c-c457bc000a2d.png)

In the image case the cropper is at maximum of right

The version installed is 3.1.0 and the options are:
`<image-cropper
    [imageChangedEvent]="imageChangedEvent"
    [maintainAspectRatio]="true"
    [containWithinAspectRatio]="containWithinAspectRatio"
    [aspectRatio]="aspectRatio"
    [resizeToWidth]="1024"
    [cropperMinWidth]="128"
    [roundCropper]="false"
    [canvasRotation]="canvasRotation"
    [transform]="transform"
    [alignImage]="'center'"
    [style.display]="showCropper ? null : 'none'"
    format="png"
    (imageCropped)="imageCropped($event)"
    (imageLoaded)="imageLoaded()"
    (loadImageFailed)="loadImageFailed()"
    class="border p-0">
</image-cropper>`

**Comment by Mawi137** [comment]
Fixed in `3.1.1`. Thanks for reporting!
