### ISSUE TITLE
When image is vertical and big, image-cropper crop widget may appear in wrong place.

### ISSUE THREAD

**Issue by nullifiedtsk** [Mawi137/ngx-image-cropper#281]
If image is vertical and big for parent container, image-cropper will scale it down, it's ok.
But then cropper widget will appear in the left with different position as image (you will be able to drag it, but it will be always `shifted` to the left).

In the HTML DOM it's looks like image canvas has `left: calc(50% - XXXpx)` offset, but cropper widget doesn't. Anyway, if will apply same left position as for image, widget will take its own place.

![image](https://user-images.githubusercontent.com/3623027/75921147-b0dfe500-5e71-11ea-85c6-932671ecd72c.png)

Reproduction on StackBlitz:
https://stackblitz.com/edit/angular-rxjs-playground-djnbhf

Just view (without editor): 
https://angular-rxjs-playground-djnbhf.stackblitz.io/

**Comment by Mawi137** [comment]
Hi it seems a little bug snuck it's way in through one of the latest merge requests. It's fixed in version `3.1.1`. Thanks for reporting!
