### ISSUE TITLE
Error NG6002

### ISSUE THREAD

**Issue by iconio** [Mawi137/ngx-image-cropper#282]
Hi

Is this something I did wrong or is it not compatible to Angular 9?

>ERROR in node_modules/ngx-image-cropper/lib/image-cropper.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of VenuesModule, but could not be resolved to an NgModule class.
This likely means that the library (ngx-image-cropper) which declares ImageCropperModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
 1 export declare class ImageCropperModule {
                           ~~~~~~~~~~~~~~~~~~

```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 9.0.4
Node: 12.11.1
OS: darwin x64

Angular: 9.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.4
@angular-devkit/build-angular     0.900.4
@angular-devkit/build-optimizer   0.900.4
@angular-devkit/build-webpack     0.900.4
@angular-devkit/core              9.0.4
@angular-devkit/schematics        9.0.4
@angular/cdk                      9.1.0
@angular/fire                     5.4.2
@angular/material                 9.1.0
@ngtools/webpack                  9.0.4
@schematics/angular               9.0.4
@schematics/update                0.900.4
rxjs                              6.5.4
typescript                        3.6.4
webpack                           4.41.2
```

**Comment by Mawi137** [comment]
It should work with Angular 9. Are you using the latest version 3.1.1?

**Comment by GM-atteoni** [comment]
I'm having this same error.

    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.1
Node: 12.14.1
OS: win32 x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.2
@angular-devkit/build-angular     0.900.2
@angular-devkit/build-optimizer   0.900.2
@angular-devkit/build-webpack     0.900.2
@angular-devkit/core              9.0.2
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@angular/flex-layout              9.0.0-beta.29
@ngtools/webpack                  9.0.2
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

@iconio did you fix that?

**Comment by GM-atteoni** [comment]
It doesn't crash the screen, just show an alert at the console.

**Comment by Mawi137** [comment]
What happens if you run `ngcc`? I just created a new Angular 9 project and it prints out `Compiling ngx-image-cropper : es2015 as esm2015`. I don't get any error in the browser.

**Comment by Madnestranger** [comment]
I'm also having issues with that. 
Using ngx-image-cropper package with 3.1.4 version and Angular 9.0.4.

**Comment by Mawi137** [comment]
Did ngcc run correctly for it?

**Comment by muzyka-viacheslav** [comment]
Unfortunately can't say because for me it fails because of angular\cli issue
"FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory".
In order to fix it I updated angular packages to 9.1.0, but ngcc still fails,
**BUT error with cropper gone**, maybe it will help you or someone who using your package.

**Comment by MaxSereda** [comment]
Hi guys, this fixed the problem for me:
Remove the node modules
rm -rf node_modules

And npm install again and it works properly.

**Comment by MaxSereda** [comment]
Hi guys, this fixed the problem for me

1) Remove the node modules
    rm -rf node_modules

2) And npm install again and it works properly.

**Comment by onyet** [comment]
> Hi guys, this fixed the problem for me
> ( ngx-image-cropper package with 3.1.6 version and Angular 9.1.0 )
> 
> 1. Remove the node modules
>    rm -rf node_modules
> 2. And npm install again and it works properly.

Thanks, however I was successful by simply closing the terminal after install with @latset flag and restarting it (ng serve).

**Comment by carbdias** [comment]
I'm having the problem with Angular 16 and "ngx-image-cropper": "8.0.0",
In the NgModule it says 
Module '"ngx-image-cropper"' has no exported member 'ImageCropperModule'.ts(2305)

I've tried importing BrowserModule and FormsModule too as stated here, but didn't solve the problem
https://stackoverflow.com/questions/61139176/angular-8-ngx-image-cropper-is-not-an-angular-module-import-error

**Comment by micaelamanescau** [comment]
I'm having this problem with Angular 18 and "ngx-image-cropper":"8.0.0",
same error as in the above comment: Module '"ngx-image-cropper"' has no exported member 'ImageCropperModule'.ts(2305)

I also have tried importing BrowserModule and remove node-modules and run npm install again, but any of this tries solve the problem
