### ISSUE TITLE
imageBase64 Not Working for Me

### ISSUE THREAD

**Issue by dotnetmensch** [Mawi137/ngx-image-cropper#285]
Hi, I am trying to use the imageBase64 input and I am getting the following errors and the image does not display.

> ERROR Error: "Uncaught (in promise): [object Undefined]"
    Angular 2
    onerror ngx-image-cropper.js:648
    Angular 16
    setTransformedImage ngx-image-cropper.js:643
    ZoneAwarePromise Angular
    setTransformedImage ngx-image-cropper.js:625
    transformOriginalImage ngx-image-cropper.js:597
    ngOnChanges ngx-image-cropper.js:407
    Angular 26
    RxJS 5
    Angular 24
    DocumentTransformComponent_mat_carousel_1_mat_carousel_slide_1_button_6_Template document-transform.component.html:9
    Angular 9
    DocumentTransformComponent_mat_carousel_1_mat_carousel_slide_1_Template document-transform.component.html:9
    Angular 6
core.js:5845:19

Followed immediately by:

> ERROR TypeError: "this.transformedImage is null"
    onload ngx-image-cropper.js:638
    Angular 16
    setTransformedImage ngx-image-cropper.js:634
    ZoneAwarePromise Angular
    setTransformedImage ngx-image-cropper.js:625
    transformOriginalImage ngx-image-cropper.js:597
    onload ngx-image-cropper.js:537
    Angular 16
    checkExifAndLoadBase64Image ngx-image-cropper.js:529
    set imageBase64 ngx-image-cropper.js:389
    Angular 4
    DocumentEditComponent_Template document-edit.component.html:18
    Angular 15
core.js:5845:19

Here is my config:
 
![image](https://user-images.githubusercontent.com/3160869/76028609-96048380-5ef8-11ea-8b1b-40e606946114.png)

I have tried setting the currentVersion.previewFilePath in both the constructor and ngOnInit in my component and it produces the same result.

I tried reproducing the error in Stackblitz but was unable.  I also tried a couple of different images and same issue.
If I convert my base64 url to a Blob and set it in the imageFile property then it loads and displays with no errors.
I tried debugging the cropper code and I found that if I put a break point here:
![image](https://user-images.githubusercontent.com/3160869/76029126-7ae64380-5ef9-11ea-8b0a-d95294e7d022.png)
Then just continue when it hits then everything works fine and the transformedSize has the height and width values of the image.
However if I put a break point on the line 609 instead, then the transformedSize has a height and width set to 0 and after continuing I will get the first error above. Looks like there methods that return promises and so maybe there is some race condition happening somewhere.

Any ideas would be appreciated. Thank you for all your hard work on this project. It is a really great cropper.

btw, I am using Angular 9.

**Comment by Mawi137** [comment]
Just released version `3.1.2` that should fix the issue. I don't understand why, but a little further down in the code, there's transformedImage.onload and transformedImage.onerror. Sometimes it triggers onerror, but it doesn't say why. Before I did a reset of the image there, now I just ignore the onerror and all works fine..

**Comment by dotnetmensch** [comment]
Thank you! It is working for me now.
