### ISSUE TITLE
Same cropped image on cropping multiple images

### ISSUE THREAD

**Issue by maahibhat88** [Mawi137/ngx-image-cropper#288]
I am using cropping in admin module where i manually crop the signatures of users, and if i didn't refresh the page it takes same cropedImage in every image i crop. their should be some refresh method to remove previous images cropped data on completion of crop

**Comment by Mawi137** [comment]
Sorry, but I don't understand the problem.

**Comment by maahibhat88** [comment]
Actually what happened is, i am having 'n' number of images in a page (refer to image 1), where i am using crop functionality to images(refer image 2), after cropping when i close and open another image for cropping(refer image 3), previous cropped image is now showing in all new previews, so for that after completing crop i set ImageChangedEvent to null, cropper to null, and cropped image to null but it still shows the previous cropped image in every new preview, untill i refresh page, please guide on how to reset it without reloading page. 
![z1](https://user-images.githubusercontent.com/16535422/76936885-baf5ef00-6919-11ea-9e07-0d6fde331811.PNG)
![z2](https://user-images.githubusercontent.com/16535422/76936887-bc271c00-6919-11ea-8614-be0809984349.PNG)
![z3](https://user-images.githubusercontent.com/16535422/76936890-bcbfb280-6919-11ea-842c-18afc75993b5.PNG)

**Comment by shahmeet999** [comment]
I am also facing the same issue
