### ISSUE TITLE
Is it possible to set output format as FormData and not to Base64

### ISSUE THREAD

**Issue by BETZCorentin** [Mawi137/ngx-image-cropper#289]
I'm trying to implement ngx-image-cropper in my website. I'm using an api with my website and when I want to update a profile picture, the api need FormData. I saw the output format could be changed but, in the doc, it not noticed that formdata is allow. So, is it possible to change this output format?

**Comment by Noman2011** [comment]
use this method 
this.croppedImage = base64ToFile(event.base64); // convert to file from base64
this.fileToUpload.append('name', this.croppedImage); // put into formData

**Comment by BETZCorentin** [comment]
Thanks you for your response but it stil don't work for me. I think i will search an other way

**Comment by Noman2011** [comment]
have you initilized? do it...this will work
fileToUpload = new FormData();
this.croppedImage = base64ToFile(event.base64); // convert to file from base64
this.fileToUpload.append('name', this.croppedImage); // put into formData

**Comment by BETZCorentin** [comment]
Yes, I have. it's weird because the api respond that the file must not be null. But when I print it just before the request it's not null

**Comment by Noman2011** [comment]
I had the same issue than I found out my Api accept only formdata than I initialized fileToUpload = new FormData();

**Comment by BETZCorentin** [comment]
i did the same but i don't know why the api return me an error. I see that i send formData but maybe it's a issue fromthe api.
Thank you for your help

**Comment by BETZCorentin** [comment]
the weird this is that it works with a normal input file but it doesn't work when I use the cropper. the api still return me that the value is null

**Comment by Noman2011** [comment]
oh one more thing use this after cropping the image.. like I had "save" button on click of this button i called this code and hide image cropper modal... when you finish your cropping than call this code it will convert your file into formData.. (never forgot to convert base64 to file..if you want a file type return)
this.fileToUpload.append('name', this.croppedImage); // put into formData

**Comment by BETZCorentin** [comment]
yes i append the croppedImage to this.fileToUpload when i want to upload it. but the convertionfrom the event.base64 is done when the immage is cropped

**Comment by Noman2011** [comment]
do not use event.base64 if you want data in FormData use this base64ToFile(event.base64);

**Comment by BETZCorentin** [comment]
This is my code: 

imageCropped(event: ImageCroppedEvent) {
    this.croppedImage = base64ToFile(event.base64);
  }
uploadCV() {
    this.CV = new FormData();
    this.CV.append('name', this.croppedImage);
    this.fileUploaService.uploadCV(this.url, this.CV).subscribe(
      (response) => {
        console.log('request successful', response);
      },
      (error) => {
        console.log('upload failed :', error);
      }
    );
  }

**Comment by BETZCorentin** [comment]
Do you see something wrong ?

**Comment by Noman2011** [comment]
CV = new FormData(); // i initilized outside the function
saveCV() {
this.CV.append('name', this.croppedImage);
this.imgName = this.croppedImage.name; //extra code
} //use a save button after cropping this will save a file into FormData
Now use may be like this 
uploadCV() {
const imageData = this.fileToUpload;
this.fileUploaService.uploadCV(this.url, this.CV).subscribe(
(response) => {
console.log('request successful', response);
},
(error) => {
console.log('upload failed :', error);
}
);
}

//upload on your own method i used like below
updateProfile() {
const imageData = this.fileToUpload;
this.authService.upload(imageData).subscribe(
        data => {
          console.log(data.url);
          this.profileService.updatePartnerPicture(data).subscribe(
            (data) => {
              this.spinner.stopLoader('loader-01');
              if (data.success === true) {
                console.log(data);
                this.updatedPartner(data);
                this.toastr.success(this.toasterSuccess.nativeElement.innerHTML, this.toasterSuccessTitle.nativeElement.innerHTML, {
                  positionClass: 'toast-top-center',
                  enableHtml :  true
                });
              }
    
            },
            error => {
              this.spinner.stopLoader('loader-01');
              this.toastr.error(this.toasterError.nativeElement.innerHTML, this.toasterErrorTitle.nativeElement.innerHTML, {
                positionClass: 'toast-top-center',
                enableHtml :  true
              });
    
            });
        },
        error1 => {
          console.log(error + 'image is not uploaded');
        });
}

**Comment by Noman2011** [comment]
if you will face still an issue I will share my complete code. 
a UI example is https://dev.pakettaxi.tk/en/#/register
you can check by attaching an image

**Comment by BETZCorentin** [comment]
Ok I finally found the issue!!
I just named the file 'file', because I found that his name has undefined, and it's why the api return me ' file can't be null'.
Thanks a lot for your time and your help.

**Comment by Noman2011** [comment]
you are welcome :)
