### ISSUE TITLE
Unable to zoom in the source image 

### ISSUE THREAD

**Issue by olanRay94** [Mawi137/ngx-image-cropper#29]
I try to zoom the source image. I have wrapped it, so by clicking the zoom in icon, the image should be zoom in too. 

I can not find the best way to zoom in the image. Could you help me?

**Comment by Mawi137** [comment]
When you zoom in, I'd take the source image and crop it. Then put the cropped image in the view instead of the source image. (Also keep the source image so you can zoom out again as well).

**Comment by olanRay94** [comment]
Thanks for suggesting. I am thinking for accessing the class:"source-image" and binding for value of scale.
I try to change the source-image with: transform :scale({{scale}}) but nothing change. I just want to zoom the source-image rather than put it in cropped-image
