### ISSUE TITLE
node_modules/ngx-image-cropper/ngx-image-cropper"' has no exported member 'ImageTransform'

### ISSUE THREAD

**Issue by meet0929** [Mawi137/ngx-image-cropper#292]
I have upgrade the version to 3.1.3 and showing error on angular 7

**Comment by Mawi137** [comment]
Can you open `node_modules/ngx-image-cropper/lib/interfaces/index.d.ts` and look what's inside? Do you see `ImageTransform` in there?

**Comment by meet0929** [comment]
export { CropperPosition } from './cropper-position.interface';
export { Dimensions } from './dimensions.interface';
export { ImageCroppedEvent } from './image-cropped-event.interface';
export { MoveStart } from './move-start.interface';
export { ImageTransform } from './image-transform.interface';

**Comment by meet0929** [comment]
@Mawi137  any suggestion

**Comment by Mawi137** [comment]
I have no idea what is wrong to be honest..
