### ISSUE TITLE
Rotate functionality is not working with angular Angular 7.3

### ISSUE THREAD

**Issue by arunkumarpal161** [Mawi137/ngx-image-cropper#293]
Hi,

We have upgraded the ngx-image-cropper version from 2.1.2 to 3.1.3. We have changed the function as per latest version requirement and still rotate functionality is not working. We have debug the code and checked the module with angular 8 then it's working. We need to upgrade version of ngx-image-cropper for angular 7.3. If any one have any suggestion this would be helpful for me ?

**Comment by Mawi137** [comment]
Can you provide a repo to reproduce the issue?

**Comment by arunkumarpal161** [comment]
@Mawi137 
Thanks for your reply.
We can not share the repository because it's client project. If you need to replicate the issue then you can check with angular 7.3 and ngx-image-crooper version 3.1.3. We have changed the function for rotate the image like horizontal, canvasRotation or vertical. We have checked and not getting any error but rotation also empty. We have debug the issue and getting empty object of 'this.transform'. Please check and let me know if mandatory for upgrade the version of angular ?

**Comment by Mawi137** [comment]
Yes, but you can create a simple Angular project that shows the issue and share that. The example here is working correctly: https://image-cropper.stackblitz.io/. If I don’t have something to reproduce the issue, I can’t fix it.

**Comment by arunkumarpal161** [comment]
yes, I have already checked the given example and it's having angular version 8. We will create the the example and share with you for replicate the issue.
