### ISSUE TITLE
How to destroy the cropper component after using

### ISSUE THREAD

**Issue by BETZCorentin** [Mawi137/ngx-image-cropper#295]
I'm trying to implement ngx-image-cropper on my website in a modal but, when I close the modal, the stay in the middle of the screen but invisible and I can't click under this image-cropper anymore. Someone have an idea to solve my problem?

**Comment by Mawi137** [comment]
Do you get any errors in the console?

**Comment by BETZCorentin** [comment]
no i don't get ay error i just close the modale but the img-cropper stay in invisible, i juste can't click. I can see it in the inspector.

**Comment by Mawi137** [comment]
Can you provide a git repo or stackblitz so I can reproduce the issue?

**Comment by BETZCorentin** [comment]
i will try to set you something

**Comment by BETZCorentin** [comment]
ok i will let you a access to the gitLab have you a adresse ?

**Comment by Mawi137** [comment]
MartijnW is my GitLab username

**Comment by BETZCorentin** [comment]
ok i added you. the cropper is implemented in the branch named devCropper. the cropper is implemeted in dashboard/dashboard-info-skipper

**Comment by Mawi137** [comment]
I didn't get any invite?

**Comment by BETZCorentin** [comment]
Ok I didn't invite the right account. Now it's done. And can I have a mail address where I can contact you? instead here ?

**Comment by Mawi137** [comment]
I can see the project, but not the code itself. Sorry, but I'm not going to put any personal contact info here. What I need is a simple angular project that shows the issue.

**Comment by BETZCorentin** [comment]
ok I added you developer I forgot to change your role

**Comment by Mawi137** [comment]
Well that's not the simple angular project I need to be able to reproduce and debug the issue.. It's more likely to be because of the modal, because if it closes properly, the html should no longer be there.
