### ISSUE TITLE
two image croppers on the page conflict with each other

### ISSUE THREAD

**Issue by dolphinsd** [Mawi137/ngx-image-cropper#297]
If you have two separate dialogs that include image cropper, that causes one of them failed to load image, since they both create canvas element, which is hidden in one of the dialogs.

Consider generating unique id for each canvas element.

**Comment by Mawi137** [comment]
Canvas elements are never added to the dom so id's aren't needed. The problem is probably that you are hiding the image cropper. It needs to be visible to be able to calculate the image size.
