### ISSUE TITLE
Component doesn't adapt to retina displays on Safari (mac/ios)

### ISSUE THREAD

**Issue by rrecio** [Mawi137/ngx-image-cropper#298]
For example, I think the loadImageFromURL, on the img.onload: https://github.com/Mawi137/ngx-image-cropper/blob/c09767a160ea934da713b062a3c5bacf30fda34d/projects/ngx-image-cropper/src/lib/component/image-cropper.component.ts#L238 
you could take in consideration window.devicePixelRatio. Like it's done here: https://stackoverflow.com/a/46013342/2570728

**Comment by rrecio** [comment]
Source code:
`            <div *ngIf="showCropper" class="form-group col-lg-4 col-xl-3">
              <label class="col-form-label" for="imageCropper">
                <p class="mb-2">Crop Image</p>
                <image-cropper id="imageCropper" style="height: 200px;"
                               [imageURL]="cropperImageURL"
                               [maintainAspectRatio]="true"
                               [containWithinAspectRatio]="containWithinAspectRatio"
                               [aspectRatio]="9 / 19.5"
                               [onlyScaleDown]="true"
                               [roundCropper]="false"
                               [transform]="transform"
                               [style.display]="showCropper ? null : 'none'"
                               format="png"
                               (imageCropped)="imageCropped($event)"
                               (imageLoaded)="imageLoaded()"
                               (cropperReady)="cropperReady($event)"
                               (loadImageFailed)="loadImageFailed()"></image-cropper>
              </label>
                <label class="col-form-label" for="opacity">
                    Opacity
                    <mat-slider id="opacity"
                                min="0"
                                max="100"
                                step="1"
                                value="100"
                                formControlName="opacity"
                                (valueChange)="opacityChanged()"
                                style="width: 250px;">
                    </mat-slider>
                </label>
                <div style="display:block">
                    <b class="mr-2">Light</b>
                    <mat-slide-toggle (change)="lightDarkToggle()" formControlName="lightOrDark"></mat-slide-toggle>
                    <b class="ml-2">Dark</b>
                </div>
            </div>
`

Results:

Chrome: 

<img width="1552" alt="Screen Shot 2020-03-28 at 3 06 41 PM" src="https://user-images.githubusercontent.com/52694/77830278-3fa8f000-7106-11ea-983a-3b54b0d517ba.png">

Safari:

![image](https://user-images.githubusercontent.com/52694/77830297-5a7b6480-7106-11ea-808d-9c27be355aa7.png)

**Comment by rrecio** [comment]
In Safari, the resulting cropper overlay div is 1/4 of the actual image size:
![image](https://user-images.githubusercontent.com/52694/77830394-d4abe900-7106-11ea-822d-de3278cf0a92.png)

**Comment by Mawi137** [comment]
I just tried in Safari and I don't seem to have that issue? Images show fine in both Chrome and Safari.

**Comment by rrecio** [comment]
If I select the Safari window edge and resize it, the div resizes and looks normal :(

https://www.youtube.com/watch?v=OOLDlyNgFoU

**Comment by Mawi137** [comment]
It's probably this: `[style.display]="showCropper ? null : 'none'"`. It's best not to use display, because the image cropper needs it to be visible to calculate the size. You can replace it with an *ngIf. Hopefully that solves your problem.

**Comment by rrecio** [comment]
It didn't help. I removed [style.display] and all ngIf higher up. The weird thing is that the cropperReady event is called with the following dimensions:

Safari:
<img width="1792" alt="Screen Shot 2020-03-30 at 10 27 53 AM" src="https://user-images.githubusercontent.com/52694/77917716-46a04180-7271-11ea-8203-0df98a0b9e4f.png">

Chrome:
<img width="1655" alt="Screen Shot 2020-03-30 at 10 28 33 AM" src="https://user-images.githubusercontent.com/52694/77917739-4bfd8c00-7271-11ea-907b-2776f0c69be2.png">

**Comment by rrecio** [comment]
Holy mother of god... I just removed the style="height: 200px;" from image-cropper tag and it got fixed on Safari... but then it breaks on Chrome, haha. Look:

<img width="1775" alt="Screen Shot 2020-03-30 at 10 34 14 AM" src="https://user-images.githubusercontent.com/52694/77918283-08efe880-7272-11ea-8e59-b213df29d4da.png">

<img width="1792" alt="Screen Shot 2020-03-30 at 10 34 08 AM" src="https://user-images.githubusercontent.com/52694/77918301-0db49c80-7272-11ea-815f-9aa22ca0d305.png">

**Comment by rrecio** [comment]
Alright. I fixed it... it seems having the image-cropper nested by a label was the problem. Sorry for bothering...

**Comment by Mawi137** [comment]
Glad you figured it out :)
