### ISSUE TITLE
Cropper Outline Width doesn't cover image

### ISSUE THREAD

**Issue by olanRay94** [Mawi137/ngx-image-cropper#30]
I suggest you to change this style:

```
:host .cropper{
  outline-width: 1000px;
}
```

Become:
```
:host .cropper{
  outline-width: 100vw;
}
```

So, the cropper will cover all image width. I have prove it in large image with > 1000px width.
I try to change it in my CSS file, but it can not change.

**Comment by Mawi137** [comment]
Good idea, thanks ;)
(added it in version 0.1.30)
