### ISSUE TITLE
Unable to see image loaded

### ISSUE THREAD

**Issue by moblizeit** [Mawi137/ngx-image-cropper#300]
<image-cropper
                [maintainAspectRatio]="false"
                [aspectRatio]="4 / 3"
                (imageCropped)="imageCropped($event)"
                imageURL = "https://activeforlife.com/content/uploads/2019/01/children-playing-at-home.jpg"
             ></image-cropper>

using angular and above is no loading cropper component at all. no error in console.

**Comment by Mawi137** [comment]
Hi can you upgrade to 3.1.5 and try again?
