### ISSUE TITLE
image is not shown in image-cropper when insert image using ng2-file-upload ng2FileDrop

### ISSUE THREAD

**Issue by lmx-gowthamb** [Mawi137/ngx-image-cropper#305]
`<div  ng2FileDrop [ngClass]="{'another-file-over-class': hasAnotherDropZoneOver (onFileDrop)="dropped($event)"  [uploader]="uploader">
       <label class="custom-file-upload">
		<input type="file"  ng2FileSelect [uploader]="uploader" 
                   (change)="onFileSelected($event)" accept="image/png,image/gif,image/jpeg"  
                    #selectfile />Choose File
	</label>
</div>
<image-cropper [imageChangedEvent]="imageChangedEvent"
	[maintainAspectRatio]="true"
	[aspectRatio]="16/9"
	[onlyScaleDown]="true"
	[roundCropper]="false"
	format="png"
	outputType="base64"
	autoCrop="true"
	[containWithinAspectRatio]="containWithinAspectRatio"
	(imageCropped)="imageCropped($event)"
	(imageLoaded)="imageLoaded()"
	(cropperReady)="cropperReady()"
	(loadImageFailed)="loadImageFailed()"
	[alignImage]="'center'">
</image-cropper>

public onFileSelected(event)
{
      // its worked
      this.imageChangedEvent = event;
}
dropped(event)
{
      // its not worked
      this.imageChangedEvent = event;
}`

**Comment by Mawi137** [comment]
You’ll have to compare the event you get from the file input and the drop component and you’ll see they are not the same. You need to get the file out of the event and pass that to the imageFile input.

**Comment by lmx-gowthamb** [comment]
what we need on the event to show the image on image-cropper!

**Comment by Mawi137** [comment]
File, Blob, base64 string, url to image or change event emitted by a file input. Take your pick! Pass any one of these to the correct Input, which you can find in the readme and it will show that image.

**Comment by lmx-gowthamb** [comment]
yeah i done that. i pass the event like as {target:{files:event}} after get the file drop event. so it will works because you use the input like event.target.event[0] so i send like  this format
