### ISSUE TITLE
Does not support global view encapsulation set to .None

### ISSUE THREAD

**Issue by sondreb** [Mawi137/ngx-image-cropper#307]
Setting the ViewEncapsulation to global None, makes the image editor display the selected source image at 100% height and width, "exploding" the UI and not showing properly any cropping ability.

```
    platformBrowserDynamic().bootstrapModule(AppModule, [
        {
            defaultEncapsulation: ViewEncapsulation.None
        }
    ])
```

**Comment by Mawi137** [comment]
Does some of your css maybe override the cropper's css?
