### ISSUE TITLE
Crop outsite the container and image

### ISSUE THREAD

**Issue by VolodyaGlivka** [Mawi137/ngx-image-cropper#308]
When i first use file upload, crop go outsite container, but if i close and reopen modal or click F12 then it fixed
fisrtTime:  ![Без імені](https://user-images.githubusercontent.com/34774767/78924170-ffe8ed80-7aa1-11ea-833c-e3d2c7dc22de.png)
after reopen modal or F12:
![Без імені](https://user-images.githubusercontent.com/34774767/78924300-39215d80-7aa2-11ea-8b59-ca8df8b49a6a.png)

**Comment by Mawi137** [comment]
Do you select the image to show also in that modal or do you first choose the image and then open the modal?
