### ISSUE TITLE
Drag image inside container

### ISSUE THREAD

**Issue by kienyan** [Mawi137/ngx-image-cropper#309]
Is it possible to make the image inside a fixed container, draggable?

Current situation:
https://i.stack.imgur.com/wCgLy.png
https://i.stack.imgur.com/oFkdh.png

If possible, I want to have it like this example: https://stackblitz.com/angular/omnljkjxykn?file=app%2Fimage-cropper-example-01.component.html

If I am not wrong, this is also possible on Facebook..

I will try to explain what I imagine:
- The image will be loaded as an draggable background image.
- A fixed, pre-defined cropper is displayed in the middle of the screen so that whenever you zoom in/out, it will affect the underlying image.

**Comment by Mawi137** [comment]
Hi, yes that's what I had in mind as well because you can zoom in now, but it will zoom in the middle. Not always what you want. I didn’t get to that yet.

**Comment by manishpatidar028** [comment]
Hello @Mawi137 sir, have you implemented this functionality?

**Comment by kienyan** [comment]
Hi, I'm sorry if my explanation was not clear.. If I understand it correctly, this is how the cropper works:
- Whenever you want to make a crop selection, you need to drag the cropper to the area of where you want it to to be cropped.

What I want is:

- The circle cropper, which you can see in my previous comment under Current situation will have a fixed position which is the center of the image. Instead of dragging the cropper, the image will now be dragged to fit a head into the cropper.

**Comment by Mawi137** [comment]
Yes and I what I already though about was making it possible to move around the image. You'd then need an extra option to fix the position of the cropper. A PR is always welcome ;)

**Comment by manishpatidar028** [comment]
@kienyan Have you got the solution?, If yes then can you help me in this I'm also stuck in the same issue.

**Comment by manishpatidar028** [comment]
@kienyan Have you got solution ? can you please share it with me I'm stuck with the same issue.

**Comment by manishpatidar028** [comment]
> Yes and I what I already though about was making it possible to move around the image. You'd then need an extra option to fix the position of the cropper. A PR is always welcome ;)

can you please share it so I can implement it or brief me about that so I can work on that

**Comment by tooler** [comment]
Hi all, did anyone find a solution for this functionality? We have interest in our company as well.

**Comment by hughanderson4** [comment]
+1
