### ISSUE TITLE
How to change style in class source image?

### ISSUE THREAD

**Issue by olanRay94** [Mawi137/ngx-image-cropper#31]
I am trying to zoom in and zoom out the source image. And I've found the best way to do that. I have to change the style property of class source-image. Like this:

```
[_nghost-c7] > div[_ngcontent-c7] .source-image[_ngcontent-c7] {
    max-width: 100%;
    max-height: 100%;
}
```

In inspect element, I try to change the max-width and max-height and the image going zoom in. So, do you have any idea to access that class directly from TS file?

**Comment by Mawi137** [comment]
I suggest you either fork this repo and make your changes there (in your package.json, you can replace the version number with your github repo) or you can simply copy the source code and add it to your project like that, that way you have full access to the image cropper code.
