### ISSUE TITLE
Default autoCrop setting should be false

### ISSUE THREAD

**Issue by praveeno** [Mawi137/ngx-image-cropper#310]
Hello,

It would be good if default config of autoCrop  will be false, else it lead to confusing state.
this is a config which can be enable if needed, 

but this can be set false as default, this way image cropper work as expected,
select section to crop and crop via button

**Comment by Mawi137** [comment]
WIth `autoCrop` false you need to use `@ViewChild` to get access to the cropper to be able to call the `crop` method. That's not really the best way to use Angular. If you use for example`ngModel` and `ngModelChange` on an input field, you don't have to click a button for the change event to emit. The user types in the input field => the change event is triggered with the entered text. In the image cropper, the user changes the position of the cropper => the cropper emits the cropped image.

With that cropped image, you can do whatever you want. You can store it in a variable and when the user clicks on your button, you can simply take the value of that variable and proceed.
