### ISSUE TITLE
Dimensions not updated after rotating the image

### ISSUE THREAD

**Issue by virgiliojr** [Mawi137/ngx-image-cropper#312]
Hello!

I'm using the `transform` input to rotate the image, but I'm facing the issue that the dimensions width / height are not being updated after that. Is there a way I can manually invert the values?

This is the original image:

<img width="417" alt="Screenshot 2020-04-10 at 21 04 52" src="https://user-images.githubusercontent.com/3875102/79016516-861f3580-7b6f-11ea-835c-fa4d04bf2dfb.png">

After rotating, the area that I can crop the image isn't correct and the image is cut off:

<img width="410" alt="Screenshot 2020-04-10 at 21 07 49" src="https://user-images.githubusercontent.com/3875102/79016538-96371500-7b6f-11ea-9565-7e0ce02f8577.png">

I guess by inverting width and height would fix that, but not sure. Any idea how I could achieve that?

Thank you, very cool component! :)

**Comment by Mawi137** [comment]
Hi there, I think the canvasRotation input is more suited for what you want to achieve.

**Comment by virgiliojr** [comment]
Hi, thanks, it works like a charm!
