### ISSUE TITLE
It is possible save image without padding, full size like in cropper

### ISSUE THREAD

**Issue by DianeTereshko** [Mawi137/ngx-image-cropper#319]
Hi, your cropper is great! Thank you! When Image is cropped and saved she has a padding with white background, not full size. It is possible save image without padding, full size like in cropper selector?

**Comment by Mawi137** [comment]
Hi there, the result will always be the parts covered by the cropper. So if you zoom out or rotate, you will indeed get a background (transparent if output is png). For example: 
![2020-04-23_12h53_12](https://user-images.githubusercontent.com/5464100/80091483-776a5280-8561-11ea-8ea8-f15cb73444e0.png)

The green background is done with css to show that the image itself is transparent.
