### ISSUE TITLE
Scale image at different points

### ISSUE THREAD

**Issue by guilhermeip** [Mawi137/ngx-image-cropper#321]
Hello,
I'm using the cropper, and I would like to be able to scale on different points of the image. It seems to me that the scale is applied only in the center of the image. Look at this example.

Imagine that I want to crop the house (more in the right) by zooming:

![IMG_20200423_132644](https://user-images.githubusercontent.com/15379320/80124350-899abf80-8566-11ea-9ff8-82017b0fbbdb.jpg)

After zooming, I can't select the house anymore:

![IMG_20200423_132623](https://user-images.githubusercontent.com/15379320/80124389-961f1800-8566-11ea-9bf2-2919724ed9d3.jpg)

With the library's current tools, is it possible to select the house?

Thanks for helping the community with this great cropper component.

**Comment by Mawi137** [comment]
Hi there,
That's not possible yet. I haven't figured out what is the best way to do that.

**Comment by 2beers** [comment]
Hello,
I'm in the same situation. I think the best solution would be to add position to transform property
Something like this:

```
export interface ImageTransform {
    scale?: number;
    rotate?: number;
    flipH?: boolean;
    flipV?: boolean;
   position? : {
      x?: number;
      y?: number;
   }
}
```

**Comment by rajeshpanda** [comment]
Any updates on this one?

**Comment by hussyd** [comment]
+1 for this positioning feature!

**Comment by freeminders123** [comment]
Are there any news? Maybe a good option would be to move the image, not the cropper, like in croppie.js.
Would really love to see this feature!

**Comment by juanclb93** [comment]
We need this feature. We just need the transform-origin property for the scale

**Comment by mhubertm** [comment]
+1
I just wanted create the same issue but fortunately I've found this subject!
Any updates here?
