### ISSUE TITLE
Contain With in Aspect Ratio broken in v3.1.7

### ISSUE THREAD

**Issue by bogdanbaghiu** [Mawi137/ngx-image-cropper#322]
Hello. 

I have updated the dependency to version 3.1.7 but it is seen that in this version the option of "[containWithinAspectRatio]" no longer works.
At the moment I have returned to 3.1.6

**Comment by bop10** [comment]
Same here, to make it work i have to rotate the image, then toggleContainWithinAspectRatio, and then rotate it again

**Comment by Mawi137** [comment]
Fixed in `3.1.8`. Thanks for reporting ;)
