### ISSUE TITLE
Setting initial crop position

### ISSUE THREAD

**Issue by axos88** [Mawi137/ngx-image-cropper#327]
Hi,

I am using the cropper just for UI, and offloading the actual cropping and processing to the server (uploading original file, and cropper coordinates, transformation parameters).
I can load the cropper position relative to the image size from the ImageCroppedEvent.imagePosition, however when the user restarts the update the cropping the edit workflow should reload the last saved position. I can't find an easy way to do that.

ngxCropper.cropper expects coordinates relative to the displayed size. 
A workaround is to watch for the scaling coefficient from the ImageCroppedEvent that fires between the load and the ready events, but that seems like a hack.

Is there an actual way to achieve this?

**Comment by viswajeetlenka9** [comment]
You can use cropperReady functionality and set your cropper position inside that function.

**Comment by viswajeetlenka9** [comment]
@axos88 
You can use cropperReady functionality and set your cropper position inside that function.

**Comment by axos88** [comment]
The problem is not on when to do it, but the fact that the cropperPosition input expects coordinates relative to the displayed size, while the ImageCroppedEvent supplies absolute coordinates relative to the number of pixels in the image. 

While the ImagerCroppedEvrent also supplies coordinates relative to the display size, that's not usable if one user does the crop, and another (with a different screen size - thus display size) tries to edit said crop, as the relative coordinate systems don't match up.

**Comment by axos88** [comment]
It's also a bit unusual that the component expects the cropperPosition in a coordinate system that should be internal to the component (the scaling of the image should not be leaked out to the outside, as a parent component is more likely to care about the pixel positions of the cropper rather than this data scaled down based on the relative size of the image and the container of the cropper.
