### ISSUE TITLE
outputType is not a valid property. The ImageCroppedEvent only has base64, and no file output?

### ISSUE THREAD

**Issue by ReaperTech** [Mawi137/ngx-image-cropper#328]
Hello @Mawi137 , thanks for this cropper.
Can you advise please....
'outputType' is not a valid property. The ImageCroppedEvent only has base64, and no file output? How can one get a file output instead of a base64?
![image](https://user-images.githubusercontent.com/43549638/81982510-39c58a80-9632-11ea-83fd-2f16acc86f86.png)

**Comment by Mawi137** [comment]
Update instructions can be found here: https://github.com/Mawi137/ngx-image-cropper/releases

**Comment by ReaperTech** [comment]
Thanks for your reply @Mawi137 . In the breaking changes it says 'this package provides a method called base64ToFile'. Where do I find the package? Is it part of the 'npm install' installation or do i have to download from somewhere? It is not mentioned on the github documentation.

**Comment by ReaperTech** [comment]
For those lookingfor a solution:

```
import {base64ToFile} from 'ngx-image-cropper';

imageCropped(event: ImageCroppedEvent) {
    const file = base64ToFile(event.base64);
    this.startPickedFileUpload(file);    
  }
```
