### ISSUE TITLE
Images with EXIF data (Orientation) fails to orient properly when sending data with ImageCroppedEvent

### ISSUE THREAD

**Issue by jovpet** [Mawi137/ngx-image-cropper#329]
I use image cropper to send data about cropping to the backend where cropping is done and images are saved. It works fine with images with no EXIF data, but images that have EXIF orientation appear fine once uploaded to image cropper, but when I send data about the image position, orientation, width, height to the backend, image is cropped with no respect to orientation since it loses EXIF data due to base64 conversion I guess. Is there a way to remove EXIF upon ImageLoaded event or something similar? I solved this by adding piexif.js and removing EXIF with file reader upon image load, but it adds no angular library to my bundle, and I prefer to avoid that if possible.

**Comment by Mawi137** [comment]
Hi @jovpet 
A base64 can also contain exif data. How do you transform your image to base64? If you use a HTML canvas, the exif rotation should be checked before drawing it on the canvas.

**Comment by jovpet** [comment]
Hi @Mawi137, I somehow missed your response. I used fileReader.readAsDataURL and than the result has been sent to imageCropper as base64 image. I use filereader, since I perform some validation before the image has been sent to cropper. I managed to solve this by using piexif to remove exif data, and than do the transforms in image cropper. It works fine now, thanks.
