### ISSUE TITLE
Needed cropper static width and heigth

### ISSUE THREAD

**Issue by Cipo96** [Mawi137/ngx-image-cropper#330]
I was expected already implemented, i just want a static cropper size that i can define.
I think is very important that feature with the use of [hideResizeSquares]="true"

Can you help me? if i set static width from javascript, cropper can't go over the size

**Comment by rajudandigam** [comment]
I am also looking for similar feature. Can you please add static width and height along with `[hideResizeSquares]="true"`.

That would be really helpful. Thanks!

**Comment by cravr** [comment]
Strongly agree ... exactly what I am after. thanks !!

**Comment by qlaffont-md** [comment]
It's not perfect but It seems to work x) #342

**Comment by Mawi137** [comment]
Released in version 3.2.0.
