### ISSUE TITLE
Can't change the background of the overlay to specifif color?

### ISSUE THREAD

**Issue by rcogal** [Mawi137/ngx-image-cropper#332]
**Version**
"ngx-image-cropper": "^3.1.9"

**Addition Info**
I've tried using the css variables to override the color but it seems not working when I set the background color similar to the background of my app. Even if I set the background color to black, it doesn't follow but if it's something light it will follow the background color

.overlay {
  --cropper-overlay-color: black;
}

![image](https://user-images.githubusercontent.com/29474267/84100258-0feb6200-aa3e-11ea-9f54-8accece86069.png)

**Comment by Mawi137** [comment]
Yes the only solution to that is to set both --cropper-outline-color  and --cropper-overlay-color to the same color.
