### ISSUE TITLE
resizeToHeight is ignored when resizeToWidth is set

### ISSUE THREAD

**Issue by C0nstan** [Mawi137/ngx-image-cropper#334]
Hi there,
i have a scenario where i want e.g. an image to be max 1000x1000 pixels and the source image is e.g. 2000x2000.
The problem is, if i set resizeToWidth to 1000, i could pick an area in that source image with
1500x2000 pixels, so it will be scaled down to 1000x1333. This exceeds my maximum image size.

If i set resizeToHeight, the resizeToWidth will be ignored like stated in the documentation.
So im getting into the same situation where the width is exceeding my maximum.

The only solution i can think about is to check the cropped area and set the correct property according to the choosen aspect ratio.

Is there a good reason why resizeToWidth is ignored when resizeToHeight is set?

Tanks!

**Comment by Mawi137** [comment]
Not really :D It would indeed make sense to remain within the bounds of the width and height. Feel free to adapt and open a PR!
