### ISSUE TITLE
Performance issue when running on mobile, works perfect on desktop

### ISSUE THREAD

**Issue by camicase82** [Mawi137/ngx-image-cropper#336]
Hi, I'm using the images cropper as part of an ionic/angular project but when running on mobile im getting some performance issues to the point of the whole app becoming irresponsive.

What I've seen is that the pointover event takes a long time, and the app would freeze even for a couple of seconds, then have a bunch of calls to the cropped function.

I've created  SO question where you can find more details on the issue, and images to the performance monitor https://stackoverflow.com/questions/62379628/ngx-image-cropper-performance-issues

really appreciate any help, this is the last stone on my way to launching my app

**Comment by Mawi137** [comment]
Each time time the touchend event fires, it will crop the image. It loads an image onto a canvas and then retrieves the base64. So a lot depends on the size of the image.

What you could do is disable autocrop and then call the crop method when the user is done.

**Comment by Mawi137** [comment]
Another possible solution is to use a web worker to offload the main thread. The cropper will probably still take some time, but it will no longer block the UI. https://developers.google.com/web/updates/2018/08/offscreen-canvas

Only problem there is browser support. iOS devices are generally quite performant so Safari might not be that big of an issue.

**Comment by camicase82** [comment]
Hi @Mawi137 Thanks a lot for the response, but we were in kind of a hurry and went for simple cropperjs
About your response, It makes sense, but what I remember from the tests, the delay was before the method got actually called, also last week we found out that the cropper was getting a huge image so also the size was an issue.

I'll check the branch we had with your image copper and provide any feedback.
