### ISSUE TITLE
Ngx Image Cropper Transform scale not smooth

### ISSUE THREAD

**Issue by swagata1603** [Mawi137/ngx-image-cropper#337]
Hi, I have implemented Ngx Image cropper with a range slider, I want the image to be zoom in and out while i am dragging the range bar.

I have followed this example - https://stackblitz.com/edit/image-cropper?file=app%2Fapp.component.html

Right now it is working but the animation is not smooth, it is jerking too much. really appreciate any help.

```
<image-cropper
class="main-cropper"
[imageChangedEvent]="imageChangedEvent"
[maintainAspectRatio]="true"
[alignImage]="center"
[aspectRatio]="1 / 2"
 [transform]="transform"
format="png"
(imageCropped)="imageCropped($event)"
(imageLoaded)="imageLoaded()"
(cropperReady)="cropperReady()"
(loadImageFailed)="loadImageFailed()"
></image-cropper>

<nouislider [min]="0" [max]="100" [step]="1" [(ngModel)]="value" (ngModelChange)="onZoom($event)" [disabled]="disabled"></nouislider>

scaleFactor : number = 1;
scale : number = 1.0;
transform: ImageTransform = {};


onZoom(rangeValue : number){
      if(this.value % this.scaleFactor == 0){
        this.scale = 1+this.value * 0.02;
        this.transform = {
            scale: this.scale
        };
      }
  }
```

**Comment by Mawi137** [comment]
Can you create a StackBlitz so I can try it out?

**Comment by chrispcb** [comment]
Same issue.

Go on your demo https://stackblitz.com/edit/image-cropper-ghkfwc?file=app%2Fapp.component.ts
clic Zoom+ it's very slow. Imported img 2 Mo

On https://alyle.io/components/image-cropper is very smooth

**Comment by Mawi137** [comment]
All it does is pass a number for the transform:scale css property. It you want it to be smooth, it's up to you to pass values with enough decimals and make sure that the slider has enough ticks.

**Comment by janhocevar** [comment]
Same issue for me, it works ok if I use image-cropper with slider, but it works really jerky if used on mobile.

**Comment by Nesz** [comment]
> All it does is pass a number for the transform:scale css property. It you want it to be smooth, it's up to you to pass values with enough decimals and make sure that the slider has enough ticks.

For me it works pretty junky with scale slider, no matter if i make step 0.000000001, 0.1 or anything in between
