### ISSUE TITLE
Crop Canvas

### ISSUE THREAD

**Issue by vishalsingh119** [Mawi137/ngx-image-cropper#338]
I have a canvas element and i want to crop the image from that canvas but I don't have an idea how to pass canvas data to ngx-image-cropper
Here the code i am working on- 

`   
 <canvas id="viewport"  width="620" height="721"></canvas>       
      <image-cropper
        imageURL=''
        [maintainAspectRatio]="true"
        [aspectRatio]="4 / 3"
        format="png"
        (imageCropped)="imageCropped($event)"
        (imageLoaded)="imageLoaded()"
        (cropperReady)="cropperReady()"
        (loadImageFailed)="loadImageFailed()"
    ></image-cropper>
    <img [src]="croppedImage" />`       

And do plugin have any event when we resize then only event trigger?
If have any idea, kindly guide me

**Comment by Mawi137** [comment]
You can't pass a canvas. The image cropper accepts a base64, image file and url as input for the image. There is currently no event that only returns the position no, it only emits with the resulting base64.
