### ISSUE TITLE
How get original image dimensions

### ISSUE THREAD

**Issue by chrispcb** [Mawi137/ngx-image-cropper#339]
Hi,

I would like to crop if original width  > 800px for exemple. 
How to get the original size via  imageLoaded event or cropperReady event ?

**Comment by BruneXX** [comment]
Hi, same here, I want to add a specific validation and I need to get the original image object in order to validate, is there any way to do that with some image cropper event right now? Thanks!

**Comment by AmoghHegde** [comment]
I have raised a PR where the imageLoadedEvent returns the image from which the dimensions can be used for any validations : #366

**Comment by Mawi137** [comment]
'imageLoaded` now emit an object containing those values. See readme for more info.
