### ISSUE TITLE
How to destroy and reinitialise cropper

### ISSUE THREAD

**Issue by arunsrivastavapulp** [Mawi137/ngx-image-cropper#341]
Hi,

I am using this cropper in popup and i want to destroy/reinitialise cropper on closing/ re opening popup.

Any idea??

**Comment by sivajisanapala** [comment]
To my understanding, you are not getting the popup on selecting the same image. If that is the case simply empty the file input value.
`@ViewChild('inputfile', {static: false})
  InputVar: ElementRef; 
  emptyInput() { 
    this.InputVar.nativeElement.value = ""; 
  }`

**Comment by AntonGrekov** [comment]
I had same issue. After reopenning same file cropper wont appear. Solution by @sivajisanapala helped me , thanks ! :)
html file inputs are smart enough not to change file data if you select same file twice. Just empty file input value to make it all work
