### ISSUE TITLE
Drag image inside cropping aera

### ISSUE THREAD

**Issue by chrispcb** [Mawi137/ngx-image-cropper#344]
Hi !

Iin your demo: https://stackblitz.com/edit/image-cropper-ghkfwc?file=app%2Fapp.component.html
Add [hideResizeSquares]="true", zoom in. The image remains centered. How choose another area of ​​the image ?
you should be able to move it inside  cropping aera.

Cropping aera should be static, and image should be draggable.

**Comment by hughanderson4** [comment]
Please consider reopening this issue.  There is no way to change the visible area after zooming in.  The zoom just zooms the center of the image, what if the user needs to crop somewhere other than the center?
