### ISSUE TITLE
Cropper completely broken in latest Chrome version

### ISSUE THREAD

**Issue by Svrkota-S** [Mawi137/ngx-image-cropper#347]
Hi fellow developer(s) of this component, I don't know if you're aware, but cropper is completely broken in latest Chrome version Version 84.0.4147.89 (Official Build) (64-bit). Any chance someone could take a look at what's wrong?

I even tested Dev v85 of Chrome and it's broken there as well.

Thanks for any help!

**Comment by Mawi137** [comment]
Just restarted Chrome to get the update and it works fine?

**Comment by Svrkota-S** [comment]
@Mawi137 , thanks for such a quick reply! What's your current version after update?

If you're using Mac, they still haven't released v84 for Mac I think, it's only released for Windows.

You can download latest Dev version and you'll see it's broken there:

https://chromereleases.googleblog.com/2020/07/dev-channel-update-for-desktop_21.html

For example, this Demo is broken on latest Windows release of Chrome:

https://stackblitz.com/edit/image-cropper-ghkfwc?file=app%2Fapp.component.html

Screenshot:

![image](https://user-images.githubusercontent.com/20969668/88301126-8bf6ec00-cd04-11ea-80bc-ec7f6d9d5ba2.png)

**Comment by Mawi137** [comment]
I have a MacBook indeed, but I checked and I have the exact same version as you. My windows laptop is managed by the organisation so it's still at version 83 at the moment..
