### ISSUE TITLE
Issue in cropper for selecting huge dimension image

### ISSUE THREAD

**Issue by 08Thug** [Mawi137/ngx-image-cropper#348]
i'm facing a feature issue with cropper  i'm currently using this 
`  [maintainAspectRatio]="true"
      [aspectRatio]="fourbythree?16 / 9 : 1 / 1"
      [resizeToWidth]="640"`

I can't able to crop the full images with big dimensions,
[https://prnt.sc/tlebvr](url)
by enabling false in **[maintainAspectRatio]** i get to crop the full image but it doesn't fullfil the **[aspectRatio]**
however i can crop full dimension with the help of  **containWithinAspectRatio** but it gets with padding i dont want the paddings. Any help from the creator

**Comment by Mawi137** [comment]
Well that's simply how it works. How can it select the full image and still fulfil the aspect ratio constraint?
