### ISSUE TITLE
Not working in modal dialog with Ionic 5

### ISSUE THREAD

**Issue by mentamarindos** [Mawi137/ngx-image-cropper#355]
It works in a normal ionic page, but does not work in a modal 
https://ionicframework.com/docs/api/modal

I'm using ionic 5 + Angular 9

**Comment by ArturV93** [comment]
It's working, try to follow this tutorial :
https://www.leonelngande.com/creating-a-lazy-loaded-image-cropping-modal-component-with-ionic-5-and-ngx-image-cropper/

**Comment by mentamarindos** [comment]
Wow, just what I needed, the tricky part was the `changeDetection: ChangeDetectionStrategy.OnPush`

Thank you!

**Comment by peteresteris** [comment]
@ArturV93 , I'm sad 'cause it doesn't work for me. I received an empty image-cropper component.
