### ISSUE TITLE
Can't set cropper position to full image.

### ISSUE THREAD

**Issue by avinashrg94** [Mawi137/ngx-image-cropper#36]
I tried to give cropper to full image and i had given maintainAspectRatio to false. But it always takes width of the cropper as same as height of the image.

**Comment by avinashrg94** [comment]
yes

**Comment by Mawi137** [comment]
It does indeed always use the aspect ratio to set the default cropper position. I'll change it so it doesn't do that when maintainAspectRatio is set to false.

**Comment by rsseurope** [comment]
I made a workaround for this for the time being, maybe you can use it.
`imageLoaded() {
        setTimeout(() => {
            this.setCropper();
        }, 250);
    }`
`setCropper() {
        const el = this.elementRef.nativeElement.querySelector('.source-image');
        let imageWidth = el.offsetWidth;
        let imageHeight = el.offsetHeight;
        this.cropperPos = {
            x1: 0,
            y1: 0,
            x2: imageWidth,
            y2: imageHeight
        };
    }`

**Comment by Mawi137** [comment]
This is GitHub so feel free to create a PR!

**Comment by Mawi137** [comment]
Should be fixed in version 1.3.1!

**Comment by rutpshah** [comment]
This doesn't seem to fix yet.
