### ISSUE TITLE
Multiple Cropper Box On  Same Image, Cropper Box Color, Give Name To Cropper Box ?

### ISSUE THREAD

**Issue by ozer0306** [Mawi137/ngx-image-cropper#374]
Hello is that possible to create multiple cropper box on  the same image ?

Hello is that possible to change cropper box color ?

Also is it possible to  give name inside the cropper box ?

**Comment by Mawi137** [comment]
Yes, you can use multiple image croppers on the same page. (e.g. `(imageCropped)="imageCropped($event, 'SOMETHING_TO_ID_THE_CROPPER')"`.

Yes, it's possible to change the color (see readme or simply override the css in your app).

Not sure what you mean by name?

**Comment by ozer0306** [comment]
**Here is the my HTML file** 
```
<image-cropper 
[style.display]="showCropper ? null : 'none'"
[imageChangedEvent]="imageChangedEvent" 
[maintainAspectRatio]="false" 
[cropper]="cropper" 
format="png" 
(imageCropped)="imageCropped($event, 'secondCropper')".
(imageLoaded)="imageLoaded()" >
</image-cropper>

<image-cropper id="secondCropper"
[style.display]="showCropper ? null : 'none'" 
[imageChangedEvent]="imageChangedEvent" 
[maintainAspectRatio]="false" 
[cropper]="cropper" 
format="png"

(imageLoaded)="imageLoaded()" >
</image-cropper>
```

But it gives an error, what should I do in my .ts file ?

**In .ts file**

I have created this function, after that what shoul I do ?

```
 imageCropped(image: string,id:string) {
    this.croppedImage = image;
  }
```

**Comment by ozer0306** [comment]
**Also is it possible to give name inside the cropper box ?**

I wan to put text middle of cropper box ? Is that possible ?

**Comment by Mawi137** [comment]
You could try with some css with something like 
```
.cropper:after {
 content: 'Text here';
}
```

The images cropper doesn't provide an out of the box solution for it.
