### ISSUE TITLE
Vertical alignment

### ISSUE THREAD

**Issue by ihor-zinchenko** [Mawi137/ngx-image-cropper#375]
hi! First of all - amazing package! Thank you! 
Tell me please how I can center the cropper area vertically?
![image](https://user-images.githubusercontent.com/38561554/96593417-252ca300-12f2-11eb-9b1c-95b0dbd412db.png)
Also, tell me please hove to remove the paddings?

**Comment by Mawi137** [comment]
The padding can't be removed because they are needed for the squares. 

What if you only set a max-height on the image-cropper? You can then maybe wrap it in a div which centers the image cropper vertically?
