### ISSUE TITLE
Image size getting bigger after cropping

### ISSUE THREAD

**Issue by likhit-vivek** [Mawi137/ngx-image-cropper#376]
I put a restriction to my website user that only images less than 10 MB can be uploaded.
But as a user, when I am uploading a 2.1 MB image and crop it using ngx-image-cropper, the resulting image is of 11.6 MB.
This should not happen. Why is a cropped image bigger than the whole image?
How can I prevent this? Pls help.

**Comment by lonerzzz** [comment]
I do not know how the library works internally, but making one image from another often results in unpredictable sizes unless specific parameters are set in the saving process. Unless the author of this tool suggests there are parameters that you can set, you are best off taking the resulting image and saving it with appropriate image compression to get it to the desired size. Only then will you be able to control the size of the resulting image.

**Comment by IgorGeorgioski** [comment]
Hello,
I am having the same error. The original file is 1.4MB, and after the crop its size is 7MB. That's 5 times more than the original file. I am using this lib for a long time, but now I need this fixed.

**Comment by likhit-vivek** [comment]
@IgorGeorgioski I was able to fix the issue by changing the output format from `jpg` to `png`. Hope it helps.

**Comment by IgorGeorgioski** [comment]
@likhit-vivek its the same for me. I was never using `jpg`, but `png` instead. So the main problem is with a png output format.

**Comment by Mawi137** [comment]
This is a common problem with a HTML canvas. What I found that may help is: make sure the output type is the same as the input type (so don't convert pdf to jpg or the other way around). Also, converting to a Blob may decrease filesize as well (you can use `base64ToFile` that is provided by this lib (it should be called base64ToBlob, I know :) ))

**Comment by BizzottoClaudio** [comment]
Even without cross convertion between jpg and png the image is still bigger after being cropped.
I have a 5400*1800 at 5.4 MB, and after cropping it in a 16:9 ration with resizeToWith=1920 the resulting file weight is 8 MB.
The imageQuality has no effect

**Comment by jlcvp** [comment]
This seems to be a problem on how HTML Canvas encodes data. It will always use RGBA. 

Our everyday photos uses RGB encoding and the lack of that alpha channel, saves a lot of storage.

**Comment by antoniogenaro** [comment]
I'm having the same issue. Is there any way to fix this? Thanks in advance

**Comment by jlcvp** [comment]
I've solved it on my project using a different compressor after the crop
https://github.com/Donaldcwl/browser-image-compression

**Comment by timsar2** [comment]
It is ok if you do it right.
first change your image format to what image type you want with canvas.
also set format property in image-cropper tag
`<image-cropper
          format="webp"
      ></image-cropper>`
`canvas.toBlob((blob) => {        // get content as webp blob\

            }, 'image/webp');`
be careful this is async process.

**Comment by abnersouza** [comment]
Same issue if i set a jpg image with 2mb it outputs a png base64 with 21mb. Is it possible to set the file type for cropping dynamic so after the upload is set i can change it based on file type? E.g upload a jpg it sets the return base64 to base64 jpg. At the moment is hardcoded png as output so getting huge files from jpg cropper.

**Comment by jlcvp** [comment]
> Same issue if i set a jpg image with 2mb it outputs a png base64 with 21mb. Is it possible to set the file type for cropping dynamic so after the upload is set i can change it based on file type? E.g upload a jpg it sets the return base64 to base64 jpg. At the moment is hardcoded png as output so getting huge files from jpg cropper.

Even using the same format as input/output it gets bigger. I solved my problem encoding it with [this lib](https://github.com/Donaldcwl/browser-image-compression) after cropping

**Comment by Oliver19xx** [comment]
The issue is still there in version 6.1.0

**Comment by Prem-Kumar-G** [comment]
> @IgorGeorgioski I was able to fix the issue by changing the output format from `jpg` to `png`. Hope it helps.

for me 'jpg' didn't work, but 'jpeg' worked. referred docs, its mentioned 'jpeg'

**Comment by jalalh14** [comment]
I have this issue too in version 6.1.0, I can not change output format from 'png' to 'jpeg' because I do want png images with transparent background, ... . I also set [resizeToWidth] = "1920" and [resizeToHeight] = "1080", it helped in some cases, but the bug still exists and some images made bigger after crop.

**Comment by jalalh14** [comment]
> @IgorGeorgioski I was able to fix the issue by changing the output format from `jpg` to `png`. Hope it helps.

this helps only for jpg images, because png images with transparent background can not be changed to jpeg because backgrounds can not be transparent in jpg images

**Comment by Hardknox1996** [comment]
> > @IgorGeorgioski I was able to fix the issue by changing the output format from `jpg` to `png`. Hope it helps.
> 
> this helps only for jpg images, because png images with transparent background can not be changed to jpeg because backgrounds can not be transparent in jpg images

> I put a restriction to my website user that only images less than 10 MB can be uploaded. But as a user, when I am uploading a 2.1 MB image and crop it using ngx-image-cropper, the resulting image is of 11.6 MB. This should not happen. Why is a cropped image bigger than the whole image? How can I prevent this? Pls help.



-------------- Below solution works for my code --------------

I am using "ngx-image-compress" to compress images so I can save my cloud storage,
but I also face same issue, 
When I am compressing ".jpg" file it works properly, but when I try it with '.png' file (eg, 2MB) file after process complete the file size is more than 2MB.

So just to fix that, I started every ".png" image file to ".jpg"
I just updated the type ".png" to ".jpg", refer below ss
![image](https://user-images.githubusercontent.com/13415434/201181889-b13dc1ff-f09f-4fda-a2c9-999373dbde4b.png)


Note: 
It will remove the transparency and make file every ".png" file to ".jpg" - (In my project I don't need transparent image, so this works for me.)

But if we found any to convert again ".jpg" file to ".png"  with transparency, Then we can use it after the compression process done.

**Comment by OssFit** [comment]
I found the same issue and I fixed creating a variable for the output format 
like this in the component where we use the cropper:

const typeFile = this.ImageFile.type;
    const extensionFileArray = typeFile.split('/');
    const extensionFile = extensionFileArray[1];
    const dialogRef = this.dialog.open(ImageCropperComponent, {
      data: {
        data: file,
        aspectRatio: 1,
      },
      maxWidth: '400px',
    });
    dialogRef.closed.subscribe((blob) => {
      if (!blob) return;
      const newBlob = new Blob([blob as BlobPart]);
      const file = new File([newBlob], 'croppedImage.' + extensionFile, {
        type: typeFile,
      });
      this.ImageFile = file;

and the same in the format property in the image cropper tag.

**Comment by tlranjan** [comment]
I see this issue has been closed. Actually this is the biggest flaw while using it in production.

**Comment by lokesh-saini-itbd** [comment]
i

**Comment by madmacc** [comment]
Is there any solution for this with a .png without using a compressor?

**Comment by hamidh2** [comment]
> @abnersouza velho, even using the same format as input/output it gets bigger. I solved my problem encoding it with [this lib](https://github.com/Donaldcwl/browser-image-compression) after cropping

I used this package [browser-image-compression](https://www.npmjs.com/package/browser-image-compression) and It decreased the image size tremendously. 

 ```
   async handleFileInput(event: any): Promise<void> {
        this.imageChangedEvent = event;
        const files = event.target.files;
        if (files.length !== 1) {
            return;
        }
        const file = files[0];
        const fileReader = new FileReader();
        fileReader.onloadend = () => {
            this.croppieUrl = fileReader.result ?? '';
        };
        this.isLoading = true;
        const compressedFile = await imageCompression(file, {
            alwaysKeepResolution: true,
            maxSizeMB: 2,
            maxWidthOrHeight: 1136,
            useWebWorker: true,
        });
        this.isLoading = false;
        fileReader.readAsDataURL(compressedFile);
    }
```

Obviously, the above code is shared just for inspiring purposes.
