### ISSUE TITLE
Change the color of the uncut part of the image

### ISSUE THREAD

**Issue by IvanAllue** [Mawi137/ngx-image-cropper#377]
Good morning / afternoon, first of all, excuse my bad English, I'm using google translator.

My goal is the following: I am using this tool because I need to cut the images 1/1. I've already done that. What happens is that I would like the rest of the image that now has a whiter tonality than normal to be able to change that white effect to another color.
I have tried using the styles with --cropper-outline-color and --cropper-overlay-color but they haven't affected anything (I'm probably not getting to understand how to use it).
![Captura](https://user-images.githubusercontent.com/50440904/97471295-dc579880-1948-11eb-9aca-b02bf6797703.PNG)

I need that the non-useful part of the image when cropping it has a blue tone.

Thank you very much in advance, the tool is great ^^

**Comment by Myerden** [comment]
You can change the style by this way


```
image-cropper .cropper {
	outline: rgb(0 0 0 / 30%) solid 100vw !important;
}
```

**Comment by mediantiba** [comment]
I have the same problem. After inspecting in Chrome, I see there's an element with class `.overlay` just before the cropper, if you remove that element it looks much better, which brings the question why is it there in the first place?

**Comment by IvanAllue** [comment]
@mediantiba try the @Myerden solution, this has worked for me.

It happened to me that apart from testing the documentation methods I also tried to play with the overlat, the solution in the end was very simple, thank you very much and I hope it will serve future users, I looked for this topic but did not see info.

Thx @Myerden

**Comment by mediantiba** [comment]
I tried @Myerden solution but it's not working for me. Note that I am using the default view encapsulation, which is `Emulated`.

**Comment by upeachyaLf** [comment]
@Myerden solution works well for square cropper, but it doesn’t work as expected for round cropper. Any way we can fix this?

<img width="499" alt="Screen Shot 2021-01-01 at 7 44 40 PM" src="https://user-images.githubusercontent.com/55175180/103439954-ced0ce80-4c69-11eb-968c-c103cedb6d4b.png">

**Comment by thousandsofraccoons** [comment]
@upeachyaLf I've managed to do it with:
```css
.cropper-view-box  {
  filter: brightness(1);
  overflow: hidden;
  border-radius: 50%;
}
.cropper-canvas img {
  filter: brightness(0.5);
}
.cropper-face {
  /* background-color: #fff; */
  left: 0;
  top: 0;
  border-radius: 50%;
}
```

**Comment by srivatsajoshi19** [comment]
@multipliedtwice  Your solution is not working
