### ISSUE TITLE
EXIF data lost after cropping

### ISSUE THREAD

**Issue by Dustb0** [Mawi137/ngx-image-cropper#380]
Hello, 

I'm passing a JPEG image with EXIF-data into the **imageBase64-input** of the image-cropper-component. The **format-Input** is set to "jpeg".

After cropping the image the EXIF-data of the original data is no longer present in the cropped image. I'd expect the component to retain that data.

**Comment by Mawi137** [comment]
This lib uses a HTML canvas to crop the image and will thus not keep EXIF data. Maybe another lib exists that can copy EXIF data, but I couldn't really find anything myself.
