### ISSUE TITLE
ngx-image-cropper having "hammerjs" dependency and hammer js using jquery2.1.1 version which is throwing vulnerability issue in whitesource.

### ISSUE THREAD

**Issue by RanjithNKtrr** [Mawi137/ngx-image-cropper#383]

**Comment by Mawi137** [comment]
Hammerjs hasn't been updated in the last years it seems, nothing I can do about that..

**Comment by Mawi137** [comment]
Seems better to remove hammerjs all together and replace the pinch events: https://stackoverflow.com/questions/11183174/simplest-way-to-detect-a-pinch/11183333#11183333

**Comment by RanjithNKtrr** [comment]
Hammerjs is installed as a dependency once I install ngx-image-cropper. I can't able to remove hammerjs package from image-cropper package . Now I am in a situation to remove image-cropper entirely.

**Comment by Mawi137** [comment]
Hmm I thought it wouldn't be installed since it's optional, but apparently it does.. 

I just removed it from the optionalDependencies so it should no longer be installed with the cropper. Version `3.3.1`.

**Comment by RanjithNKtrr** [comment]
Thanks let me update and check

**Comment by RanjithNKtrr** [comment]
It's working fine now. Thanks
