### ISSUE TITLE
Changing the cropperMaxWidth property dynamically doesn't change the cropper

### ISSUE THREAD

**Issue by itreppert** [Mawi137/ngx-image-cropper#385]
Hi there,
what I'm doing is that I change the cropperMinHeight and so on.

This doesn't have any effect on the cropper component.

Changing the aspectRatio dynamically works fine.

Am I doing sth. wrong ?

Regards,
Holger
  

                   <image-cropper
                        [imageChangedEvent]="imageChangedEvent"
                        [autoCrop]="false"
                        format="jpeg"
                        [imageQuality]="imageJpegQualityPercent"
                        [cropperMinHeight]="cropperMinHeight"
                        [cropperMinWidth]="cropperMinWidth"
                        [cropperMaxHeight]="cropperMaxHeight"
                        [cropperMaxWidth]="cropperMaxWidth"
                        initialStepSize="1"
                        onlyScaleDown="true"
                        [maintainAspectRatio]="true"
                        [aspectRatio]="selectedImageAspectRatioValue"
                        (imageCropped)="imageCropped($event)"
                        (imageLoaded)="imageLoaded()"
                        (cropperReady)="cropperReady()"
                        (loadImageFailed)="loadImageFailed()"
                      ></image-cropper>

  changeCropper(event: event) {
    if (this.selectedImageAspectRatioValue > 1) {
      this.targetImageWidth = environment.ImageUpload.targetUploadImageLongestSide;
      this.targetImageHeight = environment.ImageUpload.targetUploadImageShortestSide;
      // this.cropperMinWidth = environment.ImageUpload.minUploadImageLongestSide;
      // this.cropperMinHeight = environment.ImageUpload.minUploadImageShortestSide;
      // this.cropperMaxWidth = environment.ImageUpload.maxUploadImageLongestSide;
      // this.cropperMaxHeight = environment.ImageUpload.maxUploadImageShortestSide;
      this.cropperMinWidth = 300;
      this.cropperMinHeight = 200;
      this.cropperMaxWidth = 800;
      this.cropperMaxHeight = 600;
    }
}

**Comment by Mawi137** [comment]
These sizes don't apply to the complete component, only to the cropper (with the dots) inside the component. The sizes are relative to the source image. So it takes into account the scale of the loaded image.

**Comment by itreppert** [comment]
That's a pitty. Because I thought (and hoped) that I could change the cropper (the thing with the dots) e.g.  aspect ratio and max and min height and width. 
So I need to have a possibility to have a min and maximum cropper size for a certain aspect ratio. That's what the customer needs.
(Aspect Ratio 2/3 min height 400 px, max height 600px, min width  600px, max width 900px)
(Aspect Ratio 3/2 min height 600 px, max height 400px, min width  900px, max width 600px)

**Comment by Mawi137** [comment]
Maybe I misunderstood then, because yes you can do that with the properties you used. No need to set the min and max height when using maintainAspectRatio, it will be calculated of the min and max width.

**Comment by itreppert** [comment]
Sorry for being late ;)

The thing is, that I need to have the cropper (the dotted one) to be independent 
from the source image.
I just wanted to cut images out of the source image, that have a ranged width (and height) 
depending of the chosen aspect ratio.

So it doesn't matter, if the source image was e.g. 3000x3000 px or 1280x1920.

I want the cutted out image width to be between 

- 525px and 1920px for the aspect ratio of 3/2
- 350px and 1280px for 2/3

This doesn't work for me.



So, what I do is:

`selectedImageAspectRatioValueChanged(ratio: number): void {

    // horizontal
    if (ratio > 1) {
      this.selectedImageAspectRatioValue = 3 / 2;
      this.cropperMinWidth = environment.ImageUpload.minthreetworatiowidth; //525
      this.cropperMaxWidth = environment.ImageUpload.maxthreetworatiowidth; //1920
      // vertical
    } else {
      this.selectedImageAspectRatioValue = 2 / 3;
      this.cropperMinWidth = environment.ImageUpload.mintwothreeratiowidth; //350
      this.cropperMaxWidth = environment.ImageUpload.maxtwothreeratiowidth; //1280
    }
  }`


And the template:

`                      <image-cropper
                        [imageChangedEvent]="imageChangedEvent"
                        [autoCrop]="false"
                        format="jpeg"
                        [imageQuality]="imageJpegQualityPercent"
                        onlyScaleDown="true"
                        [maintainAspectRatio]="true"
                        [aspectRatio]="selectedImageAspectRatioValue"
                        (imageCropped)="imageCropped($event)"
                        (imageLoaded)="imageLoaded()"
                        (cropperReady)="cropperReady()"
                        (loadImageFailed)="loadImageFailed()"
                        [cropperMinWidth]="cropperMinWidth"
                        [cropperMaxWidth]="cropperMaxWidth"
                      ></image-cropper>`

**Comment by itreppert** [comment]
![grafik](https://user-images.githubusercontent.com/697513/102622062-ce501800-4140-11eb-82f8-d6ef8012138f.png)


![grafik](https://user-images.githubusercontent.com/697513/102622081-d8721680-4140-11eb-80df-a4f2c45fd41f.png)


![grafik](https://user-images.githubusercontent.com/697513/102622102-df008e00-4140-11eb-99f9-731ca601a01b.png)

![grafik](https://user-images.githubusercontent.com/697513/102622124-e4f66f00-4140-11eb-89af-32e3ab0f5047.png)

**Comment by itreppert** [comment]
What I found out is, that the first values I gave initially when the component loads, work fine.
But when I dynamically change the values, only the initial setting actually works.

Looks like there is an update problem ?

**Comment by itreppert** [comment]
Hi Mawi,

I cloned the repository and what I found in a quick hack is the following:

in the ngOnChanges method I added:
```

    if(changes.cropperMinWidth){
      this.settings.cropperMinWidth = changes.cropperMinWidth.currentValue;
      this.reconfigureCropper();
    }
    if(changes.cropperMaxWidth){
      this.settings.cropperMaxWidth = changes.cropperMaxWidth.currentValue;
      this.reconfigureCropper();
    }
```




and this to simplify

```
  private reconfigureCropper() {
    this.resizeCropperPosition();
    this.setMaxSize();
    this.setCropperScaledMinSize();
    this.setCropperScaledMaxSize();
    this.resetCropperPosition();
  }
```
