### ISSUE TITLE
Is it possible to have a loading indicator of some sort when rotating images?

### ISSUE THREAD

**Issue by MatthewLHolden** [Mawi137/ngx-image-cropper#388]
When rotating images, sometimes it hangs for a few seconds. Is there a method on sticking some sort of loading mechanism in place to indicate to the user that the process is indeed taking place?

**Comment by MatthewLHolden** [comment]
Thanks @Mawi137 - I did try that by toggling a boolean value. The issue that occurs:

1. If i have a single function to toggle a boolean that doesn't call any rotate functions, the boolean toggles immediately
2. The moment a rotate function is included, the delay still occurs and then quickly flips the boolean to true and then false once the `imageLoaded` function is called.

The below example will not toggle the loader when the `rotateLeft` function is called. There's about a 1 to 2 second delay. When it finally kicks in, it toggles the boolean to true, and then straight back to false because it's completed the function. This unfortunately makes the loader a little useless because it doesn't react quickly enough.

```
rotateLeft() {
    this.loader = true;
    this.canvasRotation--;
    this.flipAfterRotate();
}
```

Have i approached this incorrectly?

**Comment by charbelbadawi** [comment]
Hello @Mawi137, i am facing a similar issue.
When using the same code as @MatthewLHolden :
`
rotateLeft() {
    this.loader = true;
    this.canvasRotation--;
    this.flipAfterRotate();
}
`
I am getting the error: `ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'.`

i was able to bypass this error temporarly using a `setTimeout` hack that i saw on stackoverflow.

Is their something that i am missing?

**Comment by Mawi137** [comment]
I updated the demo of this lib to include a loader when rotating, you should indeed use setTimeout when showing the loader. The image rotation is a heavy operation and will block the ui thread, so a css spinner will probably not spin. A solution would be to offload that work to a worker instead so the ui remains responsive, but I'd have to take some time to look into that.

**Comment by charbelbadawi** [comment]
Yes i also faced the non-responsive UI when rotating big images, it would be perfect if a loader/spinner is shown during these heavy operations. I will try to find a solution and keep you updated.
Thank you for your time and this exceptional component!

**Comment by Kuldip097** [comment]
Hello @Mawi137 and @charbelbadawi,
Have you found a solution for this?
Because I'm stuck in it and I can't find a solution.
