### ISSUE TITLE
Multiple crop boxes in a single image

### ISSUE THREAD

**Issue by angularteam402** [Mawi137/ngx-image-cropper#391]
Hi ,
Is there any chance to show multiple crop boxes in a single image?

**Comment by Mawi137** [comment]
Hi there,
No this is not possible and is seems very complex to implement.

**Comment by angularteam402** [comment]
Hi Mawi137, 
Thanks for your reply. Actually we are working on ngx-image-cropper where we need to show multiple crop boxes in a single image. when user click on some button we need to show multiple crop boxes in a image. we are able to show single box but trying to show multiple crop boxes at a time. So I need your suggestion what is the best and easiest way (or) what is the best angular library  to show the multiple boxes, zoom In and zoom out, crop based on input co-ordinates  at a time.

**Comment by Mawi137** [comment]
I have no idea tbh :)
