### ISSUE TITLE
Uploading broken image interrupts component init process

### ISSUE THREAD

**Issue by Fallved** [Mawi137/ngx-image-cropper#392]
Uploading broken image interrupts component init process. Component's layout stops at some point and only small block (20x20px approximately) appears in modal container.
![image_2020_12_01T14_28_18_453Z — копия](https://user-images.githubusercontent.com/75789514/101789095-6e031a00-3b33-11eb-91c7-7cd0d96f2931.png)

**Comment by Mawi137** [comment]
It shoud emit loadImageFailed at that point. If not, then there's an issue :)
