### ISSUE TITLE
backgroundColor not changing for jpeg format

### ISSUE THREAD

**Issue by arorashakti** [Mawi137/ngx-image-cropper#393]
Loading JPEG file in  1 / 1 aspect ratio is adding a padding in black color, instead, I want to add a white background color.  When I'm setting a backgroundColor property to hex code #FFFFFF (white) , still base64 is setting the background color to black. please advise

**Comment by Mawi137** [comment]
The background applies to a transparent image, so there must be something wrong with the cropping / resizing. Can you create a stackblitz to reproduce?

**Comment by justinrlle** [comment]
Hello, I just stumbled on this, [here is a stackblitz](https://stackblitz.com/edit/angular-ivy-b5hkjp) which reproduces the issue with any images which has a different aspect ratio than the one desired.

For exemple, with following typescript logo :
![500px-Typescript_logo_2020 svg](https://user-images.githubusercontent.com/10925994/104007844-dda70c00-51a8-11eb-8070-9f1af29bacfa.png), I get the following result:
![image](https://user-images.githubusercontent.com/10925994/104008041-278ff200-51a9-11eb-8a8e-f7e44cac2c4d.png)

Downgrading to `3.3.0` fixes the bug, it seems the split between the component and the service introduced the bug, when I step debugged it, the value I was using for `backgroundColor` wasn't passed down.

**Comment by Mawi137** [comment]
Thanks @justinrlle. I found the issue, fixed and released in version `3.3.3`!
