### ISSUE TITLE
Dont work in modal dialog with Ionic 5

### ISSUE THREAD

**Issue by 519818538** [Mawi137/ngx-image-cropper#394]
It works in a normal ionic page, but does not work in a modal
https://ionicframework.com/docs/api/modal

I'm using ionic 5 + Angular 10

I Have tried the  solution with #355.But it does not work.

**Comment by Mawi137** [comment]
You probably need to wait for the dialog to be open before showing the image cropper.

**Comment by 519818538** [comment]
Thank you for reminding me. I  have  solved this problem by import the modal component module into app.module.ts .Thanks for your awesome job again.
