### ISSUE TITLE
No support for Multiple files.

### ISSUE THREAD

**Issue by abhinavaggarwal8** [Mawi137/ngx-image-cropper#395]
If we have a requirement for multiple images upload this seems to fail.
```
//TODO--add
 @Input() fileIndex = 0;
//TODO--update
 private onChangesInputImage(changes: SimpleChanges): void {
    if (changes.imageChangedEvent || changes.imageURL || changes.imageBase64 || changes.imageFile) {
      this.reset();
    }
    if (changes.imageChangedEvent && this.isValidImageChangedEvent()) {
      this.loadImageFile(this.imageChangedEvent.target.files[fileIndex]);
    }
    if (changes.imageURL && this.imageURL) {
      this.loadImageFromURL(this.imageURL);
    }
    if (changes.imageBase64 && this.imageBase64) {
      this.loadBase64Image(this.imageBase64);
    }
    if (changes.imageFile && this.imageFile) {
      this.loadImageFile(this.imageFile);
    }
  }

```Just a suggestion.

**Comment by Mawi137** [comment]
You can also process the image change event yourself and use the imageFile input to pass the image. That's what happens within the image cropper as well.

**Comment by abhinavaggarwal8** [comment]
Processing Event throws the cycling error. And your cropper needs event. 
and if you clone event then also Node error will accour.

I have created a directive and have override it. 

It was just an advice so that i becomes a core feature.

Thanks

**Comment by Mawi137** [comment]
The cropper takes `imageChangedEvent`, `imageURL`, `imageBase64` or `imageFile` as input. As you can see in the code you posted, when you set the `imageChangedEvent` input, `loadImageFile` will be called with `this.imageChangedEvent.target.files[0]`. When you set the `imageFile` input, it will be called with `this.imageFile`. So, if you want to show a cropper for each file, you can take your  `imageChangedEvent.target.files` and loop over them, like you probably already do to know how many files there are. Then pass the file to the image cropper via the `imageFile` input and voila:

```
<image-cropper
  *ngFor="let file of imageChangedEvent.target.files"
  [imageFile]="file"
  ...
></image-cropper>
```

**Comment by shahmeet999** [comment]
@abhinavaggarwal8 Please share your directive code for that.
Thanks in advance.

**Comment by abhinavaggarwal8** [comment]
> @abhinavaggarwal8 Please share your directive code for that.
> Thanks in advance.

https://github.com/Mawi137/ngx-image-cropper/issues/395#issue-766828918

**Comment by shahmeet999** [comment]
Can you provide more information @abhinavaggarwal8

**Comment by abhinavaggarwal8** [comment]
> Can you provide more information ?@abhinavaggarwal8

all the info is in 1st comment please read angular directives you'll understand what and how to create one.
