### ISSUE TITLE
suitable image cropper version with angular 7

### ISSUE THREAD

**Issue by ashokkumarsam** [Mawi137/ngx-image-cropper#397]
Hi Mawi137,
   I am trying to build a image cropper for the user where he can crop, zoom in and zoom out. My angular version is 7.1.0. And I tried with multiple versions like 1.5.1 and more but not able to do that because I am getting some errors. So which version of image-cropper would you recommend with angular 7 in order to achieve crop, zoom in, zoom out functionalities.

Note: My complete application will be running on angular 7 and i cannot deprecate and upgrade it.

**Comment by Mawi137** [comment]
Hi, sorry I don't remember which versions of Angular are supported by which versions of the image cropper. The Angular team only supports Angular version 8 and up, I do the same here.
