### ISSUE TITLE
Controlling quality of image

### ISSUE THREAD

**Issue by BrsJsk** [Mawi137/ngx-image-cropper#40]
Is there a way to control the quality of an image? I know we can't really improve the quality, but can we decrease the quality? Does the cropper offer an option for that?

**Comment by Mawi137** [comment]
It does now ;) However, it only applies when using jpeg or webp as output format.

**Comment by shantilal-narola** [comment]
Would you please let me know what option that is? Thanks

**Comment by BrsJsk** [comment]
@shantilal-narola imageQuality

`[imageQuality]="92"`
