### ISSUE TITLE
Resize up and to the left when the crop is positioned at the bottom right

### ISSUE THREAD

**Issue by nicothin** [Mawi137/ngx-image-cropper#400]
Demo: https://stackblitz.com/edit/image-cropper

Make the cropped area at least 2 times smaller than the original image.
Move the croping area to the lower right corner.
Drag the left vertical border. 
No change to the cropped area :(

Expected Result: The cropped area grows to the left and up.

**Comment by Mawi137** [comment]
Yes, that is intentional. Feel free to work out the logic and open a PR :)
