### ISSUE TITLE
[maintainAspectRatio]="true" && [aspectRatio]="undefined" > throw

### ISSUE THREAD

**Issue by DerZyklop** [Mawi137/ngx-image-cropper#401]
If `[maintainAspectRatio]="true"` and `[aspectRatio]="undefined"` the cropper plugin calculates some NaN’s which causes consequential problems. 

It took me some time to figure this out since my aspectRatio value gets calculated. So it looks something like this:

    [maintainAspectRatio]="true"
    [aspectRatio]="calculateAspectRatio()"

There was one unexpected case where `calculateAspectRatio()` returned undefined. Then the internal property 
setCropperScaledMinSize calculates its value like this:
`Math.max(20, this.settings.cropperScaledMinWidth / this.aspectRatio);`
which is `NaN` if `this.aspectRatio` is undefined. And then comes the error from **crop.service.ts** that `getResizeRatio()` can not be executed with a height of 0.

I could have saved time if the plugin had thrown an error with the information that **aspectRatio is required if maintainAspectRatio is true**.

**Comment by Mawi137** [comment]
Good idea to throw errors in case of an incorrect config. I'll include it in the next release.
