### ISSUE TITLE
[Suggestion] Improvement of documentation for backgroundColor setting

### ISSUE THREAD

**Issue by marcelotedeschi** [Mawi137/ngx-image-cropper#402]
First of all, thanks for the nice work !

Secondly, I'd just like to mention that the current documentation about the `backgroundColor` setting is not 100% clear when it states that you can:
"Enter a color HashCode or one of known HTML color names (https://www.w3schools.com/tags/ref_colornames.asp)"

This directs the reader to think there are only two ways of setting this property.

However, according to the usage of `backgroundColor`, the value is applied to the canvas context using [fillStyle](https://github.com/Mawi137/ngx-image-cropper/blob/master/projects/ngx-image-cropper/src/lib/services/crop.service.ts#L23), which also supports, for example, a string like `'rgba(r, g, b, a)'`.

Essentially, "[any string representing a CSS <color>](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value)". More examples [here](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Applying_styles_and_colors).

**Comment by Mawi137** [comment]
Hi, just updated the readme to include that info. Thanks!

**Comment by marcelotedeschi** [comment]
@Mawi137 Awesome! Keep up the good work 💪
