### ISSUE TITLE
Loadfail error when using it with ngx-bootstrap-modal

### ISSUE THREAD

**Issue by syahirudean** [Mawi137/ngx-image-cropper#404]
Notice some intermittent load failure after opening up my ngx-bootstrap-modal. Did some try and error, I've noticed that as long as I open the modal before `loadImageFailed()` triggered. The cropper will load and everything seems to work fine.

I can't find the cause of it though, or am I missing something?

Hope to get some light on this.

Thanks in advance.

**Comment by Mawi137** [comment]
Hi, the image cropper tries to calculate the size of the image you're loading. If you don't show it on the screen, it can't and will give you an error.

**Comment by siovene** [comment]
@Mawi137 yeah, I have the same issue as reported here: #419. Any chance to get this fixed? Please let me know: if you don't have time I'll try to submit a PR.

**Comment by Mawi137** [comment]
If you have a solution, feel free to open up a PR.
