### ISSUE TITLE
Can we show image without cropper by default ?

### ISSUE THREAD

**Issue by angularteam402** [Mawi137/ngx-image-cropper#406]
Can we show image without cropper by default ? and image with cropper on click event ?

**Comment by AndrewBotsulyak** [comment]
@angularteam402 

you can simply add styles

<image-cropper
  ....
  [disabled]="disabled"
  (click)="disabled = !disabled"
  >
  </image-cropper>
  
image-cropper.disabled .cropper {
   display: none;
}

**Comment by angularteam402** [comment]
hii @AndrewBotsulyak & @Mawi137, I tried many ways to show ONLY IMAGE without cropper by default.. 
Im facing issue as shown below. Can it be fixed ?

I want ONLY IMAGE to display on load without blur action,
![req](https://user-images.githubusercontent.com/57127506/107110659-b60e9680-686f-11eb-8bee-9a0b4b7423b5.jpg)

after clicking crop( ), Can I get cropper like 
![actual](https://user-images.githubusercontent.com/57127506/107110543-a6db1900-686e-11eb-9617-aa761b55d58c.jpg)

**Comment by angularteam402** [comment]
hii @AndrewBotsulyak & @Mawi137, I failed to show ONLY IMAGE without cropper by default.

*required as 
[only image on onLoad] 
![req](https://user-images.githubusercontent.com/57127506/107935723-c6c5b780-6fa7-11eb-9fd1-06a8ac8b0bec.jpg)

[onClick can I activate cropper]
![actual](https://user-images.githubusercontent.com/57127506/107936025-21f7aa00-6fa8-11eb-8c3b-5b5060485af5.jpg)

Can it be achieved by onClick ?

**Comment by Mawi137** [comment]
As mentioned by AndrewBotsulyak, you can add a css style to your general styles.(s)css file which hides the cropper.

**Comment by IsaacHub** [comment]
Click event on a button:
```
<button (click)="disabled = !disabled">{{ disabled ? "Show crop" : "Hide crop" }}</button>
<image-cropper [disabled]="disabled"></image-cropper>
```

Hide the cropper by default:
```
disabled=true;
```

Style:
```
image-cropper.disabled .cropper {
display: none;
}
```
