### ISSUE TITLE
Interface `LoadedImage` not exported

### ISSUE THREAD

**Issue by merobal** [Mawi137/ngx-image-cropper#411]
`LoadedImage` interface is mentioned in docs, used by `imageLoaded` event, but located in the following file, therefore it's not exported. Can you please move to interfaces folder and/or export in public-api?
https://github.com/Mawi137/ngx-image-cropper/blob/dfadfd110777d3426f927175c6f06714ed184087/projects/ngx-image-cropper/src/lib/services/load-image.service.ts#L12

**Comment by Mawi137** [comment]
Hi, should indeed have been exported. Fixed and release in version 3.3.5 ;)
