### ISSUE TITLE
export 'ɵɵdefineinjectable' was not found in '@angular/core

### ISSUE THREAD

**Issue by VishnuRaja98** [Mawi137/ngx-image-cropper#413]
for angular 7, ɵɵdefineInjectable needs to be replaced with defineInjectable. 
Edit - checked the dependendencies in package.json -  it says @angular/core >= 8. So can 7 support not be added with the above change?

**Comment by Mawi137** [comment]
Hi, since the Angular team doesn't support Angular 7 either, so I suggest upgrading you Angular version.
