### ISSUE TITLE
Sometimes the image fails to load

### ISSUE THREAD

**Issue by Gurbii95** [Mawi137/ngx-image-cropper#417]
------------------------
Using version: 2.0.2
------------------------

Sometimes when passing an image file via **Input()** the cropper fails to load the image. Seems to happen at random. Uploading another picture and then re-uploading the original picture seems to solve the issue however still seems to be a weird bug?

cropper-component.html:
```html
<image-cropper *ngIf="image"
  (imageCropped)="imageCropped($event)"
  [imageFile]="image"
  [maintainAspectRatio]="true"
  [resizeToWidth]="cropperMaxWidth"
  format="{{ fileType }}"
  (loadImageFailed)="imageLoadedError()"
></image-cropper>`
  ```
  
 cropper-component.ts:
```typescript
export class DevicesSettingsImageCropperComponent {
  @Input() image: File;
  ... 
  }
  ```

so the file originates from a different component which then gets passed through to the cropper component
upload-component.html:
```html
<div class="image-upload__button" (click)="fileInput.click()">
  <span [ngClass]="{ '-placeholder': uploadedImage?.name !== undefined }">{{ uploadedImage?.name ? uploadedImage?.name : ('Devices.Settings.Placeholder.UploadImage' | translate) }}</span>
  <input #fileInput (change)="onFileChanged($event)" hidden type="file" accept=".png,.jpg,.jpeg" />
  <button class="secondary">{{ 'Buttons.Browse' | translate }}</button>
</div>

<div *ngIf="imageSrc" class="image-upload__preview" [style.background-image]="'url(' + imageSrc + ')'"></div>
```

upload-component.ts:
```typescript
  @Output() image = new EventEmitter<File>();
```

The image upload component emits the file to the it's parent component which pushes it into a behavioursSubject the image-cropper component is subscribed to.

parent-component:
```typescript
  setOriginalImage(file: File) {
    this.originalImage$.next(file);
  }
```

parent-component.html:
```html
      <cropper (saveCroppedImage)="saveCroppedImage($event)" [devices]="selection$ | async" [fileType]="fileTypeExtension" [image]="originalImage$ | async"></cropper>
```

**Comment by Mawi137** [comment]
I suggest updating to a more recent version :)
