### ISSUE TITLE
Cropper breaks if the window is resized while the cropper is not visible

### ISSUE THREAD

**Issue by siovene** [Mawi137/ngx-image-cropper#419]
The following function is called from `onResize`, each time the browser window is resized:

```ts
    resizeCropperPosition() {
        /** @type {?} */
        const sourceImageElement = this.sourceImage.nativeElement;
        if (this.maxSize.width !== sourceImageElement.offsetWidth || this.maxSize.height !== sourceImageElement.offsetHeight) {
            this.cropper.x1 = this.cropper.x1 * sourceImageElement.offsetWidth / this.maxSize.width;
            this.cropper.x2 = this.cropper.x2 * sourceImageElement.offsetWidth / this.maxSize.width;
            this.cropper.y1 = this.cropper.y1 * sourceImageElement.offsetHeight / this.maxSize.height;
            this.cropper.y2 = this.cropper.y2 * sourceImageElement.offsetHeight / this.maxSize.height;
        }
    }
```

When the cropper is not visible, `this.sourceImage.nativeElement` has `0` width and height, which causes all cropper coordinates to become `0`, so the cropper will just show a blank white content and the cropper square will be `(0, 0, 0, 0)`.

**Comment by siovene** [comment]
Same issue if I navigate to a page with a cropper, and it's initially invisible, but then I make it visible after it's been initialized. It being initially invisible caused the cropper's coordinates to be `(0, 0, 0, 0)`.

**Comment by Mawi137** [comment]
If you want to hide the cropper, it's better to use an *ngIf. The cropper needs the image to be visible, else it cannot calculate the position. If you really want to hide it with display none, I think the best solution is to add a new Input `hidden` for example. If true, add css display none style and stop handling anything that needs the sourceImageElement. When hidden is changed to false, call `onResize` to make sure the cropper position is recalculated in case the screen was resized.

You can set display to none while the image itself is loading, but once `imageLoaded` emitted, you should show the component. Example here: https://stackblitz.com/edit/image-cropper?file=app%2Fapp.component.html
