### ISSUE TITLE
How do I use it in angular that turns on the lvy function?

### ISSUE THREAD

**Issue by bluesiboy** [Mawi137/ngx-image-cropper#421]
![image](https://user-images.githubusercontent.com/9855885/112462822-76a6f580-8d9c-11eb-80ec-18d2fda6b589.png)

This likely means that the library (ngx-image-cropper) which declares ImageCropperModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

**Comment by Mawi137** [comment]
Did `ngcc` run correctly to compile the image cropper lib?

**Comment by bluesiboy** [comment]
> Did `ngcc` run correctly to compile the image cropper lib?

thank you, i try to delete `node_modules` and reinstall package. now it's ok.
