### ISSUE TITLE
Set resize algorithm?

### ISSUE THREAD

**Issue by dglaan** [Mawi137/ngx-image-cropper#423]
Hi,

When resizing an image, is there a way to choose the algorithm used for scaling? Images seem very 'crisp' after a resize at the moment.

**Comment by Mawi137** [comment]
Hi, I suggest not setting `resizeToWidth` and `resizeToHeight` in this lib. There should be other libraries that take base64 images and do a better job at resizing them :) Let me know if you find one you like, might add it to the docs.
