### ISSUE TITLE
ImageBase64 not displaying

### ISSUE THREAD

**Issue by Axelvdbl** [Mawi137/ngx-image-cropper#426]
In my HTML file : 
`<image-cropper [imageBase64]="edit.base" [maintainAspectRatio]="true" format="png" (imageCropped)="imageCropped($event)" outputType="base64" `roundCropper="true"></image-cropper>`

edit.base is a correct base64 image but it never displayed.

config : 
`"ngx-image-cropper": "^3.3.5",
"@angular/core": "~9.1.6",`

**Comment by Axelvdbl** [comment]
I just found the problem, ImageBase64 not displaying into a modal Page

**Comment by farshadhemmati** [comment]
It was working in version 3.0.3 but it isn't working in the new version :(
