### ISSUE TITLE
Feature request : Adding viewport size

### ISSUE THREAD

**Issue by marcsloche** [Mawi137/ngx-image-cropper#429]
It is possible to specify the size of the viewport like Croppie? I have a small cropper size of 150px X 150 px, so when playing with the zoom with bigger image, there's a lot of blank space. So it will be cool to autosize the image to the viewport, 225 px X 225 px by example.

**Comment by Mawi137** [comment]
In this image cropper you move the cropper and not the image so I don't see how that would work.

**Comment by marcsloche** [comment]
Ok thanks
