### ISSUE TITLE
Cropping frame does not move smoothly on Google Chrome

### ISSUE THREAD

**Issue by IevhenIkonnykov** [Mawi137/ngx-image-cropper#43]
Hello.
Unfortunately I tried to implement your example code and I experience problems in Google Chrome Version 66.0.3359.117 (Official Build) (64-bit). The cropping frame does not move smoothly, it jumps in small steps. I have to mention that at the same time it works smoothly in Microsoft Edge.
Is there any ideas what might be the problem?

**Comment by Mawi137** [comment]
Hi, are you still having problems with this? I don't have any issues with Chrome 66
