### ISSUE TITLE
found version 4, expected 3

### ISSUE THREAD

**Issue by kd82** [Mawi137/ngx-image-cropper#433]
Hi All,

I am running into the build issue when I try to build the application after installing the library.  Please find my dependencies below:

"dependencies": {
    "@angular/animations": "4.2.6",
    "@angular/common": "4.2.6",
    "@angular/compiler": "4.2.6",
    "@angular/compiler-cli": "4.2.6",
    "@angular/core": "4.2.6",
    "@angular/forms": "4.2.6",
    "@angular/http": "4.2.6",
    "@angular/material": "2.0.0-beta.2",
    "@angular/platform-browser": "4.2.6",
    "@angular/platform-browser-dynamic": "4.2.6",
    "@angular/platform-server": "4.2.6",
    "@angular/router": "4.2.6",
    "angular2-modal": "2.0.3",
    "angular2-toaster": "2.0.0",
    "copy": "^0.3.2",
    "core-js": "2.4.1",
    "enhanced-resolve": "3.3.0",
    "hammerjs": "2.0.8",
    "moment": "2.17.1",
    "moment-timezone": "0.5.11",
    "ng2-ckeditor": "1.1.5",
    "ng2-completer": "1.5.2",
    "ng2-date-picker": "2.1.1",
    "ng2-datepicker": "1.8.3",
    "ngx-image-cropper": "^3.3.5",
    "rxjs": "5.4.2",
    "tinymce": "4.5.3",
    "ts-helpers": "1.1.2",
    "typescript": "2.4.1",
    "zone.js": "0.6.26"
  },

WARNING in ./~/ngx-image-cropper/fesm5/ngx-image-cropper.js
363:53-71 "export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./~/ngx-image-cropper/fesm5/ngx-image-cropper.js
985:58-76 "export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./~/ngx-image-cropper/fesm5/ngx-image-cropper.js
1282:64-82 "export 'ɵɵdefineInjectable' was not found in '@angular/core'

ERROR in C:/root/360/Main/WebApplications/MainApp/app/angular2/node_modules/ngx-image-cropper/lib/component/image-cropper.component.d.ts (26,14): Type 'ElementRef' is not generic.

ERROR in C:/root/360/Main/WebApplications/MainApp/app/angular2/node_modules/ngx-image-cropper/lib/component/image-cropper.component.d.ts (27,18): Type 'ElementRef' is not generic.

ERROR in Metadata version mismatch for module C:/root/360/Main/WebApplications/MainApp/app/angular2/node_modules/ngx-image-cropper/ngx-image-cropper.d.ts, found version 4, expected 3, resolving symbol LobbyModule in C:/root/360/Main/WebApplications/MainApp/app/angular2/src/app/Lobby/lobby.module.ts, resolving symbol LobbyModule in C:/root/360/Main/WebApplications/MainApp/app/angular2/src/app/Lobby/lobby.module.ts

**Comment by Mawi137** [comment]
This cropper supports Angular 8 and up. You are still on Angular 4 :)
