### ISSUE TITLE
2nd Loading the same file not loaded, unless try a diff file first

### ISSUE THREAD

**Issue by TLKG** [Mawi137/ngx-image-cropper#434]
In my app users are given a "Reset" option. For example, after loading a wrong file, so this reset will enable them restart the loading process without navigating elsewhere then come back:

```
Restart()
{
        this.fileChangedEvent(null);
        this.imageChangedEvent = null;
        this.ContentOfImageBase64String = null;
        ...
}

```
Click on _Restart_ then _Load from a file_ button, select the same file, nothing shows in the cropper. Breakpoint inside fileChangedEvent() shows it's not triggered.

Temporary workaround is to select a different file, _Restart_, _Load from a file_ then select the supposed file.

**Comment by Mawi137** [comment]
Hi, that's because the file input doesn't emit a second time, you should reset it's value as well in your restart method.

**Comment by TLKG** [comment]
If `this.fileChangedEvent(null);` won't do it, can you show how? Thank you

**Comment by TLKG** [comment]
Tried the followings, same.
`this.fileChangedEvent(new Event('change')); // or ({path:null}) or (null) won't do it.`

**Comment by Mawi137** [comment]
It's the actual value of the `<input type="file" />` that needs to be set to null. You can use a ngModel for example.

**Comment by dnbo** [comment]
Just set the value of the input to `null` on each click and it will work.
```

<input type="file"
       #fileInput
       (click)="fileInput.value = null;"/>
```

**Comment by TLKG** [comment]
Works out beautifully, thank you!

On April 23, 2021 at 4:41 AM, Daniel B ***@***.***> wrote:






Just set the value of the input to null on each click and it will work.


<input type="file"
       #fileInput
       (click)="fileInput.value = null;"/>

**Comment by TLKG** [comment]
Solution resolves it.
