### ISSUE TITLE
SSR reload show Cannot read property 'ɵmod' of undefined

### ISSUE THREAD

**Issue by wilson-young** [Mawi137/ngx-image-cropper#442]
I deployed my apps that use ngx-image-cropper or import ImageCropperModule in my lazy module route
`{ path: 'some', loadChildren: () => import('./features/some.module').then(m => m.SomeModule)},`

`import { ImageCropperModule } from 'ngx-image-cropper';
@NgModule({
  declarations: [
    SomeComponent,
  ],
  imports: [
    SomeRoutingModule,
    SharedModule,
    ImageCropperModule,
  ],
  providers:[
    SomeService
  ]
})
export class SomeModule { }
`

it's working fine when we redirect them from the homepage or other pages in applications. but if we reload/refresh the page in that route it will hang and I check on the server there are error Cannot read property 'ɵmod' of undefined
is there any way to solve or fix this problem?

**Comment by Mawi137** [comment]
Hi, I have no experience with SSR so I have no idea to be honest..
