### ISSUE TITLE
"settings.cropperScaledMaxHeight" not update when "maintainAspectRatio" changed

### ISSUE THREAD

**Issue by hoangduy1508** [Mawi137/ngx-image-cropper#443]
In begin, I set "aspectRatio: 191/100" and "maintainAspectRatio: true". Everything is okay until I change "maintainAspectRatio: false" by click button. I expect I can crop to any ratio for image, but it's not. I can't crop to full height of image because "settings.cropperScaledMaxHeight" is not update. It's complicate to explain because my mother language is not English.
At summary, I tried to read the source code of crop module and fix this. Just update CropperScaledMinSize and CropperScaledMaxSize when "maintainAspectRatio" changed in the ngOnChanges() function

`if(changes.maintainAspectRatio){
	this.setCropperScaledMinSize();
          this.setCropperScaledMaxSize();
}`

**Comment by hoangduy1508** [comment]
`
if (changes.aspectRatio && this.imageVisible) {
        this.resetCropperPosition();
        this.setCropperScaledMinSize();
        this.setCropperScaledMaxSize();
    }
`

**Comment by hhristov-tsd** [comment]
Hey Guys,

We have also faced this issue in our project and are happy to see that it has now been resolved. Will there be a new package version release, which would include this fix?

Thanks,
Hristo

**Comment by Mawi137** [comment]
Hi sorry, must have forgotten to do so. I just released version `4.0.0` because I also dropped support for Angular 8.
