### ISSUE TITLE
Load cropper positions relative to the original image

### ISSUE THREAD

**Issue by blitzmann** [Mawi137/ngx-image-cropper#445]
Great tool, but I'm requesting a feature to be able to load cropper positions based on the original image's dimensions vs the displayed dimensions (as it currently stands). 

My use case is simple - I'm sending the `cropper.imagePosition` (cropper positions relative to original image) to the server when editing an image, and the server is doing the processing of the edit. I also save these positions to the database. I do this so that I can load the images again and have the same settings, but since I'm saving the positions relative to the original dimensions, I'm not able to directly set the cropper. Saving the cropper positions relative to the displayed size doesn't make much sense, as the displayed size can change based on various UI considerations (browser size, future tweaks to layout, etc) which would nullify any stored values.

I've worked around this by doing some funky (and slightly inaccurate) math utilizing a percentage reduction between original size and displayed size, so that I know what I should reduce the cropper positions by. But obviously, due to floating point and percentages, this gives slightly inaccurate (but in my case acceptable) results. I'm wondering if there's a way for the component itself to have better access to these variables.

Here is the rough code that I have:

```
    /** When the cropper first loads, this is the initial cropper position *relative to the original image dimensions*. This is loaded from the database */
    initialCrop: { x: number, y: number, width: number, height: number };
    /** initialCrop then gets converted to a CropperPosition, which is *relative to the display size*. This is what is fed into the image cropper via [cropper]="initialCropper" */
    initialCropper: CropperPosition = { x1: 10, y1: 10, x2: 100, y2: 100 }
    
    cropperReady(cropper) {
        if (this.initialCrop) {
            let widthReduction = ((this.loadedImage.transformed.size.width - cropper.width) / this.loadedImage.transformed.size.width)
            let heightReduction = ((this.loadedImage.transformed.size.height - cropper.height) / this.loadedImage.transformed.size.height)

            // convert save x,y,width,height to x1,y1,x2,y2
            let savedCrop = { 
                x1: this.initialCrop.x, 
                y1: this.initialCrop.y, 
                x2: this.initialCrop.x + this.initialCrop.width, 
                y2: this.initialCrop.y + this.initialCrop.height 
            }

            // reduce the crops by the percentage reduction
            let newCrop = { 
                x1: savedCrop.x1 - (savedCrop.x1 * widthReduction), 
                y1: savedCrop.y1 - (savedCrop.y1 * heightReduction), 
                x2: savedCrop.x2 - (savedCrop.x2 * widthReduction), 
                y2: savedCrop.y2 - (savedCrop.y2 * heightReduction) 
            }
            
            // load the cropper positions into the image cropper
            this.initialCropper = newCrop

            this.initialCrop = null
        }
        this.loading(false)
    }

```

I might be able to provide a working example if needed.

Is this something that can be integrated into the component?

Thanks!

**Comment by Mawi137** [comment]
Hi, there will indeed be those rounding errors depending on how much the displayed image is scaled down. It's probably easier from within the component, but you should be able to achieve the same with what you're doing.
