### ISSUE TITLE
Crop sizing problems

### ISSUE THREAD

**Issue by kilavila** [Mawi137/ngx-image-cropper#446]
Hi, I have a small problem I can't find a solution to. Some of our users upload really high res images(6000x4000), so the cropper won't span across the image.

![image](https://user-images.githubusercontent.com/79692462/119792297-e12bfd00-bed5-11eb-95b0-fcd172acb686.png)

I have tried setting max-width to 100% on the cropper, and also tried `cropperMaxWidth="100%"` but this isn't working.
Is there any way I can get the resizer to span across the width of the image or do we have to downscale the image somehow before cropping?

Any tips on this would be much appreciated!
Thanks

**Comment by Mawi137** [comment]
Can you post the whole config? You should leave `cropperMaxWidth` empty to achieve what you want.
