### ISSUE TITLE
Feature Request | Add aspect ratio as a range

### ISSUE THREAD

**Issue by Heatmanofurioso** [Mawi137/ngx-image-cropper#450]
It would be a really interesting quality update to allow the aspect ratio to be a range between 2 values.
A sort of minimum, and maximum aspect ratio.

This would especially be useful for banners

**Comment by Mawi137** [comment]
Sounds very complicated as well 😅

**Comment by Heatmanofurioso** [comment]
Limiting the crop area between 2 values instead of locking it on a specific value/allowing free range?
Not sure how you have the current functionality implemented too, but the idea doesn't sound too tricky to me 🤔 

I can try and see if I can make a PR for it, once I have some free time. Haven't looked at your code, but if you lack the time, or think that this feature idea isn't worth your time, I could give it a go.

If you think it's worth having, of course 😄

**Comment by Heatmanofurioso** [comment]
Ping...

**Comment by Heatmanofurioso** [comment]
Would be nice to get some support on the issues in here
