### ISSUE TITLE
Some Bootstrap themes are conflicting with the class "overlay"

### ISSUE THREAD

**Issue by Gabr13dev** [Mawi137/ngx-image-cropper#452]
I'm using the AdminLTE theme in version 2 and when using ngx-image-cropper it conflicts with an "overlay" class used in the selection component and in the bootstrap theme. I solved rename this class for "overlay-cropper"
If this is not an error or misuse on my part please let me know

With conflict:
![image](https://user-images.githubusercontent.com/58440817/120850196-7c177d80-c54d-11eb-966b-f1f151429c26.png)

No conflict
![image](https://user-images.githubusercontent.com/58440817/120850373-b97c0b00-c54d-11eb-95fb-f5f4b0cccbc4.png)

**Comment by Mawi137** [comment]
Hi, unfortunately changing the class name is a breaking change because some users overwrite the css of this component. SO I'm not sure what would be the best way to fix this.

**Comment by JensSpanier** [comment]
Would it be possible to overwrite the class name via a component input?

**Comment by Gabr13dev** [comment]
Actually, i take the overlay class off by using a javascript selector. At the moment, it's the only solution that i found and it works very well, but it isn't a clean option.

**Comment by danielfsc** [comment]
A simple solution is a refactor in css. Just rename all css classes' names by adding a prefix. For example: 
overlay  to ngx-ic-overlay

**Comment by Mawi137** [comment]
I changed all css classes to have the `ngx-ic-` prefix as suggested. Will be released in version `5.0.0`.
