### ISSUE TITLE
Programmatically load an image and open cropper

### ISSUE THREAD

**Issue by stsomewheredesign** [Mawi137/ngx-image-cropper#453]
I'm (sadly) having to rely on a Kendo control for image uploads. Because of this, I am unable to attach a `(change)` event to the actual `<input type="file">` element and there's no easy way to find a reference to this element to inject the `(change)` event.

The Kendo wrapper does fire a select event and I do have access to the image, so I'm wondering: is there a way to automagically populate the `imageFile` and pop open the cropper?

I've already tried programmatically writing the value of a reader into a local variable of `imageFile` and added that as a parameter to my `imageLoaded()` method but the method does not get triggered. I'm certain that Kendo is to blame for all of my misery, I'm just trying to find a way to circumvent their garbage and get your component to work.

**Comment by Mawi137** [comment]
When the kendo FileSelect emits a select event, you should simply assign the first file to a variable and pass that to the `imageFile` input. Something like `this.imageFile = e.files[0];`.
