### ISSUE TITLE
Output fileURI instead of base64 string.

### ISSUE THREAD

**Issue by Evanzsnr** [Mawi137/ngx-image-cropper#457]
My question is, is it possible to have my output as a file URI instead of a base64 encoded string?

**Comment by Mawi137** [comment]
Hi, I think you should be able to do that with what is given back by the image cropper.

**Comment by littletof** [comment]
To get an image file from the base64 string, you can use the code below. 
It should convert `base64` to `File`, you can use it with the `imageCropped(event: ImageCroppedEvent)`'s `event.base64`:

```ts
async base64ToFile(url: string, filename: string): Promise<File> {
    // https://stackoverflow.com/a/38935990/1497170
    return fetch(url).then(res => res.arrayBuffer()).then(buffer => new File([buffer], filename));
}
```
