### ISSUE TITLE
How to make the cropped image same format as image upload instead of base64 format?

### ISSUE THREAD

**Issue by drake4964** [Mawi137/ngx-image-cropper#46]
Hi, here is my image file format,
![image](https://user-images.githubusercontent.com/7411958/39422347-8a78d36c-4c9f-11e8-876a-4068383846b6.png)
and below is my cropped image format
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAVUAAACqCAYAAAAdv9xWAAAgAElEQVR4Xty9aaxl6XUdts483Hm+981jvZq6q4rd7GY3KbItShQpypYRBIgRQA5sI7AiJ04iIBEMOYYD5EcQwEgMyQkS25ApR7IlO3ISSY4kRpya3WQPrGJXd3XN79Wb7zyeeQz2vnVbzabg/K8DFN6r9+6759xzvm99a6+99v4EPEPHf/BXrqVymsJIAVlIkAgxIqRwY/qBiGzGREHRoSbAJPBQKpeQyWbgBz6C0EeqCEhi8L/JeIr2eRcedIiCAEkRkaQJXM+BECb8XlnDhCikiKIAcURfYwACVEWDJMtIIcALAnieC1ESEEUhisUsgmgKpAI0RUcaJ0hjIFUUqLqBOEmRQIRlO0gnMRzPQZqmSERAVVVkdBVxFEKVRIgpvVLg6zcME57n8dOM4wiSKkJWReiGAU03+Hq0jIFYSKCrOgrZIkRJQpoI0FUDlmXDchxks3mIsoQ0DBBGKiazELbjQZAECHAQBw5C24IYCgidGMdPzlEsFjCdzrC21oAkAbBHqDYzePELl/Dqlz+H6vISHMuC59nIFmtwHRn14jY818bp6X2cHbVx+KCNW99/hAd3DyEpNlw3AEQZcSwgTUU4foCQHoyYQpcUaKmAWehAURTUqhX+7MVSEa1cCa2lVZi5CsaWDy9I4KQxhqMRjk+OMR4PMZtNMbNthFGMFCmiNOFnK8oykiQBBPqsAoCU76cMuob5RBHox/SMRYHHBf8gTfkZpXTf+IUpBEGEJEn0lzwOBEFGmtLrJUAUIYgiZEGA7ztQJAmKKML1fISqCFFV+Jy6qkCVUiSeDSQedi9tY2N3A5qoQVElSKqEldUlhEmIfL4MRVb5PIIgQRRFiKKBfq+DpVYThZyJyWSMTEZHHKeYTh24QQRdyyCXL8IwNCShCwk0lh3YzggPHn+I566/gG5/imy2BNu1oOshOp0OcrkcSqUifD+AbTtYWl6G69DfOZhOJ8hlc5BFEeP+AJokQxKAQq0Bz/MhqSomlgPfDyFEAd+hRJQxGo+RiBJc10aKGIHvIp8xoIgCup0+hFRCpVKBABGaruPs5Ay1cg35QgGSKGE8nsznqKjwXEmiCJEf4ntvvolMvoRqsw5BkSFqCkRFRj4QkMtk4DozWOMJmo0qsvkCzjptNFaXISgK7j1+hMu7m7i6t4dyqYb/+lf+DjRFw96lS8gXcvjg7h08OTrAxtYGGq0mtCzNyGfo+Ot/4+WUJgWNaxpUBGIEaoquwdCzsK2AvzbrLRiOj1wpAzWjwk892P4MERwIiYiH9x5DkwxYUxdtaEASQUojaGIKTRGhhSFURYGmaXz3oihCkgqI4wRRJECRTWSMHERJgePYCAIHUexBVgQYWR1O7PLklWWZQYEm4sgaIJcr8MQjgJ5MppCFKg/QNI2RyRpQVRmKGEKIEwhJitB2kTezCKUYrudBEIQ5KADQNJk/t6IZiGlyqxoyuoKMJsEwihAkA1EsQdUzkBQV7mwKy5pBTGPomgprMANEAX6UIAxTEFomkQ/P9eHbHkI/QhwmmPR9yLIEIQ2QMRTkciYurdfwaP8urrx4Ab/wi7+AJ2cPsbm7ASHx4Xa6iNwERrYJSdZx3u5icG6h3/bx+jfewcGTM8xkB0kU82cU6VkKAiJamBQNThAhEmSEEWAIPt/7VquOMAp4kpcKBZSrNeh6HpJq4I033sL69iZG4yHOzs4xHo9h2xYsN0Cc/tn9omfACxoB6hw5f+zrx6eKIosfvWbx+iimRXV+0PgjUBUFCQndPllFQO+fAAb9nIGawFeYjyNRRBBG87GUJPxzSQQEMUKchNAyOurNGqrVMtZbZXi+DcOUIcvApct7MPQictkCZFmFJMkI/AiTiY1yuQhFkVCuFPHuu+/g8pULfF2O4yAMwznwJxJ0XaeRDFGKeaz2Rz2eE4auY3d7B6eHxwjDAJAlnJ6eIo5jLC0tod/vY3V9B7Zt8zVPJhP+7DM5hm9bcEYjNApF5E0DlYIKy3Jg2S7MXAFBFCEXmxgNR6g0G7ADD8PpBKV6gdZTRIEP37EwHvYRBgGiMEK5XMXJ8TkqlSrfyxAKZElGrdbAW2+9y4vr8vpF/mytVgu9Xg/37t2DourY2NoELaOCJEEiUBVlSJIAWUgRuC50TUGjVsdkOoOfxNAyWbz59ru49uIV9Pod9Hp9TMbzz7m1sYPRYIJutwvXdflZfubVV5DotOQ+Q8cv/iefS2VaiXi1cxEEAbMx1TChyDriCFAUE/lsHstmjlf6WI4QpAEihOgPTpExsnh0fx+nRx2US3kMRRMiEmgiYCiArkiIZzMGQ5oMdINpgEGMEMYRAo8mlgxVMZkFEHOglTcIXEgSsUcJ08Cas8+nwErvEyKEpukQIGE0mkISZXgzicFClgWYpgFRAjQpYWY0m0xBPIiAR5AFRHHE10QHvTcDsE4rsgY/TSFpBnKmBpPYq06D1mRQhaAgJQAgVpYmCFwbnutApt8xqKZwHB9eGCIJA9iWjdANgURCHM4nPDGKmBi5a1NAgKKa5YkewkV5qYT/4r/627hz/7uoFWWkloX2YQff+Nbb+Kt/42/hyVkH02EA3xLxx3/4bfT7E0zjCbM4/nxM/FJEXgBZNzB1fISpiDABNDHgz1sqFWAYKoqlAgPK6tomppaHJJHwre+8gZ1LF9DrdRlQafEhAPCjGH4Y872iMULnoEVREKWPFiYGHGEOfp88ZElg8KDfz1mhCM/3P3rt4neKLCOKE8iqziBO3xuyAkJa+lt6ZvxaeriCyGCwANY0iSGKCbNzyCkKpQLK5RJ0MYAk0zqX4PKVXXzqhRsw9DwK+RIvygktuEHM44kWPLqJBB5nZycolcowDIPP6fs+LMuas1tRYICWZOKNIVIEUDQBw/4AN99+F5vr6xiNRxA1FdPpFKurq/xZ6/U62t0RzwECZmKI9N6d0MKw00ZWVVHSDeiyBENOMRpP4XkBqo0mAvqbQOV7ki0VMLKmSCURI2sIVZN4vBHQmUxeElhTC47j8cLebC7z/VLMLMajKWRZ4fnd7fZQbC7h8YOHINRN4gSh5+PRo33c+NQNmPkcYooqkKJVqNAQh5BGcG0bCq1iaQrdNHms5cplHJ6eo1TPMXM+OHiCe3cfMVDnskWUCxX+3KPRCDs7O1hZXUG+kn+2QPVX/5ufSwmg6KHSBKIBqmg6FI3CdIVibMiSBl0z0MqWEIsxvMRFgIBXxtdf/waeu3oVGU1HtVTCW299DzOxwOxNTiMoQgxFSBG7PhT5R0FV0HwEsQdr6jFb1VQThpqFLKq8etJA4MkjCfCFkAckTZ4FU6HwnkKpKEoxGk45vAodkiNiKKoM01QZKHMU/scxBqMhg3qcJPCsGT9IGtR0DjqCwIOZM6GbOQwtC6Kmo1kroZg1oCgZQDSQpAqiROB7hIiYzQiuRdJEgkaxjiHdwwSIE4HD5fFgyAM7CVLIkoIkSjD1ziCLEjKGiciPkMYx1CjD15KKCcrVIuqNCr7wpT3o2gyj41M0S038X//3nyIQyvjCV76I0BMwGwf4oz/4U/Q7Q+gZidk4AQ8xOvpEJK2Iisqg6icCQpJpEovZviyLqNZKyGRMZLJF1JtLuP9gH2a2hJu33kOlWcdgOGAwpXvHzILYLzPHObOnn88jHInZ2//fQfOPzr1gtPT9AlQXIEzPlkAhiEJmSolAckYCWhe1p2AahhE/M1nRWBr4EQBnWSFCGIUQVXpOMkQphRS7ME0N165fwfbOGl566UVIkgpDzzBg8eKA+WcgmYCiJWKf9PlbzVU+HxEOAtVMJgNRUjl0ptfEicfnrNbyaLcPcXZ8gqxuYDgYIFcoIJYEBs5sNotqtcrvc94Z8uJA70WATaAT5lQoSDHp9aDQAmZbaFWqvHhEJMeJMgbjMWI7+ohBdkZ9ZoiqoSGXz0IUaPBFyJkGqyzTyRSu6/HnlCWVF5CpZaPX7aFcriOTybJM4BsiBt0eKtkC7PEEo14fnbM2di7solStMEulxbVVXoIiSxDTCNZ0CoGEN1HE9oULGFkWYkHEzPWRLxuoNap8X3/7t34Hy8srOD/tYHtzl+8xsXX63Pl8HsvLy88WqP7DX/trKd0UmiA0gAi0KASXNROSqCIMwQwyny2gnq/w6m+HFqzAYv01DXwMBl3kMgasyRCCkKI9Id0ygSIkUNKIv58NJxxyLJghgXcgWAjiAEEQQxQIuDNQJRkaraAxEPoU0kmI0hShOAdVAkWajHSdkqZhPJ7CtlxEEU0KEXIksV6bEKjLxCQkmLKMTD4Px3cxmI5hZDLQiPXQCquTXhY/ZToh9IwJPZOFRYxd1VAtFVDM6kgSBQlUQNAQhAm/JvZp0s0gIUHGNOGMbMxsC25I75fCD0OM+mNYUxsescCIzikg0cYgwTfyY0T0GRMBOT3HId362gqiMIQsidi+UcXKqokLyyt4dOchNKOG7751C1tXLmOttYnxwMK7b9/CyeEpqlmNGSoRNCLQc3VTYqZnexEtgbDdAKns8WAOQw+ra8t8f2SNmAjQ7gwhKwYGoymcwGUtnPQ8eicC6DAlBig+XdxCWkfmIfdHeqTIgLsI0T8JsqSl86IWx/w6Ahpa4Oj7j/+drknww4BBFTItiCkix2NQpWdPf0/jiK6VPuNCSmCwf6rPxkkEgfR+xIjCAHlDwMbmKl544XkG1mIpz5q6KMgMqnTHSCuv1Sss6fQHXWbyo9EA5dIyj480mbM1WrwhqhiMBrCsMSBE0HQJuppCSgMeV4amsTZ5cnYKOwn5b1ZWVjj0LRQKsJyQwYjApdFo4PDwEK4h8lg9fXKA1HFhKDJWGyvMKIOQdOwU3f4A1WIFuXweM9/FWa+LaqOO2nIDs+kEpqFB5SgiYvCja/a8ELOpxZr72uoa2u02giBCo7HEUVS5VMF3H9zCkwePcePiZYh+jFl/iH73nK8tVyxCUolMxMjIRWQMHaoiMqjGYYBas8HafbleZyJy8/YH2Lu6DVkRsb//5KPciTVzoSsGP2uSQ3Z3d1Gr1rDUXHq2QPU3vvafpzRgiBkS0PHghgBZy0KRNTh2CF3PolapQ5cMSJqImTdGfzqAF7mwhyNY1gTNegmGJsE0VJwP50AqJAHEyGd91RrPGFRpUtA5aLUeOn34cUgpDGbFAmk9QoqcIUMSNcQRJTQU+FEEN3H5+mi1p4N0qEyhiOFwgulkBk3V0e8PsVJpzueyEDPAU7KrYGYwGI2QLxcRCAlG0wnKigZFkvn9CATovUmH9WOSP1QoxEZUDcW8iUalCM9LEcYSRMmAHybMVJ3pFFHkswwgiQISN4aiqWj3huh0+iBRIwnAA3rSH8GxPYBYbt6HImlwZj6SUAAiEeNRH6tLdTzab+O5vXVO6PnZKTJF4D/69/59/Mkffh2bW8/jG995A3bg4ud/7i9Dk038H7/7eyjlSrC7ZzAUle8xyRvE1lNB5ZDdCRMkooLR1EYo2swOXNfCzs4Wh7kjy8f5+QhmLotOdwgzW0B/PJgnpGjxIj1NkjgpR1oFgVgUhIzciqLSrf6ILS7Cf5Z3PnEQUyUgpfek33PYK0n8/Zz1ziUDXSdZIICq6xBken0KiYCXgC1NeQzNgVSBJBv8/8V5aUEiLVEhtpuEiJKAw/i8LuC55y/jJ7/4E6jVyqhUi8y+VYXCfZUjMQJvP3A4OeV6M2bx9LeikOOQmBI+tCjQ2ItJovJdzKwJTFNGpVpA9+wJttebCH0fnfM2Ctkc3r35A2xc3mMA/frXv46f//mfZ3b6zW+/yayVrp1AbmtrC2MhwKjbgTUcwhmOsLe9hdCK4Tguz8lacwmuH6JaqUBWFaSKBI/id0nE2J7x+xRovFarcB0LukKkKITr+ixrPHywz+C+u7ONwCcS5WI8GjNxuT89gTOa4NrORYxO2qhk89h/cBfNpRYvwpS81k0DoS2hkMshY6iwZlOEvgdJU9BcXka2VAJkBd/67pt48ZXr2N7ZxM2bP0S/N8SDBw/xpZ/+CjJ6Fm+88QZee+01joxJf0bwjGmq//p3/l5Kg4tWGtXQOewi8T9D+qmkI/QpHMszWyWB29AEBOEE7fMDnJ0e4MrzF3lwkkZCTJf0phdffB6nxycwdQOR58O2LIRCxAysUi5gMhwiDFwoognXDZEQeAoiJyhUVYOuG8w6ZzObfybrCrqzQ1gzh7XKfL7Ag8RzEiiKhtnM4SQDTczADZHPZRCFDnIZHWkSoFarYGI7COIEfgqMZ1NoKVCrlHnSeNYUy0st1kkpm8xZf1OfT2pFARkUKHSSEoWTaYaRhTP1YQc+IiGFF4eYOTaDcuj4SCl7PrEReaSdzhNoxIYm4xnrW3E4T7rRwckZYt5ySAIEEt/Fqy+9jM++/ALkgoHhpIdkMsZnXngZuUITb77zPv7fb34XX/3yV5i9/dHv/yEnzLayCjRDZ003fMoWI09EKshoD0YQNAOTqQNHGDNTe/vd93kiVCsNlOtLeOPNN/nZ0SJHiYmAmL8wj2A4eqFo5mMsdCHDkB5Lr/vzjoX+vdDQiakS+HHWnzRr+v7pH7K++jRxSJLmXHOljDwttiIUBu4EoUBZb4F1REmiTL/GX1PSgiByRpuy2UlCyasQUUyJVh2NkonVtRYuX9lBvVmEIMQoN+rI54vMUGk8uSSThFPWP7e3t/krXXvnfMyASouAaZp8P5yYtHNiqMSYU0xnQ0yH51hrFnBydIyttXXO7FNyyA9iDu+JpRI7IzAhKYXYKYW+xLrpPN9//xaWlpronp8yOVlqteB1x8gWCgjJBaGoPEcjZrkyWuvrcIIQtkfyToDheIB8NgtSAKrlCh4/fshSBkkR79++jUa1BtMg506MUqnE/2jOvv/++yhuVPHm699FXjeR1QzWVE/utbGzu4lcJQNBTJEvZ1ESmsjmMghClyUSOlm93uRIsN5aRqZUwhtvvQ3LmSAMfR4/ly5d4oWIkmYf3rnLksDW1i5azWX+uSY9Y9n/3/tXfz+lyURZbwp9Hd97qpERe1ShKTkocgaOHcCjzLccQ5IDiIKPwJ8hjCweZHQcHx/zZGhWSjwB6XsS7VlaCF1sbKzDs8lionKIYo0TOFbID4fsMhRO0oSgmUb2DxEyxqQJ+TaKLRW27SEKk3nYJkoYDW3WKc/PO8xYKVGVyRagkXUmibDUqEJEDC9wOJucygqIF49nM6RRhGI2C01VOFlUqxTnr6FwViLJIUG2kGdgncwcaKqBUrYCTTHZPiYkMmIRGM6mnCwgIKKw0R7PEHsR/JnPg5vuG1mvwiCB74X8PQ0q0hIDP4AozvW2SPKwslJFKafgyqUN/NRrn8HahT1oqoasJOF7r38fxcoqnnvhc/jGN19HEkbwphZ+97f/BRI/QDZw2B5VqddgZEn/FXByeA7HCyBIGs7afb43HesQe5d2MRpbCGNye6RYWtvCwZMnHJJRiO+FPkBaZpLws/tkpn4BkouEE4HZj4X6T2WCRfKJJQHMw/xFkop/9vR1dM9Jr6T3JNmGeCgBB/2j54qn2jPpk6kszkFVlCGLpPnPtUIGVYlsWHTdFHXFDAaUsCzoCmESlpYr2N5dw9paC83VZRQLZV7wSOaYTW0O4/n1hQJfD3EokphIJvrIYUDhtZJFvlRi0J5ZA4zGfczGXdRLJkI/QLlQxMnREfK5PAbDISdlCEAeP37MAF0slxnQymU6v8e/m8YhXGuGtdVlmIYOazJGPLOQyRdx2u1CMTPwwgB7Kxs8PyJBgqTpOOt08e57P0C328Grr7yCermCoyeHqNWqEBWJyUwaxdDJCWLbTJpIH6WFg+bubDbDJHUgpQIe3buH04MjXNzZxdn+gPXolY1VxGmAfKmApkHMVYPtTBGElBCmxRZQdB2Xr11HudHAnfsPcHzyBNPZmIcFLSh7e3uMBYZmYHVlDaaR5bHX6XQRBv6zFf7/z7/2iymFI5brsA+tWC7BcT3k8yXoWhaSYEAUdARBAlHNIfSnsJ0+Qn8Cyxogm1WY4dA/niyCAIOGtyShN+ij2mzAC3x4lJWFgKypcxKL9B5ZKGM6ttmuQ5lZYhfzcMXjsDKTybFeet45hVkUUK020OsOMBgMkc3m5uw5pEHhIIlTDqsO2gOU81l40xFq2SyWG1UMRwMY2SwsL8DUcZEvl9jqQVnmUimPyPNAmWnyRxaKBfapTu0ZD5RaowFZNVgKMeQMcSYG1chPIeka/CRiXWvmWBgOhoj9mMOZ6WAMd0bsVYFjuwj8EGEYw7Jc9hUGvs8DmxekFMgUFFRKGdQqOp6/uoat9RrK1Sp2trawVm/A9wWEaQ6dkcOa7ns3b0FJBXzjj/8Es/EEomvxIKcsrJnP8sIQxjGDeZIIcCzKCmfQtU+wd3ELl69ex9FpB999/U3Iem6efe522f5jew5E1jLn+ii9FwEKgeyPH2Sn+nFQJXBc/FskpshcTCDNtilxrr8SqC40UtYt0xSKvLBnEXDO7U4iuQ7oGkQyMQGxMAdkVVI5fCdApUQTuUVowaXMdxiRs4BAHMgqKjRdxMpqAzc+dQXXrl9FiADZTJ7DfgZoWWXbFV1fsVjkMU2hL10TgR6BH31P4+zodIBsroCllSbCyMF43EeSeGg1yzh49BiryysYDwYwDQMZU8eDBw/4fWu1Gkd2lVqNSQiBKo15smulioG7H97B9uYGe1TTOIQqJ0gFkcftcbsDxTDw6Z1djuj2j46RyjK6ZK+qVtkL26zVMZtMUC6W0Fpd5nFMWv1Kcxk/ePcWNtdXcHTwhO/9jRs35s9XlnEy6yEOQljDMSc8u+dtaFIB550OLl65Ml9g0xSXWmvQNAUnJ4dwXJvtavlyBYVKGYKqsyQXpCmePHmEyXiIb37zm0/zKCkq5QrWVzdQrzU4Ajk6OsFoNEG9ufJsgeo/+V//dmo7Npu4SYymLJ+ZyRCtQ6XSABIVYSAgDFLUlzcReBP4wRiaEsP3Z+iePWZBhAYFgVS314PfHSGTzyFXLuKocw4tY6I/nXE4tL25ziZ8VZGQ1erwfLLDuAhCG2HoIKXiA9IAY/JA0twQOOGTChGmEwuaRuFXzGBKLJVOTllcmlDEYO91+jAkEXoSY6NWgxD4OGufICSAIFsO+UuJgSgaT9JauciAqrKoH7KOpqgq3MBHrljg0MtxA2aqppKd26IoNE4UyIaG4XSKk+453zsS4kfdIdypA2/mQCQHADkbwoR1LZr45Kcd2gOe7AxUMX0lRkVy5VxPXl0uQ0p9rK6W8fNf/QKuXryCam0D3ZmAQnUF52dtIErw4M6H+L3f/VfwbAfuZAzHdRGnCetfVNxQrBXhWC5qxTqyeg6+EyGQe7h09XmcnfeI/OHDO/cxc+lzZ/jvwzRmNkSpxoV3mUBxYfD/kdCdw3hKVv354f+C4S5kjjSZRzQfB9uEbVnzxNMiYUWRxvw8ZIHS2DWi8FhIEUlgqSqgiAYpVPodgyoBNRnKJGanBGBxHEAQE37OGTkLTRewtFzFlas72Lu4DTWjIJ8rQtfNuVdVlHF0fMjjuFavI44iqJrKVqXpZIIwiliDpOKXdpdIhIJqrQxZSRDFxLITvP7Gt7C+sorLexchPbXdZU0CkCNcvnwZb7755lzT9sni1GSNlj47JaymNrlZXBQyJkaDLl/H0el9Ns2PLBtf/9Z3sH1hF5/b3UEcxTjv9+HFCU7O2gzSpOGSZa/XGaFWzWNpdQ2CqaN33mGrFP3Od12cHR+x+V+WJKxvrKPZbOHmw7uQBAHexEIahBz+94cez8+NnQtsN4tSAdfXV9hRc3R8wIs4WfMkw0ClUWcfrR2GMHJ5HB08wp0PbvOiQQsTfdb9x/tYbq1gNrM46jw6PMaHd++jvrL1bIHq7/z2rzJTnZLp2PeQyWURUMo/pfB6hsAHGvU1FAtV1lR1lbToEIocY…"

**Comment by shantilal-narola** [comment]
Any update on this?

**Comment by drake4964** [comment]
still unable to figure it out, try to change the backend to recieve base 64 string instead of file.
