### ISSUE TITLE
Image gets bigger in file size

### ISSUE THREAD

**Issue by dvdnhm** [Mawi137/ngx-image-cropper#460]
I ran couple of tests with the cropper, after the crop the output image is bigger than the original file size.

Original: 800x450px - 71.8 kb
Cropped: 105x105px - 215.4kb

Original: 800x1422px - 153 kb
Cropped: 138x150px - 1 mb

Any suggestions?

**Comment by Chidexprince** [comment]
@dvdnhm  Add this property [resizeToWidth]="256"
You can specify the number of your choice. This resizing property compresses the image. It is 0 by default. 

Tested with an image of 100kb and it is compressed to 22.5kb with the specified number.
Hope this helps

for example:
<image-cropper [imageChangedEvent]="imageChangedEvent" [maintainAspectRatio]="true" [aspectRatio]="4 / 3" [resizeToWidth]="256"
            format="png" (imageCropped)="imageCropped($event)" (imageLoaded)="imageLoaded()">
</image-cropper>

**Comment by dvdnhm** [comment]
It worked out, thanks.
