### ISSUE TITLE
Feature: pass touch events outside of cropper on mobile

### ISSUE THREAD

**Issue by squio** [Mawi137/ngx-image-cropper#464]
Hi there,

Image cropper is working great on mobile (we use it in an ionic project)!

I have a use case where it would make sense to allow scrolling the screen view when touching the picture to be cropped *outside the cropper area* to scroll the mobile device view.

The attached screenshot hopefully explains the situation: the photo covers a significant part of the screen while the cropper is only covering a small part of the photo.
Touching anywhere outside the cropper and dragging currently has no effect, dragging on the small (white) borders left or right of the photo works.

In Firefox I can get this behavior by removing the inline properties from the generated DOM container element (second screenshot):
- `touch-action: none;`
- `user-select: none;`

It would be great if we could enable this behavior (with an extra setup option, default off?)

![device-2021-10-14-121553](https://user-images.githubusercontent.com/169410/137300086-2817aa00-9cb4-4faa-8806-6e40d6d54792.png)

<img width="347" alt="Screenshot 2021-10-14 at 12 28 32" src="https://user-images.githubusercontent.com/169410/137301048-bb669b9d-f6ea-4a6e-aed7-d4d57ac1fe98.png">

**Comment by Mawi137** [comment]
Hi

You should be able to overwrite the css if you put it in the global styles.scss.
```
image-cropper > div {
 touch-action: auto !important;
 user-select: auto !important;
}
```

**Comment by squio** [comment]
Fair enough; but to me it appeared that those properties were inserted at runtime from script somehow...

My attempts at overriding from css failed (disn't insert them at the :root element, maybe the cascade wasn't specific enough...)
