### ISSUE TITLE
'image-cropper' is not a known element error

### ISSUE THREAD

**Issue by maxbauer** [Mawi137/ngx-image-cropper#465]
Hi,

at first thanks for this nice project!
I wanted to create a component which allows me to upload and crop it afterwards.

I have a module for the ui components:
**ui.module.ts**
```
import { NgModule } from '@angular/core';
import { ImageCropperModule } from 'ngx-image-cropper';
import { ImageUploadComponent } from './image-upload/image-upload.component';

@NgModule({
    imports: [
        ImageCropperModule
    ],
    declarations: [
        ImageUploadComponent,
    ],
    exports: [
        ImageUploadComponent,
    ]
})
export class UiModule { }
```

**image-upload-component.html**
```
<input type="file" (change)="fileChangeEvent($event)" />
<image-cropper format="png" (imageCropped)="imageCropped($event)" (imageLoaded)="imageLoaded()" (cropperReady)="cropperReady()" (loadImageFailed)="loadImageFailed()"></image-cropper>
<img [src]="croppedImage" />
```
Here I'm getting the error:

> 'image-cropper' is not a known element:
> 1. If 'image-cropper' is an Angular component, then verify that it is part of this module.
> 2. If 'image-cropper' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

When I'm importing the ImageCropperModule in the app.module.ts directly and then using the image-cropper component in the app.component.html then everything works well. What's my fault with the extra module?

Thanks in advance!

**Comment by Mawi137** [comment]
I have no idea to be honest. Importing the ImageCropperModule in the module where the component is used, should be enough. Like you did.

**Comment by subodhmishrakiwi** [comment]
its not work for me

**Comment by MikiraSora** [comment]
it's not work for me , please help
![image](https://user-images.githubusercontent.com/7549173/206873190-f301ee02-d4d7-4ddd-8705-cd7046d81a90.png)
![image](https://user-images.githubusercontent.com/7549173/206873172-f484e39d-9fb8-4269-b2d6-e698a0ac22a5.png)

**Comment by Logik03** [comment]
this doesn't  work,  i have downgraded  the version imported imageCropperModule in the component i do need it, but still yet i get te the 'image-cropper' isn't a known element , this is still an issue in 2022
