### ISSUE TITLE
backgroundColor is not respected for png format

### ISSUE THREAD

**Issue by wertzui** [Mawi137/ngx-image-cropper#466]
When using `[containWithinAspectratio]="true"` and `backgroundColor`, the cropped image will not get the background color if the format is `png`.

I have the following `image-cropper` and also a `p-colorPicker` from PrimeNG to set the background color.
```
  <image-cropper #cropper [imageFile]="tempImageFile"
                 [maintainAspectRatio]="true"
                 [aspectRatio]="120 / 40"
                 [resizeToWidth]="120"
                 [resizeToHeight]="40"
                 [onlyScaleDown]="false"
                 [autoCrop]="true"
                 [containWithinAspectRatio]="true"
                 format="png"
                 (imageCropped)="croppedImageChanged($event)"></image-cropper>
  <p-colorPicker [(ngModel)]="cropper.backgroundColor" appendTo="body"></p-colorPicker>
```

When I pick a color, I can directly see the change in the cropper so the binding between the two is just fine.
![image](https://user-images.githubusercontent.com/4849642/140085072-4b4abdd1-dc7b-481a-80af-803e494630c7.png)

When using format `jpeg` the cropped image gets the selected background color.
![image](https://user-images.githubusercontent.com/4849642/140084537-ee8e42ea-56d9-419d-af07-db3ef392e5b6.png)

When using the format `png`, the background color is always transparent.
![image](https://user-images.githubusercontent.com/4849642/140084831-b6a05bc7-f8cf-4282-a48e-4c275d19e7d9.png)

**Comment by Mawi137** [comment]
Hi, I don't seem to be able to reproduce the issue. Are you using the latest version?
