### ISSUE TITLE
Moving out of View Engines

### ISSUE THREAD

**Issue by RoopanV** [Mawi137/ngx-image-cropper#468]
While building an app with Angular V13 facing below warning:

⠙ Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
- ngx-image-cropper [es2015/esm2015] (https://github.com/Mawi137/ngx-image-cropper.git)
Encourage the library authors to publish an Ivy distribution.

**Comment by gloriousjob** [comment]
This would be tied this issue: https://github.com/Mawi137/ngx-image-cropper/issues/470

**Comment by Mawi137** [comment]
Hi, you can use version `6.0.0` of the image cropper.
