### ISSUE TITLE
Accept undefined for @Inputs without default value

### ISSUE THREAD

**Issue by wertzui** [Mawi137/ngx-image-cropper#469]
There are some `@Input` declarations which neither have a default value or are possibly undefined.
To get better type checking, these should be marked as possibly undefined.
In my case, this breaks my build, because I'm wrapping the cropper in a component and are providing `File | undefined` to the cropper for the `imageFile`, because I am exposing another `@Input` for the property and if I don't mark that as possibly undefined, The TypeScript compiler won't let me compile my code too.

So instead of
```
  @Input() imageChangedEvent: any;
  @Input() imageURL: string;
  @Input() imageBase64: string;
  @Input() imageFile: File;
```
it should become
```
  @Input() imageChangedEvent?: any;
  @Input() imageURL?: string;
  @Input() imageBase64?: string;
  @Input() imageFile?: File;
```

**Comment by BensonBen** [comment]
you could always map your observable or inputs to these observables to a type, or cast as a workaround for now.

It should be noted that I also want this feature

**Comment by Mawi137** [comment]
Hi, I applied this to the latest version of the cropper (6.0.0) which requires Angular 13.
