### ISSUE TITLE
Allow align image when zoom in

### ISSUE THREAD

**Issue by mivanyna** [Mawi137/ngx-image-cropper#472]
I would like to have ability move image to see top of the image (or bottom, left, right side) when zooming in.

Currently when you zoom in - you see central part and top, left, right, bottom sides are cropped and can't be viewed.
I want to zoom top right corner for example.

**Comment by mivanyna** [comment]
I guess just need to add `translate`

**Comment by mivanyna** [comment]
Here it is, https://stackblitz.com/edit/image-cropper-8pjour?file=app/app.component.ts
Should I create a PR with those changes?

**Comment by mivanyna** [comment]
Can't create a PR, don't have access :(

**Comment by vpetrusevici** [comment]
Looks good. @Mawi137, is it possible to add?

**Comment by Mawi137** [comment]
@mivanyna You first need to fork this git repo, apply the changes to the forked repo and then you can open up a PR.

**Comment by mivanyna** [comment]
> @mivanyna You first need to fork this git repo, apply the changes to the forked repo and then you can open up a PR.

@Mawi137 done https://github.com/Mawi137/ngx-image-cropper/pull/478
