### ISSUE TITLE
Scale to fit outer container

### ISSUE THREAD

**Issue by Rikarin** [Mawi137/ngx-image-cropper#473]
Hi,
I read documentation multiple times but it's not clear to me how to scale up uploaded image to fit the outer container.
eg. I upload image of size 150x150 and I would like to fit it inside 600x600 to better see it when cropping.

Thanks

**Comment by Mawi137** [comment]
Hi, yes this is intentional. Maybe you can override the behaviour with css by setting a width for the `.ngx-ic-source-image`
