### ISSUE TITLE
I'm on angular 13.1.0 - but when using 6.0.0 I'm not able to load the component.

### ISSUE THREAD

**Issue by baskuis** [Mawi137/ngx-image-cropper#474]
Error:

main.424e07d9dbd06fc1.js:1 Uncaught error Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'onDestroy')

<img width="1278" alt="Screen Shot 2022-01-05 at 9 36 19 PM" src="https://user-images.githubusercontent.com/407588/148324338-72515a1a-e525-4db7-b99d-39d4d88db581.png">

Would you know what could be the issue? Happy to help fix it otherwise, or at least I can try?

**Comment by Mawi137** [comment]
Hi, can you try deleting your node modules and installing it again or delete the angular cache in your project? I think there might still be a cached version of it in your project because Angular converts ViewEngine libs to Ivy itself and usually stores that somewhere.
