### ISSUE TITLE
Image load error if component visually hidden

### ISSUE THREAD

**Issue by acfaruk** [Mawi137/ngx-image-cropper#475]
https://github.com/Mawi137/ngx-image-cropper/blob/5dce0635670e97557772ccf9e0ebdad72035b19b/projects/ngx-image-cropper/src/lib/component/image-cropper.component.ts#L270

This line caused issues for me, since I had the component in a dialog that was only visually hidden. The image would load in the component but this line would say that it was not loaded yet, causing it to error out eventually. I was able to fix this by removing the component from the DOM while it was not used, but it should also work while hidden in my opinion.

Easiest way to reproduce: Wrap the component in a div with the hidden attribute and listen to the loadImageFailed event.

**Comment by Mawi137** [comment]
You can visually hide it. It needs to be on the screen in order to calculate the width and height of the displayed image.

**Comment by acfaruk** [comment]
Hey thanks for the reply, I made a codesandbox to show my issue:

https://codesandbox.io/s/objective-khayyam-h1zcj?file=/src/app/app.component.ts

The imagecropper in div2 does not show up correctly after being visible again. 
I wanted to use it like that, so that the component could load the image in the background and initialize and then all I would have to do was make it visible. As you can see from the example, it does not seem to work for my usecase.

**Comment by Mawi137** [comment]
You can hide it until the `imageLoaded` event fires. From then you should show the cropper.
