### ISSUE TITLE
What Angular versions are supported

### ISSUE THREAD

**Issue by TimMackey** [Mawi137/ngx-image-cropper#476]
I notice version 5.0.0 Dropped support for Angular 9.
I am required to migrate my project to Angular 9, and then to Angular 10.
Must I find another image cropper component, or will you reconsider supporting current Angular versions?
Is there a work-around?
Will this component work if I import the files and build it into my project Angular 9?

**Comment by Mawi137** [comment]
If you don't want to upgrade your project, you can stick to an older version of the image cropper as well. However, I won't be doing any updates to old version.
