### ISSUE TITLE
Cropper size remains zero and non resizeable

### ISSUE THREAD

**Issue by la-kumar** [Mawi137/ngx-image-cropper#48]
hi ,
Sometimes when an image is loaded for cropping, the cropper square remains non-resizeable
leaving cropped image corrupted .
Please help what should be done in such scenario.
Note : 
in attached image cropper is non-resizable and below is cropped image which is  not generated
![cropperissue 1](https://user-images.githubusercontent.com/35961175/39830095-0b8d47d6-53de-11e8-809a-d4f8f58ce032.png)

**Comment by abnersouza** [comment]
I had similar issue like your only when using the IPAD.

To solve i add settimeout function.

`loadImage(event: any) {
    this.imageVisible = false;
    this.originalImage = new Image();
    this.originalImage.onload = () => {
      this.originalSize.width = this.originalImage.width;
      this.originalSize.height = this.originalImage.height;
    };
    const fileReader = new FileReader();
    const blank =
      'data:image/png;base64,iVBORw0KGg' +
      'oAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAC0lEQVQYV2NgAAIAAAU' +
      'AAarVyFEAAAAASUVORK5CYII=';
    fileReader.onload = (ev: any) => {
      if (
        event.target.files[0].type === 'image/jpeg' ||
        event.target.files[0].type === 'image/jpg' ||
        event.target.files[0].type === 'image/png' ||
        event.target.files[0].type === 'image/gif'
      ) {
        this.imgDataUrl = ev.target.result;
        this.originalImage.src = ev.target.result;
        this.imageLoaded.emit();

        setTimeout(() => {
          const displayedImage = this.elementRef.nativeElement.querySelector('.source-image');
          const maxSize =
            displayedImage.offsetHeight > displayedImage.offsetWidth
              ? displayedImage.offsetWidth
              : displayedImage.offsetHeight;
          this.cropper.x1 = Math.floor(displayedImage.offsetWidth / 2 - maxSize / 2);
          this.cropper.y1 = Math.floor(displayedImage.offsetHeight / 2 - maxSize / 2);
          this.cropper.x2 = this.cropper.x1 + maxSize;
          this.cropper.y2 = this.cropper.y1 + maxSize;

          this.crop();
          this.imageVisible = true;
        }, 0);
      } else {
        this.imgDataUrl = blank;
        this.originalImage.src = blank;
        this.loadImageFailed.emit();
      }
    };
    fileReader.readAsDataURL(event.target.files[0]);
  }`

**Comment by Mawi137** [comment]
Hi @abnersouza, that code seems a little outdated?
@la-kumar What's the version of the cropper you're using?

**Comment by la-kumar** [comment]
hi 
@Mawi137  , I am using "0.2.6" version

**Comment by wandersoncesar-actuar** [comment]
Same problem here.

**Comment by lblower** [comment]
i had the same issue.  i am using **base64** image  in one of my angular project.
* i guess the issue is when plugin load the config property is set to null so the cropper doesn't work.
---------------------
i have set a condition when the **base64  image string is available**  only then load the ngx-image-crooper plugin.

> 
> <div ***ngIf="imageCropper.imageBase64" >**
> 			<image-cropper
> 				[imageChangedEvent]="imageCropper.imageChangedEvent"
> 				[maintainAspectRatio]="true"
> 				[imageBase64] = "imageCropper.imageBase64"
> 				format="jpeg"
> 				(imageCroppedBase64)="imageCroppedBase64($event)"
> 				(imageLoaded)="imageLoaded()"
> 				(loadImageFailed)="loadImageFailed()"
> 				style="max-height: 33vh"
> 				[style.display]="imageCropper.cropperReady ? null : 'none'">
> 			</image-cropper>	
> 		</div>
