### ISSUE TITLE
Text and line and shapes

### ISSUE THREAD

**Issue by mammadkoma** [Mawi137/ngx-image-cropper#480]
Is it possible to add Text and line and arrows and shapes on image and get base64?

**Comment by Mawi137** [comment]
Hi, not this is not an image editor, simply an image cropper.

**Comment by mammadkoma** [comment]
Did you use a free angular package for image editor in your projects?

**Comment by Mawi137** [comment]
I never needed such features, so no :)

**Comment by mammadkoma** [comment]
Thank you I used ngx tui image editor.
