### ISSUE TITLE
Static width, height doesn't work when adding small dimensions image

### ISSUE THREAD

**Issue by Ranindu15** [Mawi137/ngx-image-cropper#483]
We set static width and height because we need the specific size of the image(static sizes). But when we add the small image it doesn't get that static width or height. It gets the image natural width or height for the crop. I think when the user sets static width or height image should be that size with the additional background color.

**Comment by Mawi137** [comment]
Hi there. Sounds like a good idea. Feel free to open up a PR with those changes.
