### ISSUE TITLE
unable to change the ratio when maintainAspectRatio is set to false

### ISSUE THREAD

**Issue by konrad-synergy** [Mawi137/ngx-image-cropper#484]
When `maintainAspectRatio` is set to true, changing ratio works. However, if you'd like to change the ratio when the `maintainAspectRatio` is set to false, it does not work. It would be nice to have it working both ways, don't you agree?

**Comment by Mawi137** [comment]
What do you expect it to do when `maintainAspectRatio` is false?

**Comment by Mawi137** [comment]
I still don't understand what you want it to do.  maintainAspectRatio: true => the aspect ratio is always fixed. maintainAspectRatio: false => freeform. That's what is does now.

**Comment by akkonrad** [comment]
If so, it means that it's not a common case and maybe weird even. So I guess I won't bother you with that, unless I'll find some time to do it and PR. Anyway, good job and take care :)

**Comment by Mawi137** [comment]
Apparently not :D Thanks and you too!
