### ISSUE TITLE
Add a Pan functionality to align image when zoom in

### ISSUE THREAD

**Issue by mivanyna** [Mawi137/ngx-image-cropper#488]
It would be nice if we can align image (like here https://github.com/Mawi137/ngx-image-cropper/issues/472) with pressing on image and moving mouse like we do with cropping area.

Maybe existing logic can be reused.

**Comment by alexfarrugia** [comment]
I added a stackblitz for this issue here: https://stackblitz.com/edit/image-cropper-kekq3j

Also uploaded a PR https://github.com/Mawi137/ngx-image-cropper/pull/495 which addresses this. Hopefully will be reviewed soon :)

**Comment by Mawi137** [comment]
Released under version `6.2.1`.
