### ISSUE TITLE
Wrong Preview with very small Images

### ISSUE THREAD

**Issue by timstrakeljahn** [Mawi137/ngx-image-cropper#492]
When trying to upload a very small image (4kb, png, 300x300px) the preview of the cropper is showing a half cut picture. 

If I save the cropped image directly without moving the cropper the right image is saved. 
Even when moving the cropper the right selection gets saved.

I've attached the original image and a screenshot of the cropper preview

<img width="316" alt="Screenshot 2022-02-22 at 21 46 00" src="https://user-images.githubusercontent.com/19797567/155216359-854385fb-96c8-4be5-a2a9-0a22aa7f9edf.png">
![frame (3)](https://user-images.githubusercontent.com/19797567/155216393-32d15c6d-695e-44b1-99c3-a94409c2ecd2.png)

**Comment by djabif** [comment]
Hi @timstrakeljahn , I'm facing the same problem. Were you able to solve it?

**Comment by timstrakeljahn** [comment]
Hey, not yet, unfortunately. I will let you know if I find a solution.

**Comment by jagoqui** [comment]
Hi, I have the same problem :(, some solution?

**Comment by djabif** [comment]
@jagoqui try with this:
```
::ng-deep {
  img.ngx-ic-source-image {
    margin: 0px auto;
  }
}
```

**Comment by timstrakeljahn** [comment]
@djabif thank you very much this is working for me

**Comment by jagoqui** [comment]
@djabif  thank you very much, it worked for me. :3
