### ISSUE TITLE
Change the border of the round cropper

### ISSUE THREAD

**Issue by alexfarrugia** [Mawi137/ngx-image-cropper#493]
Hi, first of all thanks and well done for such an awesome package!

Is there an easy way to change the border of the cropper (specifically the round one) ? I would like to have a border which is not dashed but which is solid and white in colour?

Many thanks

Alex

**Comment by djabif** [comment]
You can style it using ng-deep selector

```
::ng-deep #yourView {
  .ngx-ic-cropper:after {
    border: solid 2px #fff;
  }
}
```

**Comment by logiccrunch** [comment]
> You can style it using ng-deep selector
> 
> ```
> ::ng-deep #yourView {
>   .ngx-ic-cropper:after {
>     border: solid 2px #fff;
>   }
> }
> ```

awesome thanks for your help

**Comment by alexfarrugia** [comment]
awesome thanks for your help
