### ISSUE TITLE
Skewing of image

### ISSUE THREAD

**Issue by dylanvdmerwe** [Mawi137/ngx-image-cropper#497]
I wanted to find out if there is any possibility to allow the option to make it so that the cropped image does not need to be fully rectangular. 

For example: 
![image](https://user-images.githubusercontent.com/2852839/161502918-b2ead709-086c-416c-8631-2b16977fa129.png)

It would be great to optionally support the ability to move each corner handle independently which would result in an image that is skewed from the original, but can allow much greater cropping functionality in certain situations. 

The resulting image would still be rectangular in shape, with the contents skewed to fit the shape.

**Comment by Mawi137** [comment]
This would have a big impact on the code of this lib because now it only tracks 2 coordinates for the cropper position and a lot of calculations would be needed to track the changes of the middle dot. But feel free to give it a try an open up a PR!
