### ISSUE TITLE
Image rotating for portrait images on mobile devices

### ISSUE THREAD

**Issue by abnersouza** [Mawi137/ngx-image-cropper#50]
Hi guys, I found this issue in my Ipad pro, Iphone and also same issue in a android mobile as well.

I used the ngx-image-cropper in our app, but after testing in the mobile uploading a portrait image, i got the following.

![48965e22-8571-4f03-a72d-b18f221cb97c](https://user-images.githubusercontent.com/3270632/40209809-e14e4930-5a17-11e8-8ca6-94e5a7635815.jpg)

As you can see i just opened the https://stackblitz.com/edit/image-cropper in a mobile phone and add a photo in a portrait mode, notice that half of the image is black, if you move the cropper from the middle to the top the issue with black part is solved. But the image is still rotated left.

In my case I also used that in progress web app, where i used the mobile camera and depending on the orientation you use the mobile phone the image can be upside down.

Tried to find out in the code where the image is being rotated, if you could let me know please?

Thanks

**Comment by Mawi137** [comment]
Does that happen with all of your images? Images are cropped fine on my Android. Also, the image aren't rotated in the code.

**Comment by abnersouza** [comment]
@Mawi137 I tested on an galaxy s3, Iphone 6s and Ipad pro.  I will try on other devices as well.

**Comment by Mawi137** [comment]
Hi, the image cropper now check for the EXIF rotation and rotates the image accordingly. Seems to be working fine for me now! (version 0.2.8)

**Comment by abnersouza** [comment]
@Mawi137 Thanks so much for the effort, i will test over the weekend and let you know. Also tks @justsolarry for the help there.

**Comment by abnersouza** [comment]
@Mawi137 Perfect change, not is rotating it properly. One thing i can't do unfortunately is resize the cropper i have the cropper on a modal and can't resize using the squares. Let me know if you have a similar issue like that. Thanks so much
