### ISSUE TITLE
Add options

### ISSUE THREAD

**Issue by Frankistan** [Mawi137/ngx-image-cropper#504]
It would be great if we could pass an object variable as settings to the "image-cropper" component . For instance:

// HTML
<image-cropper [settings]="cropperSettings" </image-cropper>

 // TS
        cropperSettings = new CropperSettings({
            alignImage: "center",
            aspectRatio: 4 / 3,
            roundCropper: false,
            .....
        });

**Comment by Mawi137** [comment]
That was my goal, but the impact is bigger than I estimated so I didn't expose it yet.
