### ISSUE TITLE
Intalled ngx-image-cropper in angular universal project getting error "window is not defined    at new ImageCropperComponent"

### ISSUE THREAD

**Issue by sunysunysuny** [Mawi137/ngx-image-cropper#506]
Hello team,

I followed all the instruction from the [https://www.npmjs.com/package/ngx-image-cropper](url) and  installed  ngx-image-cropper successfully in angular universal project.

Also there is no error at the time of compilation. But as I browse the project it throw the error.
"window is not defined    at new ImageCropperComponent".

I am attaching the files please have look and let me know where I am missing.
response will be appreciated
![ngx-image-first-page](https://user-images.githubusercontent.com/27955832/173312467-add9da9f-995c-4cae-b656-6bbd38f7841c.PNG)
![ng_version](https://user-images.githubusercontent.com/27955832/173312477-33742658-4b48-46de-8894-f833b0b1caa7.PNG)
![ngx-error](https://user-images.githubusercontent.com/27955832/173312482-4c5622de-583e-4d94-9ae8-044842481bcd.PNG)
.

**Comment by Mawi137** [comment]
The image cropper needs to be visibile in order to calculate the positions. Can't you wrap the image cropper in an ng-container with an ngIf so it is only rendered when the platform is a browser?
