### ISSUE TITLE
Support for Angular 14

### ISSUE THREAD

**Issue by rossmills99** [Mawi137/ngx-image-cropper#507]
Currently the library does not compile using Angular 14, would be great to see support for the latest framework version.

**Comment by christiansimms** [comment]
I am able to use this library in an Angular 14 app. The only challenge I had was IntelliJ added this import by default:

   `import { ImageCropperModule } from 'ngx-image-cropper/public-api';`

Which caused a weird error message:

`
Error: Module not found: Error: Package path ./public-api is not exported from package .../node_modules/ngx-image-cropper (see exports field in .../node_modules/ngx-image-cropper/package.json)
`

The solution was easy -- just tweak the import:

`import { ImageCropperModule } from 'ngx-image-cropper';`

**Comment by Mawi137** [comment]
It should indeed work fine with Angular 14. Are you getting an error @rossmills99 ?

**Comment by rossmills99** [comment]
Thanks both for confirming it should work. I raised the issue on someone else's behalf so will check with them and share any further info I can.
