### ISSUE TITLE
How can I align vertically ?

### ISSUE THREAD

**Issue by lucas-sesti** [Mawi137/ngx-image-cropper#508]
I'm trying to align vertically the image when the height is smaller than component height, how is it possible? I can't find anything about this in documentation.

I tried add display flex in parent div of image-cropper and added align-items: center in image-cropper, it works when the image is small, but when the image is larger, doesn't work

<img width="857" alt="image" src="https://user-images.githubusercontent.com/11727165/175377893-4e4759ed-0384-4cf4-b70c-792e5162db4e.png">

**Comment by Mawi137** [comment]
Hi, I got it to work by adding a wrapper div which has
```
display: flex;
align-items: center;
height: 300px;
```

The image-cropper should get a max-height that equals the height of the div.

**Comment by lucas-sesti** [comment]
Oh it works, I was trying add align-items in image-cropper but work when add in wrapper like you said. Thank you
