### ISSUE TITLE
Problem with round cropper on version 5.0.0

### ISSUE THREAD

**Issue by ipostu** [Mawi137/ngx-image-cropper#509]
Hello!

I've recently started using this library in a ionic project and works fine.
We wanted for avatar images to use the rounded cropper, but it looks like there is a bug. 

The class that is attached right now when roundedCropper is set to true is called "rounded", but as per changelog was renamed to "ngx-ic-rounded" 

Is it possible to release a new version with this fix? like 5.0.1?
Upgrading to latest version is not an option right now, we are using version 11 of Angular.

The workaround is to use the css rules from "ngx-ic-rounded" in a globally defined class named "rounded"

**Comment by Mawi137** [comment]
Hello, it's a breaking change so that's not an option I'm afraid.

**Comment by Hardik432** [comment]
I think your problem will resolve in this version https://www.npmjs.com/package/ngx-image-cropper/v/5.0.1
