### ISSUE TITLE
Allowing cropper to have bigger height then the image

### ISSUE THREAD

**Issue by BrsJsk** [Mawi137/ngx-image-cropper#51]
Is there a way to allow to cropper to get bigger then the selected image? 

For example, I maintain aspect ratio of 1 / 1 which is a square, and if I upload an image with width of 600 and height of 100, the cropper will be a square of width and height 100 but there's no way to make it bigger. 
Imagine if we want to fit the 600x100 image into a 200x200 cropper. Is there a way to do it?
Yeah, I know then the image wont be pretty and will have dead space, but that's not important. Just need to have the option.

[https://stackblitz.com/edit/image-cropper-jenfnl](url)

**Comment by Mawi137** [comment]
Hmm, that won't be easy I'm afraid..
You're probably looking for something like this: https://fengyuanchen.github.io/cropper/
