### ISSUE TITLE
allowMoveImage does not consider rotation

### ISSUE THREAD

**Issue by sfox-developer** [Mawi137/ngx-image-cropper#510]
Hey there,

thanks for this awesome piece of art.

The latest option allowMoveImage is a great one, so finally we can build an option similar to instagram, linkedin, etc where we can make the image move and not the cropper.

There is one issue with this new option you can also see within the example project.

Following steps to reproduce:

- add rotation of 90
- click "enable image panning"
- move image left and right

Here you can see the image does move up and down, and now left and right anymore because of the transform.

**Comment by Mawi137** [comment]
Hello, thanks for letting me know! It's fixed in versiom `6.2.2`.
