### ISSUE TITLE
feature request: option to make backgroundimage not reach canvas boundaries

### ISSUE THREAD

**Issue by sfox-developer** [Mawi137/ngx-image-cropper#511]
I really like the new option allowMoveImage. It would be great to have an option to make sure the background image is not dragged further than the canvas itself to prevent adding additional image material which is blank/white or to what ever the background is set to.

in cropper.js i think it is the viewMode = 1 which does restrict the image to the canvas.

**Comment by Mawi137** [comment]
Sounds like a good idea! Although that would mean that you cannot zoom out when that option is enabled?

**Comment by sfox-developer** [comment]
Hey @Mawi137, yes exactly. The user needs to zoom in to drag the image around.
Here an example https://www.loom.com/share/09e2b8d34a66473cac89f6b93b0f3f27

**Comment by wasifmehmood** [comment]
@Mawi137 any idea when can we get this feature?
