### ISSUE TITLE
Disable cropper or allowMoveImage

### ISSUE THREAD

**Issue by Hardik432** [Mawi137/ngx-image-cropper#513]
Currently when you use disable option it will disable both cropper movement and `allowMoveImage` functionality. What I want is to disable only cropper not `allowMoveImage` functionality.

**Comment by Hardik432** [comment]
Hey @sfox-developer thanks for the help. But can we do this programatically like add new option and handle this scenario. It's hard to think that we can achieve this using css. Thanks again

**Comment by oquadri** [comment]
Hi, I am trying to get similar behavior for my app and restrict cropper movement (cropper circle fixed) and allow background image to move and pinch to zoom in/out. Tried css given by @sfox-developer  but no luck. Is there any other solution that worked, please share. Thanks!
Below is my code for cropper:
  <image-cropper
    [imageChangedEvent]="myImage"
    [maintainAspectRatio]="true"
    [roundCropper]="true"
    [aspectRatio]="1 / 1"
    [resizeToWidth]="128"
    [disabled]="false"
    [hideResizeSquares]="true"
    [allowMoveImage]="false"
    format="png"
    (imageCropped)="imageCropped($event)"
    (cropperReady)="cropperReady()"
    (loadImageFailed)="loadImageFailed()"></image-cropper>

**Comment by Hardik432** [comment]
@oquadri You have set allowMoveImage to false it should be true
