### ISSUE TITLE
when  set crop disable(by css both disable=true and allowMoveImage=true not working together) and allowMoveImage=true then always emit same base64 data?

### ISSUE THREAD

**Issue by skmahala** [Mawi137/ngx-image-cropper#519]
here is my code sample  
css
 image-cropper::ng-deep {
  .ngx-ic-overlay,
  .ngx-ic-cropper {
    pointer-events: none;
  }
  .ngx-ic-cropper {
    top: 50% !important;
    left: 50% !important;
    transform: translate(-50%, -50%);
  }
}
html code
<input id="profile-img-file-input" #inputFile type="file" class="profile-img-file-input"
    (change)="onFileChange($event)">
<image-cropper #imageCropper [imageFile]="selectedfile" [roundCropper]="true" [cropperStaticWidth]="200"
            [cropperStaticHeight]="200" [allowMoveImage]="true" [hideResizeSquares]="true" format="png"
            (imageCropped)="imageCropped($event)" [autoCrop]="false" style="--cropper-outline-color:rgb(0,0,0,0.5);">
 </image-cropper>
 <img src="{{base64}}" alt="">
  <button type="button" class="btn btn-success position-absolute bottom-0 start-50 translate-middle-x"
            (click)="done(imageCropper,inputFile)">Done</button>

and in my ts file
selectedfile: any;
base64 :any;
 imageCropped(event: any) {
        this.base64 = event.base64;
        let file = base64ToFile(event.base64);
    }
    onFileChange(event: any) {
        this.selectedfile = event.target.files[0];
    }
    done(imageCropper: any, inputFile: any) {
        inputFile.value = '';
        imageCropper.crop();
    }

**Comment by vimleshofficial** [comment]
same issue i am facing if allow "allowMoveImage"  this after that i move image and crop but image is cropping wrong
