### ISSUE TITLE
Resizing window when cropper is hidden breaks the cropper

### ISSUE THREAD

**Issue by jarektomanek** [Mawi137/ngx-image-cropper#520]
Cropper calculations blow up when the cropper component has `display:none` and browser window gets resized.

**Steps to reproduce:**
1. Load an image, crop it
2. Set `display: none` on the cropper component
3. Resize the browser window
4. Remove `display: none` from the cropper component

**Expected result:**
Cropper restores with positions as in step 1.

**Actual result:**
Blank cropper component shows up, cropper position is not kept.

Live demo: https://image-cropper-vxkcos.stackblitz.io

Preview:
![resize-when-hidden](https://user-images.githubusercontent.com/3630704/186136837-c96318ca-91d0-4764-8fd3-a762438ddfd3.gif)

**Comment by Mawi137** [comment]
Hi
I just released version 6.3.1 which now has an input called `hidden`. When set to true and then back to false, it will handle the resize then.
