### ISSUE TITLE
Transparent background is converted to Black for .png file that has transparent background

### ISSUE THREAD

**Issue by Mage111** [Mawi137/ngx-image-cropper#521]
I'm using the last build - 11.0.0
just upload and crop PNG file with transparent background
the background become black
any help please?

**Comment by mivanyna** [comment]
There is a property `backgroundColor`, please check if you set it to black
or try set it to `transparent`

**Comment by madmacc** [comment]
Did anyone find a solution to this?
I need the png to have a transparent background and if setting it as below the background is black.
```
<image-cropper
     ...
      format="png"
      backgroundColor="transparent"
  ></image-cropper>
```

![image](https://github.com/Mawi137/ngx-image-cropper/assets/43654472/88c70df7-834a-445d-9e35-3bf9cb6fc345)
