### ISSUE TITLE
Contain Within Aspect Ratio - Large image do not work on iOS 15.7 Safari

### ISSUE THREAD

**Issue by jesben** [Mawi137/ngx-image-cropper#525]
Load large image with "Contain Within Aspect Ratio" works in Chrome on my PC, but in iOS it dosen't load. Smaller images works...

[image-who-do-not-work-on-ios.zip](https://github.com/Mawi137/ngx-image-cropper/files/9654825/image-who-do-not-work-on-ios.zip)

**Comment by Mawi137** [comment]
Hi, that's because a HTML canvas is used to transform the image. Because you start with a large image, the resulting image will be even bigger when enabling contain within aspect ratio. On iOS it simply fails to do that.
