### ISSUE TITLE
I want to change aspect ratio dynamically. But cropper is cropping on previously cropped aspect ratio.

### ISSUE THREAD

**Issue by utkarsh621x** [Mawi137/ngx-image-cropper#528]
I want to change aspect ration dynamically and want to use same function every where to crop images this is my code ===> 

i am using useEffect to reload the function and use State variable to set aspect ratio

// code starts here ==> 

 const [width, setWidth] = useState()
  const [height, setHeight] = useState()
  const [I, setI] = useState()
 
  useEffect(() => {
    drag_crop()
    console.log("re rendered")
  }, [I])

  const drag_crop = () => {

    return(<>
      <div className="w-100 p-2">
        {uploading ? <LoadingOutlined className="display-6 text-primary mx-auto" /> : <input type="file" accept="image/*" className="form-control" onChange={(e) => step1(e)} />}
    
    </div>
      <div className="w-100 "> 
        <div style={{ width: "700px", height: "400px" }} className="mx-auto">
      
          <Cropper  viewMode={1} style={{ width: "100%", height: "100%" }}  src={orignal} onInitialized={cropper => setUnCropped(cropper)} autoCrop={true} data={orignal} dragMode='move' scalable background={false} aspectRatio={width / height} />
       
        </div>
    
   <div className="w-100 d-flex justify-content-center m-2">
   <button style={{}} className="btn btn-success " onClick={(e) => handleBanner(e, I)}> Crop & Save </button>

      </div>
      </div>
    </>)
  }

**Comment by Mawi137** [comment]
Hi, your code doesn't seem to be Angular code. Are you sure this is the right repo?

**Comment by utkarsh621x** [comment]
my bad its an react js code
