### ISSUE TITLE
Cropper dimensions limits

### ISSUE THREAD

**Issue by gudzdanil** [Mawi137/ngx-image-cropper#53]
Make available configure min width/height dimensions to crop
E.g. need to crop image with 1.5 aspect ratio and to be not less then 320x240px

**Comment by Hukutus** [comment]
It would be nice to set minimum dimensions to prevent image stretching.

**Comment by KrishnaSharmaCC** [comment]
@Mawi137 , Is this something which can be done in the near future? I mean, is it on the roadmap?

**Comment by Mawi137** [comment]
This was actually way easier to implement than I thought :D 
Just added the `cropperMinWidth` Input in version `1.3.3`!

In @gudzdanil example, you'd set the input to `320`. The height will be calculated based on the aspect ratio.

**Comment by imbdb** [comment]
> In @gudzdanil example, you'd set the input to 320. The height will be calculated based on the aspect ratio.
if `[maintainAspectRatio]="false"` then `cropperMinWidth` is needed

**Comment by Mawi137** [comment]
You mean cropperMinHeight will be needed?

**Comment by imbdb** [comment]
Yes, Apologies for the typo.

**Comment by Mawi137** [comment]
Ok, then there's already an issue for that :) #130
