### ISSUE TITLE
css leak in the package after installing

### ISSUE THREAD

**Issue by brandart** [Mawi137/ngx-image-cropper#530]
I installed the package and afterwards some of my UI looks different:

my chartjs legend icons increased:

before install
<img width="378" alt="image" src="https://user-images.githubusercontent.com/31988348/199694728-4360aa09-a40d-4eac-b720-9d158768e5ac.png">

after install the icons increased a lot:
<img width="461" alt="image" src="https://user-images.githubusercontent.com/31988348/199694796-0439c040-1cf9-4541-9b53-8eacdd770b08.png">

**Comment by Mawi137** [comment]
That would be very odd since all css used in this component is scoped to the image-cropper itself and all css classes used are prefixed with `ngx-ic-`. Maybe your chartjs lib was updated?

**Comment by brandart** [comment]
nop 🤔 

I fixed it by setting `boxWidth` and `boxHeight` of the `chartjs` legend icon
