### ISSUE TITLE
Internet Explorer 11 throws IndexSizeError if ratio is > 1

### ISSUE THREAD

**Issue by ftischler** [Mawi137/ngx-image-cropper#54]
Internet Explorer 11 throws IndexSizeError after loading of some images if canvas size is restricted from elements around. This always happens if the ratio in the crop method is calculated to be greater than 1. I already prepared a PR to fix this issue.

**Comment by merceaemil** [comment]
Can you share the fix until the pr is approved?

**Comment by ftischler** [comment]
Unfortunately my fix didn't work in some corner cases. I will try to solve the problem and share it here when I have achieved it.

**Comment by ftischler** [comment]
My solution to the problem was a change in the crop method:
```ts: 
const sWidth = Math.min(superCtx.originalImage.width, width);
const sHeight = Math.min(superCtx.originalImage.height, height);
const ctx = cropCanvas.getContext('2d');
if (ctx) {
    ctx.drawImage(superCtx.originalImage, left, top, sWidth, sHeight, 0, 0, width * resizeRatio, height * resizeRatio);```

**Comment by TylerJBrown192** [comment]
I am also experiencing this issue in Firefox. Here's the full Error output:

`DOMException
​
code: 1
​
columnNumber: 0
​
data: null
​
filename: "webpack-internal:///./node_modules/ngx-image-cropper/ngx-image-cropper.es5.js"
​
lineNumber: 564
​
message: "Index or size is negative or greater than the allowed amount"
​
name: "IndexSizeError"
​
result: 2152923137
​
stack: "ImageCropperComponent.prototype.crop@webpack-internal:///./node_modules/ngx-image-cropper/ngx-image-cropper.es5.js:564:17\nImageCropperComponent.prototype.ngOnChanges/<@webpack-internal:///./node_modules/ngx-image-cropper/ngx-image-cropper.es5.js:199:17\nZoneDelegate.prototype.invokeTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:421:17\nonInvokeTask@webpack-internal:///./node_modules/@angular/core/esm5/core.js:4956:24\nZoneDelegate.prototype.invokeTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:420:17\nZone.prototype.runTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:188:28\nZoneTask.invokeTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:496:24\nZoneTask/this.invoke@webpack-internal:///./node_modules/zone.js/dist/zone.js:485:28\ntimer@webpack-internal:///./node_modules/zone.js/dist/zone.js:2025:17\n"
​

**Comment by merceaemil** [comment]
This was my fix. Solved width and height and it makes sure that size does not exceed the original size.
Lines 408-419 ( inside crop() method)

```const ratio = this.originalSize.width / displayedImage.offsetWidth;
const left = Math.max(0, Math.min(this.originalSize.width, Math.round(this.cropper.x1 * ratio)));
const top = Math.max(0, Math.min(this.originalSize.height, Math.round(this.cropper.y1 * ratio)));
const width = Math.min(this.originalSize.width, Math.round((this.cropper.x2 - this.cropper.x1) * ratio));
const height = Math.min(this.originalSize.height, Math.round((this.cropper.y2 - this.cropper.y1) * ratio));
const resizeRatio = this.getResizeRatio(width);
const cropCanvas = document.createElement('canvas') as HTMLCanvasElement;
const widthWithRatio = Math.min(this.originalSize.width, width * resizeRatio);
const heightWithRatio = Math.min(this.originalSize.height, height * resizeRatio);
cropCanvas.width = widthWithRatio;
cropCanvas.height = heightWithRatio;
const ctx = cropCanvas.getContext('2d');```

**Comment by neto-moovone** [comment]
Hello ! 

Up @Mawi137 ! 
@merceaemil You can create a PR for this issue please ?

Thanks you !

**Comment by SeinopSys** [comment]
Running into the same issue, would love to see this fixed!

**Comment by Mawi137** [comment]
Are you guys still having issues with this in the latest version? I used this polyfill for the `toBlob` method:
```
if (!HTMLCanvasElement.prototype.toBlob) {
  Object.defineProperty(HTMLCanvasElement.prototype, 'toBlob', {
    value: function (callback, type, quality) {
      var dataURL = this.toDataURL(type, quality).split(',')[1];
      setTimeout(function() {

        var binStr = atob( dataURL ),
            len = binStr.length,
            arr = new Uint8Array(len);

        for (var i = 0; i < len; i++ ) {
          arr[i] = binStr.charCodeAt(i);
        }

        callback( new Blob( [arr], {type: type || 'image/png'} ) );

      });
    }
  });
}
```
Then tested in a virtual machine with IE11 and it seems to work fine.

**Comment by philipjohn007** [comment]
I am using `v1.2.2`, but I get the same issue with IE11. I tested on Edge, but it works fine there.

I use the following template code

    <input id="upload" type="file" (change)="fileChangeEvent($event)" (click)="$event.target.value = null" accept=".png, .jpg, .jpeg"/>
    <div *ngIf="isShowCrop">
            <image-cropper
                    [imageChangedEvent]="imageChangedEvent"
                    [maintainAspectRatio]="true"
                    [resizeToWidth]="500"
                    [onlyScaleDown]="true"
                    (imageCropped)="imageCropped($event)"
            ></image-cropper>
    </div>

And the following component code

    fileChangeEvent(event: Event): void {
      const selectedFile: File = (<HTMLInputElement>event.target).files[0];
      if (selectedFile.size > MAX_SIZE) {
        this.uploadErrors = // Error
      } else {
        this.isShowCrop = true;
        this.imageChangedEvent = event;
      }
    }

    imageCropped(event: ImageCroppedEvent): void {
        this.uploadErrors = [];
        this.croppedImage = event.base64;
    }

**Comment by philipjohn007** [comment]
Upgraded to the latest version (`v1.2.4`) and the issue not more exists.
