### ISSUE TITLE
How to crop in round shape  ?

### ISSUE THREAD

**Issue by krunalsk007** [Mawi137/ngx-image-cropper#541]
is there any css or methods to create round shape ??

**Comment by krunalsk007** [comment]
I try with this as suggest [here  ](https://github.com/Mawi137/ngx-image-cropper#api)[roundCropper]="true" and style="border-radius: 100%"  but its only show round image but actual image is still square fromthis
```
  imageCropped(event: ImageCroppedEvent) {
        this.croppedImage = event.base64;
    }
```
any idea how to get round image ?

**Comment by loiddy** [comment]
The description of roundCropper: 

"Set this to true for a round cropper. **Resulting image will still be square, use border-radius: 100% on resulting image to show it as round.**"

**Comment by loiddy** [comment]
Sorry, let me add a bit more to that. I didn't read your message properly. I didn't realise you tried border-radius: 100%.

A bit of background. I don't think round images exist. They are really squares/rectangles. You get the image in a circle shape, but all around it there is still image, it's just transparent. And it fills in the square/rectangle. Look at [this img for an example](https://www.mockofun.com/wp-content/uploads/2019/12/circle-image.jpg).

If you are looking for that, a round image with transparent around it, I don't see where this lib does that. It can be added tho. 

If you want an img that you are then going to display on a website and you want it to be round, you can add border-radius: 100% to it and it will be displayed as round. It will look like what you crop when roundCropper is true. But you have to add this to the outputted image, wherever it it that you are using it. To the lib you add [roundCropper]="true" , and to the outputted img style="border-radius: 100%".

Hope thats a bit more clear and it helps.

**Comment by krunalsk007** [comment]
thanks  for reply,  but i want image which is share by you as an [example ](https://www.mockofun.com/wp-content/uploads/2019/12/circle-image.jpg)
