### ISSUE TITLE
Crop not working correctly when zoom in and move the image

### ISSUE THREAD

**Issue by mariusoprea03** [Mawi137/ngx-image-cropper#545]
Hello,

I have encountered the following behavior.

I have the cropper configured in the following way:
`<image-cropper
        [imageChangedEvent]="imageChangedEvent"
        [maintainAspectRatio]="true"
        [containWithinAspectRatio]="false"
        [roundCropper]="true"
        [imageQuality]="100"
        [resizeToWidth]="260"
        [cropperMinWidth]="260"
        [onlyScaleDown]="true"
        [transform]="transform"
        [allowMoveImage]="true"
        format="png"
        (imageCropped)="imageCropped($event)"
        (imageLoaded)="imageLoaded()"
        (cropperReady)="cropperReady()"
        (loadImageFailed)="loadImageFailed()"
      >`

If I try to zoom in and move the image, let's say in an upper position, the cropped image is taken from the center and not from the position I moved the cropper.

Did I missed something in the config or this is really a problem?

I'm waiting for any feedback. Thanks in advance!

**Comment by MAGNUM81** [comment]
I might have a problem akin to this one...
@mariusoprea03 question: when you move the image (not the cropper, the background image), does it update the cropped image at all? For me it doesn't...
What I mean by this is the following: I moved the image to bottom of canvas, and preview still shows the cropped part where the image is *supposed* to be. See following screenshot using Bing logo.
![image](https://user-images.githubusercontent.com/15250750/218140072-5318486e-331f-4983-a0df-b1301219afa2.png)

**Comment by carlosedof** [comment]
up... its happening for me too

**Comment by montella1507** [comment]
Same problem here.

**Comment by Mawi137** [comment]
I don't seem to be able to reproduce the issue. Do you also have the issue when you checkout this project and run the demo app?

**Comment by aparkertg** [comment]
Hi I'm tracking this same issue. I'm allowing users to zoom in on the image to be cropped. The zoom is based on the center of the image, not on where the cropper is placed. If the user wants to zoom in on the edge of the picture, they need to move the image so the cropper can be placed over it (after zooming in).

As mentioned we set the config to allow the user to drag and move the image. Which works fine. If the user moves the cropper on the newly repositioned image, and crops it, they will not get a cropped image of what they are looking at.

The cropper's alignment is off when the image is moved. Please resolve.

**Comment by dabasejumper** [comment]
Hello Martijn,

Great package! Thank you for your hard work. 

Here are my steps to reproduce:

1. Upload the original image
![image](https://github.com/Mawi137/ngx-image-cropper/assets/8972286/ce17afc5-a246-48ce-bb41-4900eae12103)

2. Zoom and Move the Crop
![image](https://github.com/Mawi137/ngx-image-cropper/assets/8972286/6458cf93-dc53-42da-b981-3957c1a6dde1)

3. View issue after image is saved.
![image](https://github.com/Mawi137/ngx-image-cropper/assets/8972286/bdd9e0e1-1d92-4cdf-8d61-46467306ff27)

Here is the code I have given your component:
`<image-cropper [autoCrop]="false" [imageChangedEvent]="imageChangedEvent" [cropperStaticWidth]="width"
                [hideResizeSquares]="true" [cropperStaticHeight]="height" [roundCropper]="isRoundedCropper"
                [imageURL]="imageUrl" [transform]="transform" [canvasRotation]="canvasRotation" [allowMoveImage]="true"
                [output]="'blob'" [backgroundColor]="'#dedede'" [format]="'png'" (imageCropped)="imageCropped($event)"
                (imageLoaded)="imageLoaded()" (cropperReady)="cropperReady()"
                (loadImageFailed)="loadImageFailed()"></image-cropper>`

**Comment by MawsFr** [comment]
What's the value of your "transform" object ?

Here my tranform object :

```typescript

/* ... */

@ViewChild(ImageCropperComponent) cropper: ImageCropperComponent;
scale = 1;

get transform(): ImageTransform {
    return {
      ...this.cropper?.transform,
      scale: this.scale,
    };
  }

/* ... */
```

**Comment by Mawi137** [comment]
@dabasejumper I was able to reproduce the issue with your HTML.
To fix it you should use 2-way databinding on the `[(transform)]="transform"` attribute.
Like that the `transform` variable is also updated when you drag the image, else it will just back to the original position if you would change for example the scale in the `transform` object in your component. I can try to find a fix for this, but I recommend using 2-way databinding. I'll see if I can make this more clear in the readme.

**Comment by bardiaabasirad** [comment]
I am using Tailwindcss framework, which has placed style block for images. I solved the problem by adding this style, maybe your problem will be solved with this method.

``
img.ngx-ic-source-image {
  display: inline-block;
}
``

**Comment by MustafaMohamed2018** [comment]
it still zooming in then center of the image
