### ISSUE TITLE
Base64 empty on iOS

### ISSUE THREAD

**Issue by Robertndrei** [Mawi137/ngx-image-cropper#547]
I am cropping image files and after cropping, only at some random times, plugin returns invalid base64 url and cropped image won't generate. Valid cropped url contains over 50,000 characters base64 url but for bad base64 url returned from plugin, the string length is apprx 600 characters.

**Screen shots of successful and unsuccessful image crop:** 
<img width="441" alt="Screen Shot 2022-12-13 at 3 07 46 PM" src="https://user-images.githubusercontent.com/110682608/207441719-8b534bf7-d897-46c8-bb1b-a55bd6a41ae9.png">
<img width="441" alt="Screen Shot 2022-12-13 at 3 42 54 PM" src="https://user-images.githubusercontent.com/110682608/207441722-ce803984-abc8-4675-ba18-f71010c9b692.png">

**Technical details:**
 - Angular cli: v15.1.3
 - Ionic cli: v6.20.4
 - ngx-cropper-image: v6.3.2

**Device information:**
 - iOS: v15.1, v16.1.2; iPhone: 11 Pro Max (intermittent)
 - iOS: v16.1; iPhone: 11 xs max (always)
 - iOS: v16; iPhone: 8 (always)
 - iOS: v16.1.1; iPhone: 8 plus (always)

**Invalid image url:**
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAgKADAAQAAAABAAAAgAAAAABIjgR3AAABNklEQVR4Ae3QMQEAAADCoPVPbQwfiEBhwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwb+AwMAjwABWBXfzAAAAABJRU5ErkJggg==

_Originally posted by @oquadri in https://github.com/Mawi137/ngx-image-cropper/issues/481#issuecomment-1349678516_

**Comment by Robertndrei** [comment]
I found a workaround! I disabled `autoCrop` and used `crop` method.

**Comment by oquadri** [comment]
@Robertndrei  I did same and so far it seems to be working good.
@DianSSIE  it looks like cropper is not ready or image is not completely loaded by the time autocrop is called by plugin. Blank image was generated only if I don't resize cropper and just take cropped image as is in iOS.
I am showing cropper in an ion-modal so when user clicks on done only then I am manually calling plugin crop method. Hope that helps

**Comment by DianSSIE** [comment]
Just confirming that the workaround worked for me as well
