### ISSUE TITLE
Error occurs when using `containWithinAspectRatio` setting to crop large images on Firefox

### ISSUE THREAD

**Issue by Ch-Hamza** [Mawi137/ngx-image-cropper#548]
When attempting to crop large images with the containWithinAspectRatio setting on Firefox, an error occurs. This setting is used to transform the image to fit better with the specified aspect ratio. The error only appears on Firefox, as it works fine on other browsers.

I managed to reproduce the error on the demo-app in this repo, Steps to reproduce the error:

1 - Launch the demo-app on Firefox.
2 - Upload a large image (as shown in the screenshot)
<img src="https://user-images.githubusercontent.com/36152789/221930905-8d57dbd2-5250-436a-aea3-b28ea8e8701d.png" width="400">
3 - Click the Contain Within Aspect Ratio button to apply the setting.

Version information:

- Angular version: `13.3.11`
- ngx-image-cropper: `6.3.2`

To reproduce the error, please follow the steps above and observe the error that occurs.

**Comment by Mawi137** [comment]
The lib uses the HTML canvas to do these transformations. Each browser has different limits for what it allows when exporting it to a base64 url. So there's not really anything that can be done except for resizing the image before giving it to the image cropper.
