### ISSUE TITLE
How can we get resized image width and height in the canvas?

### ISSUE THREAD

**Issue by harirapuru** [Mawi137/ngx-image-cropper#55]
if the input image size is 1024*798 for cropping.when we load the image into canvas for cropping it will be resized according that.ho we can get the resized image  width*height?

**Comment by brunork26** [comment]
I found this asynchronous way,

```
const i = new Image();
i.onload = function(){
    alert( i.width + ', ' + i .height );
}
i.src = this.croppedImage;
```

In the source ( https://stackoverflow.com/questions/17774928/js-get-image-width-and-height-from-the-base64-code?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa ) , there is also a synchronous.

**Comment by harirapuru** [comment]
yes this will give width and height of the original image which i have given input.But i need displayed image width and height. I gone through inside code there is statement 

const displayedImage = this.elementRef.nativeElement.querySelector('.source-image');

this will give the displayed image width and height,On this displayed image we are doing actual cropping. the displayed image width and height changing for different size images differently. So hown can i access this displayed image size with height in my code?

**Comment by choskyo** [comment]
Do you mean the width/height values of the output image? If so you can make a viewchild on the <image-cropper> element and get the cropper's dimensions from viewChild.cropper. Alternatively fork the repo and change the output, I did that [here](https://github.com/choskyo/ngx-image-cropper/commit/14e98f36352d2339fc14e86eccb6caed406edb96) as an example before I realised I didn't have to.

https://angular.io/api/core/ViewChild

**Comment by Mawi137** [comment]
Hi @harirapuru 
After the `imageLoaded` event, you can also use `this.eRef.nativeElement.querySelector('.source-image')` to get the element from outside the image-cropper. `clientWidth` and `clientHeight` are available on that element.
