### ISSUE TITLE
Big size image cannot be traced

### ISSUE THREAD

**Issue by imotality** [Mawi137/ngx-image-cropper#551]
Hello. i found an issue that we can't actually control the event when image load has been started and finished. Like when we are passing the [imageURL] argument. that function in your source code doesn't emit any start and end loading event. Is there any way it to be fixed?

**Comment by Mawi137** [comment]
It starts loading when you pass it the image url and it emits `imageLoaded` when finished. So that should be enough if you want to show a spinner for example.
