### ISSUE TITLE
Performance leak while loading and cropping

### ISSUE THREAD

**Issue by imotality** [Mawi137/ngx-image-cropper#552]
In case of cropping or passing through the image URL application might instantly die. The problem was found on the ToDataURL().
I have tested it and want to ask you to rewrite it using blob. I can share you the forked code
<img width="741" alt="image" src="https://user-images.githubusercontent.com/27500883/229894272-0797c1f0-f68e-404f-8e6a-7e83dcbecdaa.png">

**Comment by Mawi137** [comment]
I was curious so I already changed it myself and it now seems to be possible to crop much larger images! That's something this lib needed for a long time already, so thank you very much for that ;)

I'll try to rework it in the coming days, because it does give some breaking changes.

**Comment by Mawi137** [comment]
It had a bigger impact than I expected, but everything has been changed to use the `toBlob` instead of `toDataURL`. Released under version `7.0.0`.

**Comment by imotality** [comment]
glad it helped!
