### ISSUE TITLE
Is it possible to load an image into the image-cropper via code?

### ISSUE THREAD

**Issue by tonyashah** [Mawi137/ngx-image-cropper#56]
I have a service that that returns a URL to an image & I want that image loaded up to crop (vs. using the file input button to load the image).   I am not seeing a way to do this with this library, but maybe I am missing something?

**Comment by limbo93** [comment]
I have captured an image through webcam. I tried the following. But failed to load the image in cropper. It's just loaded in the preview.

capture() {
        let video = this.webcam.video;
        this.canvas.nativeElement.getContext("2d").drawImage(video.nativeElement, 0, 0, video.nativeElement.offsetWidth, video.nativeElement.offsetHeight);
        let imgUrl = this.canvas.nativeElement.toDataURL("image/jpeg");
        let image: any = new Image();
        image.src = imgUrl;
        this.webcam.stop();

        let blob = this.makeblob(imgUrl);
        let file = new File([blob], "image.jpg");
        this.imageFileChanged = file;
}
