### ISSUE TITLE
Crop is missing a few px when width is defined

### ISSUE THREAD

**Issue by williamlambert-jc** [Mawi137/ngx-image-cropper#561]
In some edge-cases the crop will miss a few px if the image-cropper is constrained with a specific `width`, it's difficult to reproduce but I got it on [this stackblitz](https://stackblitz.com/edit/stackblitz-starters-4ohpc6?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=src%2Fmain.ts&title=Angular%20Starter)

When drop-and-droping the crop zone below the image-cropper (to crop the bottom of the image) the cropped dimensions are 1124x599 while the `cropperMinHeight` is set to 600

![ngx-cropper-bug](https://github.com/Mawi137/ngx-image-cropper/assets/76045417/1ccb3433-c241-4816-9b99-fe0205cd0430)

The issue will **not** happen when defining the width of `image-cropper` to `450px` or `550px` but **will** happen with width `500px`

**Comment by Mawi137** [comment]
Fixed in version 7.1.0
