### ISSUE TITLE
New blob output is always of type 'png'

### ISSUE THREAD

**Issue by Sergiobop** [Mawi137/ngx-image-cropper#564]
Even though the new default output #556 is nice, it always returns a blob of type 'image/png' causing some files to increase size in large amounts.

I think the blob should respect (whenever is possible) the 'format' of the original file. If the format is 'jpeg', the blob type should be 'image/jpeg', not png.

When the output is base64, i achieved this using your base64ToFile helper (since that method respects the original file type ```return new Blob([ab], {type});```

**Comment by Mawi137** [comment]
It seems that's indeed a little bug. Fixed in version `7.0.1`.

Thanks for reporting!
