### ISSUE TITLE
Not getting Base64 object

### ISSUE THREAD

**Issue by Shalil-j** [Mawi137/ngx-image-cropper#565]
im facing the issue of not getting base64 object 

![image](https://github.com/Mawi137/ngx-image-cropper/assets/56194185/ca4bcc76-544b-4025-a327-88a75ccdf51c)

here is my code
![image](https://github.com/Mawi137/ngx-image-cropper/assets/56194185/503239dc-8157-4840-af0b-63fba321bbab)

**Comment by mivanyna** [comment]
which version?

**Comment by mivanyna** [comment]
Maybe this will help?
https://github.com/Mawi137/ngx-image-cropper/releases/tag/7.0.0

**Comment by Shalil-j** [comment]
thank you , its working 🙏

**Comment by Shalil-j** [comment]
...
