### ISSUE TITLE
How to keep current cropper? also set options dynamically?

### ISSUE THREAD

**Issue by webcat12345** [Mawi137/ngx-image-cropper#57]
I am using this library for cropper and canvas for rotate.
Once rotate is finished then the base64 code also being changed. at moment, library reset the cropper to the startup point and we lost everything, I would like to keep the current cropper and set it after rotated image loaded. 

I have tried to manually set cropper using viewchild but didn't get it working.

also another topic is just want to set cropper ratio dynamically, but ratio change is not reflected to the view. If i tries to crop again then the cropper ratio reflected. any solution for these problems? 

Thank you

**Comment by darSynereo** [comment]
I have the same problem when i try to dynamically change the aspectRatio.
even if i use a variable there before the image upload i breaks.

![screen shot 2018-06-28 at 11 02 26](https://user-images.githubusercontent.com/28061538/42021272-db16da66-7ac2-11e8-8fef-28f8c6b17f4e.png)

any news?

thanks

**Comment by stoto34** [comment]
Any news about this ?

**Comment by Mawi137** [comment]
Changing the aspectRatio should be solved now. As for the rotating, I'm planning on adding it to the image cropper itself so it can keep the cropper's position. #87

**Comment by seriana** [comment]
Any news about the rotation?

**Comment by dreemhai** [comment]
Hello, any news about this?
