### ISSUE TITLE
Not working with firefox browser 116.0.2

### ISSUE THREAD

**Issue by Panic7** [Mawi137/ngx-image-cropper#575]
I use 
- ngx-image-cropper 5.0.2
- angular cli 10.1.4
And it works fine in other browsers, but with firefox I can't upload a large image like 20MB:
error { target: img, isTrusted: true, srcElement: img, eventPhase: 0, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, timeStamp: 16630, … }
​
bubbles: false
​
cancelBubble: false
​
cancelable: false
​
composed: false
​
currentTarget: null
​
defaultPrevented: false
​
eventPhase: 0
​
explicitOriginalTarget: <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAF4AA…">
​
isTrusted: true
​
originalTarget: <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAF4AA…">
​
returnValue: true
​
srcElement: <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAF4AA…">
​
target: <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAF4AA…">
​
timeStamp: 16630
​
type: "error"
​
<get isTrusted()>: function isTrusted()
​
<prototype>: EventPrototype { composedPath: composedPath(), stopPropagation: stopPropagation(), stopImmediatePropagation: o()
, … }
[main-es2015.7b57a35c598fbbfdacc0.js:1:1167081](https://eticket.yukon.cv.ua/main-es2015.7b57a35c598fbbfdacc0.js)

**Comment by Mawi137** [comment]
In the latest version the code was optimised which might resolve this issue. If not, I suggest using another lib to first resize large images before giving them to the image cropper.
