### ISSUE TITLE
Issues Encountered When Uploading Two Incorrect Images

### ISSUE THREAD

**Issue by thomas-chu-30** [Mawi137/ngx-image-cropper#577]
I uploaded two incorrect images in a row. However, the second time I didn't enter the loadImageFailed event. But, if I upload a correct image and then upload an incorrect image again, it triggers the loadImageFailed event once more. Why does this happen?

```
"ngx-image-cropper": "^7.0.2",
```

**Comment by Mawi137** [comment]
Did you use the image change event and was it the same image that you used? It should trigger again if you use a different image.
