### ISSUE TITLE
Assistance on implementation

### ISSUE THREAD

**Issue by jongbonga** [Mawi137/ngx-image-cropper#582]
When implementing the cropper on a page, everything works fine.

When the same implementation is moved inside a component and imported inside the above page, I get the below error on `imageCropped`

<img width="790" alt="Screenshot 2023-09-07 at 16 10 52" src="https://github.com/Mawi137/ngx-image-cropper/assets/12111716/019f7d60-13c1-46ed-a955-e6a4266537f7">

The component 
```
<image-cropper
  #cropper
  [imageBase64]="myImage"
  [maintainAspectRatio]="true"
  format="jpeg"
  [roundCropper]="true"
  [hideResizeSquares]="isMobile"
  [transform]="transform"
  [autoCrop]="false"
  [hidden]="!myImage"
  (imageCropped)="imageCropped($event)"
  (loadImageFailed)="loadImageFailed()"
  (imageLoaded)="imageLoaded()"></image-cropper>
```
  
  Accessed with `@ViewChild('cropper') cropper: ImageCropperComponent;`

**Comment by Mawi137** [comment]
Try using two-way databinding on the transform property: `[(transform)]="transform"`.
