### ISSUE TITLE
Blob output is too large when png format is selected

### ISSUE THREAD

**Issue by defra91** [Mawi137/ngx-image-cropper#583]
I noticed that when you select png as format the Blob output is very large. If I select jpeg format the blob size is normal.

**Comment by Mawi137** [comment]
That is the behaviour of the HTML canvas which is used to crop the images. Nothing that I can do about that.

**Comment by defra91** [comment]
Thank you very much for your reply. I was just wondering why this behavior occurs when the forma is 'png' but it does not when the format is 'jpeg'. Only a curiosity.

**Comment by Mawi137** [comment]
I think the main reason is that jpeg doesn't include transparency (alpha) while png does. So for a png image an extra byte is added for each pixel.

**Comment by OssFit** [comment]
I found the same issue and I fixed creating a variable for the output format(the same input format, the same output)
like this in the component where we use the cropper:

const typeFile = this.ImageFile.type;
const extensionFileArray = typeFile.split('/');
const extensionFile = extensionFileArray[1];
const dialogRef = this.dialog.open(ImageCropperComponent, {
data: {
data: file,
aspectRatio: 1,
},
maxWidth: '400px',
});
dialogRef.closed.subscribe((blob) => {
if (!blob) return;
const newBlob = new Blob([blob as BlobPart]);
const file = new File([newBlob], 'croppedImage.' + extensionFile, {
type: typeFile,
});
this.ImageFile = file;

and the same in the format property in the image cropper tag.
