### ISSUE TITLE
Change Detection runs on every mousemove

### ISSUE THREAD

**Issue by rbrewer-echelon** [Mawi137/ngx-image-cropper#589]
I'm profiling my application with the Angular Dev Tools, and it shows that change detection is firing on every mousemove event.... This is a really big performance drain. 

I traced it down to this package, the problem goes away when I comment our cropper out. 

I see this commit was proposed but not accepted `zetti-caletti:perf/change-detection` -- https://github.com/Mawi137/ngx-image-cropper/pull/526 

is there a reason not to do this? Its a big problem in our app, making changeDetectionStrategy.OnPush completely pointless.

Is there something else we can do to keep this from occuring?

**Comment by Mawi137** [comment]
It can indeed be improved, I made a suggestion to the person that opened that PR, but he never replied so the PR got closed. I'll look into it so that it only listens on mouse move when you clicked on the cropper.

**Comment by Mawi137** [comment]
Should be fixed in version 7.1.0.  I replaced the HostListeners with rxjs streams that only start listening once you click on the cropper. Let me know if it fixed the issue.

**Comment by rbrewer-echelon** [comment]
will do! thanks
