### ISSUE TITLE
CrossOrigin for imageBase64

### ISSUE THREAD

**Issue by mdlia** [Mawi137/ngx-image-cropper#59]
We have a problem when we try to use image base 64 from external url.
Code used : 
imageUrl = http://[external-url]/program/photo/28291/28291-1-original-photo.jpg
<image-cropper
      [maintainAspectRatio]="true"
      [aspectRatio]="16 / 9"
      [resizeToWidth]="128"
      format="jpeg"
      [imageBase64]='imageUrl'
    ></image-cropper>

ERROR DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

Solution: 
Add this.originalImage.crossOrigin ='Anonymous'; in loadBase64Image function 
or adding an input ( @Input() crossOrigin = null; ) and use it in the same function.

Thank you.

**Comment by AhmedBoustani** [comment]
[imageBase64] expects a string representation of the file image. What you're giving it is a url to the image. You should download it either as base64 or as a file and give it to the image-cropper under the right attribute
