### ISSUE TITLE
Reset cropper with a base64 image

### ISSUE THREAD

**Issue by k0nsun** [Mawi137/ngx-image-cropper#597]
A default image is set to "imageBase64" on load.
After loading another image by the event "fileChangeEvent" (file upload), i want to save the current file and reload the default image.
The default image is not loaded when "imageBase64" is set again.

Steps:
1. open https://stackblitz.com/edit/image-cropper-4a6sdf7
2. open any image
3. click on "Save and reload"

The cropper keep the actual image.

**Comment by loiddy** [comment]
Hi, that's because you never changed the imageBase64 value so angular can't detect any changes that then trigger loading a new image. You could set imageBase64 to a string in fileChangedEvent, for example, or in imageLoaded.

**Comment by k0nsun** [comment]
I see your point.

I modified this:
`this.imageBase64 = MockData.DEFAULT_IMG;`
in this:
`this.imageBase64 = new String(MockData.DEFAULT_IMG) as string;`

and it's works !

Thanks for your help.
