### ISSUE TITLE
Import issues when upgrading to version 7.1.1 using rxjs version 6.6.0

### ISSUE THREAD

**Issue by johnypremanantham** [Mawi137/ngx-image-cropper#598]
When upgrading to Angular 16, i get the following issue when trying to run my project:

./node_modules/ngx-image-cropper/fesm2020/ngx-image-cropper.mjs:1302:83-92 - Error: export 'takeUntil' (imported as 'takeUntil') was not found in 'rxjs'

**Comment by Mawi137** [comment]
Which version of rxjs are you using?

**Comment by johnypremanantham** [comment]
Sorry, correction on my post. The issue occured when i updated the ngx-image-cropper library to version 7.1.1. I just tried downgrading to 6.3.4 then it worked. My rxjs version is: "rxjs": "~6.6.0"

**Comment by nicodeboer76** [comment]
Also import errors. We are using Angular 15.1 and rxjs version 6.6.7.
Can't you change the import line in image-cropper.component.ts from:

import { first, fromEvent, merge, takeUntil } from 'rxjs';
to:
import { merge, fromEvent } from 'rxjs';
import { first, takeUntil } from 'rxjs/operators';

to fix the problem?

**Comment by Mawi137** [comment]
Any reason why you aren't updating to rxjs 7?

In any case I updated the imports and release version `7.1.2`.
