### ISSUE TITLE
Setting base64 of the image in [imageBase64] input not working 

### ISSUE THREAD

**Issue by vishwasreddy89** [Mawi137/ngx-image-cropper#60]
Hi Team,

I am trying to pass base64 image as input but its not working properly i can see image is coming without any coordinates of cropper i tried giving coordinates inputs also .It is not working please help me to resolve this issue .Its Very Urgent.Anything else i am missing pls let me know.Any example plunker will also be help full.Passing string of base64.

Thanks,
Vishwas Reddy,
vishwasreddy89@gmail.com

**Comment by AhmedBoustani** [comment]
Is this still relevant?
I tried it with Base64 and it worked fine. Could you comment the code you're using? Also, have you tried with event and worked but switching to base64 didn't?

In any case here's how I implemented it.
in .component.ts:
```
  // Since I use input to get the image, I turn the file into base64
  // and send it as input to the image-cropper
  fileChangeEvent(event: any): void {
    const myReader = new FileReader();
    myReader.onloadend = (e) => {
      this.imageToCrop = myReader.result;
    };
    myReader.readAsDataURL(event.target.files[0]);
    console.log(this.imageToCrop);
  }
```

Then, in the .html
```
<input type="file" (change)="fileChangeEvent($event)" />

<image-cropper
  [imageBase64]="imageToCrop"
  [maintainAspectRatio]="true"
  [aspectRatio]="4 / 3"
  [resizeToWidth]="128"
  format="png"
  (imageCroppedBase64)="imageCropped($event)"
  (imageLoaded)="imageLoaded()"
  (loadImageFailed)="loadImageFailed()"
></image-cropper>

<img [src]="croppedImage" />
```
