### ISSUE TITLE
base 64 output is empty

### ISSUE THREAD

**Issue by subhajitwiner** [Mawi137/ngx-image-cropper#605]
when i tried to get event output from 
imageCropped(event:ImageCroppedEvent){
// if I take bloob its fine working good but when I tried to get base 64 it didn't give any output
 console.log(event.blob) // working fine
 console.log(event.base64) // returning empty data 

}

**Comment by Mawi137** [comment]
Did you set the output to base64? By default it's set to blob because it has better performance.

**Comment by edubaldin13** [comment]
I'm actually facing the same problem, commenting here awaiting for the fix, now I'm at work but as I get home gonna try to find the error

**Comment by edubaldin13** [comment]
GN guys, hope you're well, I've just the code and found how to make it work for base64, I made it goes fine at work today and tried on the demo-app and worked, it seems to have a problem on cropper when the return type is base64 (but at work worked fine) so this is how to make it run
![image](https://github.com/Mawi137/ngx-image-cropper/assets/37090072/6bab75b8-f1a7-42b2-b294-89746ad8dea4)

**Comment by komendantaa** [comment]
```
simply add output="base64" to the <image-cropper>
```
https://github.com/Mawi137/ngx-image-cropper/releases/tag/7.0.0

Is this what you are looking for?

**Comment by Hansel03** [comment]
You only have to add this parameter in the html component


  <image-cropper
  output="base64"
  >
   </image-cropper>
