### ISSUE TITLE
crop() should be a Promise

### ISSUE THREAD

**Issue by rbalet** [Mawi137/ngx-image-cropper#606]
using the `crop()` method, I do see that this does return a promise

## ToDo
* Add the correct type to the method return value

**Comment by Mawi137** [comment]
It depends on what the output type is: https://github.com/Mawi137/ngx-image-cropper/blob/ab3ab64439202696354b5bf876f2d22ebd59a0ff/projects/ngx-image-cropper/src/lib/component/image-cropper.component.ts#L579

**Comment by rbalet** [comment]
@Mawi137 Thx Mawi137. Closing the issue
