### ISSUE TITLE
How to disable this warn: Could not find HammerJS - Pinch Gesture won't work

### ISSUE THREAD

**Issue by ronaldohoch** [Mawi137/ngx-image-cropper#618]
Hi guys, thanks for the project :D

Is there a way to disable this warn? It shows up in test.

![image](https://github.com/Mawi137/ngx-image-cropper/assets/2287371/9cbb8b0e-5c7c-45db-8da7-4fd7463dc057)

**Comment by Mawi137** [comment]
In the latest version, hammerjs was removed.
