### ISSUE TITLE
Cropper Position is not working

### ISSUE THREAD

**Issue by adi-wtag** [Mawi137/ngx-image-cropper#638]
Hello, 
I am using cropper 8. For me, everything is working properly except provided cropper position. 

```
    <image-cropper
      [imageFile]="url"
      [maintainAspectRatio]="true"
      [containWithinAspectRatio]="containWithinAspectRatio"
      [aspectRatio]="aspectRatio"
      [cropperStaticHeight]="150"
      [cropperStaticWidth]="150"
      [cropper]="cropperPosition"
      [(transform)]="transform"
      [style.display]="showCropper ? null : 'none'"
      (imageCropped)="imageCropped($event)"
      (imageLoaded)="imageLoaded($event)"
      (cropperReady)="cropperReady($event)"
      (loadImageFailed)="loadImageFailed()"
    ></image-cropper>
    
  cropperPosition: CropperPosition = {
    x1: 206,
    x2: 356,
    y1: 54,
    y2: 204
  };
```

But the cropper  position is not working. the initial position is always top left corner on {x1: 0, x2: 150, y1: 0, y2: 150}. Any help is highly appreciated. Thanks.

**Comment by Mawi137** [comment]
Hi
This will be fixed in the next release. I'm working on a replacement for HammerJS, after that I will make a new release.
For now what you can do it wait for the imageLoaded to have emitted and then set the cropperPosition in a `setTimeout`.
