### ISSUE TITLE
ImageCroppedEvent has set blob to null

### ISSUE THREAD

**Issue by I1C** [Mawi137/ngx-image-cropper#639]
When I upload an image from ios, the image cropped event has set blob to null. If I make the crop smaller, then I have a blob.

Do you know how can I fix it?

Thank you!

**Comment by Mawi137** [comment]
This component uses the HTML canvas which has it's limitations. I'm guessing your image it too large initially.

**Comment by I1C** [comment]
Yeah, you are right. Thank you very much!
