### ISSUE TITLE
ngx-image-cropper not able to show image due to Content Security Policy (CSP) issue in angular app

### ISSUE THREAD

**Issue by iamsandeepkmr** [Mawi137/ngx-image-cropper#658]
**Error:** Refused to load the image 'blob:https://<example.com>/42ab5bb8-7920-4aff-8d6a-630df8795cb7' because it violates the following Content Security Policy directive: "img-src * 'self' data: *". Note that '*' matches only URLs with network schemes ('http', 'https', 'ws', 'wss'), or URLs whose scheme matches `self`'s scheme. The scheme 'blob:' must be added explicitly.

I tried to include the policy in meta tag like this `<meta http-equiv="Content-Security-Policy" content="img-src 'self' data: blob: *;">`
Still issue is not resolved.

ngx-image-cropper version used: 7.2.1

**Comment by Mawi137** [comment]
If you have a CSP header, that will take precedence over the meta tag. If not, your meta tag appears correct to me, so I have no idea why it shows that error.
