### ISSUE TITLE
Breaking change: public method resetCropperPosition() removed from image-cropper.component.ts  in release 8.1

### ISSUE THREAD

**Issue by bernhardkircher** [Mawi137/ngx-image-cropper#659]
Hello,

it seems that after upgrading to Version 8.1 the previously public method resetCropperPosition() has been removed with this change:
https://github.com/Mawi137/ngx-image-cropper/commit/9e968b4c2f7288819735263c9b22c9b3d1420d82

It is available in Version 8.0.

It seems that it has been replaced by checkCropperWithinCropperSizeBounds() but this one seems not to be available when I install Version 8.1.

I am not sure if this was intentional or the error is on my side. If this was intentional, is there a recommended replacement?

Thank you for your feedback and great work!

Best,
Bernhard

**Comment by Mawi137** [comment]
Hi @bernhardkircher

I put the `resetCropperPosition` back and released version `8.1.1`.
