### ISSUE TITLE
how to get cropper co-ordinates?

### ISSUE THREAD

**Issue by omretterry** [Mawi137/ngx-image-cropper#66]
how to get cropper co-ordinates. I want get the value output from the plugin.i only find the way to set the coordinates.

**Comment by AhmedBoustani** [comment]
According to the docs, you can get the coordinates by creating a new object {x1: number, y1: number, x2: number, y2: number } and set it as input to the package under crop parameter. Any change through mouse movements will be recorded in the attributes in the object without changing it (pass by reference). thus, you will have the final coordinates in the object that you gave it. Let me know if that works for you.

**Comment by omretterry** [comment]
it works, thks a lot
