### ISSUE TITLE
how to convert BASE64 to normal image url 

### ISSUE THREAD

**Issue by DamithaPerera** [Mawi137/ngx-image-cropper#69]
I'm trying to convert base64 to normal image url using angular 4. I found a solution 
```
`  dataURItoBlob(dataURI)  {
    // convert base64/URLEncoded data component to raw binary data held in a string
    let byteString;
    if (dataURI.split(',')[0].indexOf('base64') >= 0)
      byteString = atob(dataURI.split(',')[1]);
    else
      byteString = unescape(dataURI.split(',')[1]);

    // separate out the mime component
    const mimeString = dataURI.split(',')[0].split(':')[1].split(';')[0];
```

    // write the bytes of the string to a typed array
    const ia = new Uint8Array(byteString.length);
    for (let i = 0; i < byteString.length; i++) {
      ia[i] = byteString.charCodeAt(i);
    }

    return new Blob([ia], {type: mimeString});
  }
`
but the problem is it changes the image url format. ("..../public/uploads/offers/1531895217034CxqrY.blob") 

`
```
imageCropped(image: string) { 
this.croppedImage = image; 
this.BASE64 = this.dataURItoBlob(image); 
console.log('BASE64 => ', this.BASE64 ); 
this.imageData = this.BASE64; 
}
```
`

this.imageData is the variable that i pass through the API

this is the response 
`BASE64 => Blob(116234) {size: 116234, type: "image/png"}
 size:116234 
type:"image/png" 
__proto__:Blob`

**Comment by Mawi137** [comment]
So you need a file instead of the base64 string? In version 1.0.1 you can use the `imageCroppedFile` output to get that.

**Comment by Sathishchary** [comment]
I have installed the ngx-image cropper 1.0.1 only but still its showing "Blob(116234) {size: 116234, type: "image/png"} size:116234 type:"image/png" __proto__:Blob", its not file object, 

I have used the imageCroppedFile  only.



```
<input type="file" (change)="fileChangeEvent($event)" />

<div>
  <image-cropper
    
      [imageChangedEvent]="imageChangedEvent"
      [maintainAspectRatio]="true"
      [aspectRatio]="4 / 3"
      [resizeToWidth]="128"
      format="jpeg"
      (imageCroppedFile)="imageCroppedFileObj$event)"
      (imageLoaded)="imageLoaded()"
      style="max-height: 33vh"
      [style.display]="cropperReady ? null : 'none'"
  ></image-cropper>
</div>
<img [src]="croppedImage" />
```

 ```
fileChangeEvent(event: any): void {
      this.imageChangedEvent = event;
  }
  imageCroppedFileObj(image: any) {
      this.croppedImage = image;
      console.log(this.croppedImage);
  }
  imageLoaded() {
    this.cropperReady = true;
  }
  imageLoadFailed () {
    console.log('Load failed');
  }
```

how do i get the file object?

**Comment by Mawi137** [comment]
A Blob should work for that, there is no way for the cropper to return a File: https://developer.mozilla.org/en-US/docs/Web/API/Blob
