### ISSUE TITLE
In case of invalid image loadImageFailed not called

### ISSUE THREAD

**Issue by zsole** [Mawi137/ngx-image-cropper#71]
Hi,

Thanks for the component, works quite fine. The only thing we realized is that when you load a picture that is invalid (e.g. empty file, renamed to "invalid.gif"), loadImageFailed event is not called.

loadImageFile fails at row:, this.checkExifRotationAndLoadImage(event.target.result); 
Its inside an async method already, so catching error outside, is not easy.

Could you fix this?

Thanks.

**Comment by Mawi137** [comment]
Hi, this should be fixed in 1.2.1
