### ISSUE TITLE
png to jpeg,background transparent to black?how to bg to white?

### ISSUE THREAD

**Issue by Songux** [Mawi137/ngx-image-cropper#72]

**Comment by Songux** [comment]
![96-512](https://user-images.githubusercontent.com/33338721/43274137-833c72ac-9128-11e8-9cd2-e4cb080f2c65.png)
after 
![background](https://user-images.githubusercontent.com/33338721/43274273-f2d99e14-9128-11e8-8b31-b0eeab7baf35.png)
How to make background transparent convert white?

**Comment by robinnau** [comment]
i forked it and added the ability to change the background color of the canvas 
https://github.com/robinnau/ngx-image-cropper
