### ISSUE TITLE
Add Release Notes and Tags

### ISSUE THREAD

**Issue by matthiasbaldi** [Mawi137/ngx-image-cropper#73]
Would it be possible, that you add release notes and a tagging?
It would be easier to detect changes like the last one I met while updating to your newest version.
`imageCropped` --> `imageCroppedBase64`

Thanks a lot and very good work for this Angular module 👍

**Comment by Mawi137** [comment]
Just added a release for the 1.1.0 update, I'll keep doing that in the future ;)
