### ISSUE TITLE
Edge Browser - TypeError: Object doesn't support property or method 'toBlob'

### ISSUE THREAD

**Issue by matthiasbaldi** [Mawi137/ngx-image-cropper#74]
Hi

In the actual newest version of ngx-image-cropper: (1.0.1) I detected in Edge (Microsoft Edge 42.17134.1.0) the following Error:

```
ERROR TypeError: Object doesn't support property or method 'toBlob'
[object Error]: {description: "Object doesn't support property or method 'toBlob'", message: "Object doesn't support property or method 'toBlob'", number: -2146827850, stack: "TypeError: Object doesn't support property or method 'toBlob' at t.prototype.crop
```

In Chrome it works without any problems.

I think the issue is in the following Line of Code:
https://github.com/Mawi137/ngx-image-cropper/blob/a7d4ab329a58f01f6b2bc439f59bf135cbc42777/src/image-cropper.component.ts#L431

A possible Solution, I found here:
https://stackoverflow.com/questions/47475647/canvas-to-blob-on-edge

**Comment by matthiasbaldi** [comment]
I tested it shortly in my project - if you include the package form https://github.com/blueimp/JavaScript-Canvas-to-Blob as mentioned in the StackOverflow article, it will work.

I added the following line to my polyfills.ts, after a `npm install blueimp-canvas-to-blob`:
`import 'blueimp-canvas-to-blob/js/canvas-to-blob.min.js';`

I think that would be the easiest way to fix it.
Wdyt @Mawi137 ?

**Comment by dly5891** [comment]
@matthiasbaldi This just saved me from so many issues. Did you have to make those changes to your polyfill.ts or did you just install the package? I know its been a few months since you posted your answer. No worries if you don't remember.

**Comment by Mawi137** [comment]
For Edge a polyfill is needed indeed: 
```
if (!HTMLCanvasElement.prototype.toBlob) {
  Object.defineProperty(HTMLCanvasElement.prototype, 'toBlob', {
    value: function (callback, type, quality) {
      var dataURL = this.toDataURL(type, quality).split(',')[1];
      setTimeout(function() {

        var binStr = atob( dataURL ),
            len = binStr.length,
            arr = new Uint8Array(len);

        for (var i = 0; i < len; i++ ) {
          arr[i] = binStr.charCodeAt(i);
        }

        callback( new Blob( [arr], {type: type || 'image/png'} ) );

      });
    }
  });
}
```
Source: https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob

Or, in version 1.2.0+ you can choose to only get the base64 so it no longer uses the `toBlob` method.

**Comment by matthiasbaldi** [comment]
@Mawi137 Thank you for your information about the base64 output option.
I fixed my issue to use the base64 output. This is the absolut correct way for me.

**Comment by ankitvadariya** [comment]
@Mawi137 you just save my day. Thanks a lot
