### ISSUE TITLE
Can't set image extension/type dynamically

### ISSUE THREAD

**Issue by studentitm** [Mawi137/ngx-image-cropper#75]
I am trying to make the image format dynamic, according to the extension of image uploaded.
But it takes png by default, if not specifically provided. Is there a way to make it dynamic with the current code?

**Comment by Mawi137** [comment]
You could load the image before giving it to the cropper to determine the mime type and pass it to the image cropper. I might add it to the cropper itself.

**Comment by studentitm** [comment]
@Mawi137 Thanks! I implemented it as you suggested.
