### ISSUE TITLE
Add an example where emiting the file requires user interaction (upload button click)

### ISSUE THREAD

**Issue by jedgrant** [Mawi137/ngx-image-cropper#78]
@Mawi137 , apologies if this is the wrong way to ask this. 

This thing works great, but Ideally, I want to upload the file after the user adjusts the frame. Right now, I can get the imageCroppedFile the moment the frame is shifted, but I don't know how to attach that to an "upload" button. Any chance you could add a small example to the documentation for this or if it's something everyone already knows how to do, shoot me a link and close this?

**Comment by Mawi137** [comment]
You can either use the base64 and send that to your backend or to use a file I found this: https://stackoverflow.com/questions/40214772/file-upload-in-angular
But it depends on the implementation of your backend.
