### ISSUE TITLE
In addition to file-type validation, could add a file size validation?

### ISSUE THREAD

**Issue by yoonjesung** [Mawi137/ngx-image-cropper#79]
Not sure if there are any other validations that are useful, but file size is the one that comes to mind.

Can add an input for maxFileSize and do a check when reading the file.

When emitting the loadImageFailed event, instead of emitting void, could emit a string or object to represent the reason for failure.

If you'd like I can create a PR.

**Comment by ovyshnivskyi** [comment]
Agree, does file size restriction implemented?

**Comment by Mawi137** [comment]
Hi, I don't think that's something to be handled by the image cropper, you can easily do that outside of the image cropper using the results returned by either `imageCroppedBase64` or `imageCroppedFile`.
