### ISSUE TITLE
Feature: more touch friendly

### ISSUE THREAD

**Issue by jpduckwo** [Mawi137/ngx-image-cropper#81]
Awesome job on the module! I've just managed to migrate from another library very quickly so thanks for your work.

I think it would be great to make the cropper box a little more touch friendly some ideas might be:
* make the edge squares larger and maybe into circles to facilitate easier grabbing on a touch device
* putting cross move icon overlaid on the cropper box to show it's moveable (you don't see the cursor on the touch devices)

I don't think these things would detract from the current experience on desktop.

Cheers, Joel

**Comment by gloriousjob** [comment]
I've added this to my styles.scss to make the squares larger (making them circles doesn't do much in my mind but add border-radius: 50% if you want that):

// Make the image cropper a little more touch friendly
@media (hover:none), (hover: hover) and (pointer: coarse) {
	image-cropper .square {
		height: 10px!important;
		width: 10px!important;
	}
}
