### ISSUE TITLE
Integrate with smartcrop 

### ISSUE THREAD

**Issue by nicholassinggih** [Mawi137/ngx-image-cropper#82]
Hi all,

This is a feature request. 

Is there an easy way to integrate with smartcrop? Just a brief intro, smartcrop is a js lib that outputs the best candidate for face detection or any other locust (not just human face) in a photo. It outputs a canvas with a box surrounding what it thinks is the face of a person. 

My thought is to allow ngx-image-cropper to use smartcrop as a plugin to provide the best initial box for cropping. 

https://github.com/jwagner/smartcrop.js

I guess, without having read the whole docs on smartcrop & ngx-image-cropper, technically one can take the numbers output by smartcrop, and use those numbers as the coordinate of the initial crop box as input to ngx-image-cropper. 

But it will be great if ngx-image-cropper can do that automatically, simply by having the dev to specify smartcrop as a plugin.

Thanks.

**Comment by Mawi137** [comment]
Looks cool! However, I also think that if you want to use it, you can easily do that outside of the image cropper, like you said.

**Comment by vishnu-dev** [comment]
@Mawi137 I was not able to set the `[cropper]` input using the output from `smartcrop`. I want to dynamically set the cropper after processing. My current implementation is something like this

```
const crop = await smartCrop.crop(image);
    this.cropper = {
      x1: crop.topCrop.x,
      y1: crop.topCrop.y,
      x2: crop.topCrop.x + crop.topCrop.width,
      y2: crop.topCrop.y + crop.topCrop.height
    };
    console.log(this.cropper);
    this.image = item.file.rawFile;
    this.showCropper = true;
```

**Comment by vishnu-dev** [comment]
Indeed it's a relative image problem as mentioned in #220
