### ISSUE TITLE
rectangle image sizes is there away to dynamically add white space top and bottom of the picture

### ISSUE THREAD

**Issue by hadi-roudaki** [Mawi137/ngx-image-cropper#83]
I got this issue with cropping rectangle images, basically, I want to crop images to a square ratio and  I need the cropping to stretch and move off the the image size 
![screen shot 2018-08-24 at 9 24 50 am](https://user-images.githubusercontent.com/6867867/44558912-11c13400-a78a-11e8-976c-04ab2e66e1bb.png)

is there anyway to add white space to top and bottom of the pictures to match the width to the height and then apply cropping, ill take any suggestions

**Comment by Mawi137** [comment]
That would involve some code changes, but I like the idea to be able to have the image width and height match the aspect ratio.

**Comment by captaincaius** [comment]
PRing today :)
