### ISSUE TITLE
Image size need it!

### ISSUE THREAD

**Issue by nichapps** [Mawi137/ngx-image-cropper#86]
Hi!

These days i'v installed your package.
I was wondering if you can add an output whit the dimentions of the cropped image.
I wanna advertise in my app if the dimension of the image are optimal.

Thanks!

**Comment by Mawi137** [comment]
I added a new output `imageCropped` with emits a `ImageCroppedEvent`. That object contains the base64, file, cropped width, cropped height and cropper position. `imageCroppedBase64` and `imageCroppedFile` will be removed in the future. More info in the readme.md.
