### ISSUE TITLE
Change the aspectRatio

### ISSUE THREAD

**Issue by paulomota** [Mawi137/ngx-image-cropper#88]
Can I change the aspectRatio dynamically? I tried to get the cropper element by the id and them set aspect-ratio atribut in the typescript, no result in this way.

**Comment by karanecs** [comment]
I also tried to make aspect ratio dynamically, but it is not working

**Comment by igorkaiudenko** [comment]
Same question here

**Comment by stoto34** [comment]
Same question...

I tried with a variable but it doesn't work and the cropper bug.

**Comment by CreativeAcer** [comment]
You should be able to adjust the ratio by setting the aspectRatio to a variable
`[aspectRatio]="selectedRatio"`

and in your typescript file you change the variables value to something like 
```
selectedRatio: number = 1/1;
selectedRatio: number = 16/9;
```
etc

**Comment by stoto34** [comment]
@CreativeAcer  It's working but the cropper is not refreshed. I have to click on the cropper to get the new ratio updated.

Here what I'm doing (I change the value of a select to change the aspectRatio)

`updateRatio(event) {
        if (event) {
            this.selectedRatio = event.value.ratio.w  / event.value.ratio.h;
        }
        console.log(event);
    }`

I would like to know how to "refresh" the cropper when I change this value. Any idea ? Thank you :)

**Comment by CreativeAcer** [comment]
@stoto34 this should refresh the cropping window aswell:

create an input 
```
@Input()
    set ratioChanged(ratio: number) {
        if (ratio) {
            this.aspectRatio = ratio;
            this.resetCropperPosition();
        }
    }

```
and add the selectedRatio to this in your html:
`<image-cropper ... [imageBase64]="Base64" [aspectRatio]="selectedRatio" [ratioChanged]="selectedRatio"></image-cropper>`

**Comment by stoto34** [comment]
I like this idea, i'm going to test it. By the way, what is resetCropperPosition function ?

**Comment by CreativeAcer** [comment]
yes, important sidenote is that i updated the base npm package.
Created my own version and added it to my project.

this way i can add the functionality i needed.
this.resetCropperPosition() is a function thats allready available in the core code.

**Comment by stoto34** [comment]
Thank you very much for your help :)

**Comment by stoto34** [comment]
How did you add resetCropperPosition functionnality to your main component ? I add image-cropper folder inside my "coreModule" of my project but I don't how can I reach resetCropperPosition  function from my component (itemModule)

ItemModule knows coreModule.

**Comment by stoto34** [comment]
I've got an error : 

ERROR in src/app/itemModule/components/item.form.component.ts(50,18): error TS2339: Property 'resetCropperPosition' does not exist on type 'ItemFormDialogComponent'

I think I missed something...

**Comment by CreativeAcer** [comment]
yes, from your naming i think you only need to add the image cropper html to your itemformDialog html file:
`<image-cropper ... [imageBase64]="Base64" [aspectRatio]="selectedRatio" **[ratioChanged]="selectedRatio"**></image-cropper>`

and in the files you added through npm

in the core file named:
image-cropper-component.ts
you add this 
```
@Input()
    set ratioChanged(ratio: number) {
        if (ratio) {
            this.aspectRatio = ratio;
            this.resetCropperPosition();
        }
    }
```
now by changing the aspectratio variable in you component (ItemFormDialogComponent) you will trigger te cropper to change

**Comment by stoto34** [comment]
Great it works !!! Thank you very much for your precious help

**Comment by CreativeAcer** [comment]
you should take into consideration that is not a great idea to change the npm code files.
So it might be best if you created your own version and add that to your project. (Just copy the files and place them in your own folder in your project structure, reference the files from there instead of the npm)

so that it will not get broken with some possible future updates.

And you're welcome :)

**Comment by stoto34** [comment]
Yes I know that's why I've created a folder in my coreModule named "image-cropper" and I removed npm package ngx-image-cropper. You should suggest this update for the next version of this library, it works well.

**Comment by CreativeAcer** [comment]
@stoto34 i allready created a pull request :)

**Comment by Mawi137** [comment]
If you update to `1.1.0`, it should reset the cropper position if you change the aspectRatio.

**Comment by krunalsk007** [comment]
just add this line 
this.cropper.setAspectRatio(this.aspectRatio);
