### ISSUE TITLE
Returning Dimensions of the cropped image relative to the original image

### ISSUE THREAD

**Issue by sunnysetia93** [Mawi137/ngx-image-cropper#93]
I was using the package and needed dimensions of the cropped image relative to the original image but the outputs only have an **image file** or **base64** as an option.

It would be beneficial if the dimensions were also returned along with these options as It can be used in many cases.
I suppose this can be done while selecting the frame and getting its **event.OffsetX** and **event.OffsetY** as soon as the "**mousehover**" event takes place. 

Thank you.

**Comment by Mawi137** [comment]
You can use the cropper input for that. In the class containing the cropper, create a variable: `cropper = {x1: 0, x2: 0, y1: 0, y2: 0}` and assign that to the cropper input. The image cropper will update these values when the cropper's size or position changes.

**Comment by Mawi137** [comment]
I just also added a new output `imageCropped` which emits a `ImageCroppedEvent`. That object contains the base64, file, cropped width, cropped height and cropper position. `imageCroppedBase64` and `imageCroppedFile` will be removed in the future. More info in the readme.md.

**Comment by sunnysetia93** [comment]
Thank you for the information. Appreciate it.
