### ISSUE TITLE
Load image in the cropper via component

### ISSUE THREAD

**Issue by luisschneiders** [Mawi137/ngx-image-cropper#94]
Hi @Mawi137, 

I hope you are well.
I'd like to know if there is a way to inject the image in the cropper dynamically via component, instead of using input type="file".

Many thanks.

**Comment by Mawi137** [comment]
Hi @luisschneiders 
There are 3 inputs you can use to make the image cropper load a file. `imageChangedEvent ` (when using a file input), `imageFileChanged` and `imageBase64`. So if you have a file, use the second one, if it's a base64, the third. More info in the Readme.md
