### ISSUE TITLE
I want  imageCroppedFile in ts file

### ISSUE THREAD

**Issue by nani2nithin** [Mawi137/ngx-image-cropper#95]
How can i get the cropped image file in ngx image cropper to upload the image file to aws. can u suggest the solution how to get the cropped image file.

**Comment by Mawi137** [comment]
Simple take the file returned by the `imageCroppedFile` output. How you should then upload that file to your server depends on you backend implementation. I think there are articles on stackoverflow or blogposts you can find using Google that will help you with that.

**Comment by nani2nithin** [comment]
ngx image cropper is not working in angular when runs with ng serve --aot

**Comment by nani2nithin** [comment]
> 
> 
> Simple take the file returned by the `imageCroppedFile` output. How you should then upload that file to your server depends on you backend implementation. I think there are articles on stackoverflow or blogposts you can find using Google that will help you with that.

upload the file from front end not from backend. so i need the file

**Comment by Mawi137** [comment]
Does it work with `ng build --prod` ?
