### ISSUE TITLE
roundCropper does not round crop

### ISSUE THREAD

**Issue by nphias** [Mawi137/ngx-image-cropper#96]
Hi .. This would be a relly nice feature to have..  i need it for my application.
but although it shows a circular selector.. it does not alpha-rize to pixels outside the circle in the final blob/base64

<image-cropper
                [imageChangedEvent]="imageChangedEvent"
                [maintainAspectRatio]="true"
                [aspectRatio]="1 / 1"
                [resizeToWidth]="540"
                roundCropper = true
                format="png"
                (imageCroppedFile)="imageCropped($event)"
                (imageLoaded)="imageLoaded()"
                (loadImageFailed)="loadImageFailed()">
</image-cropper>

**Comment by Mawi137** [comment]
Indeed, but you can use the following css to show the image as round: `border-radius: 100%;`. I can imagine that there are use cases where you want the image to be round itself, but I hope adding this css to the image will solve you problem.

**Comment by Yejielw** [comment]
can this be added to the documentation 
was kinda tricky to find

**Comment by Mawi137** [comment]
Seems like I forgot to add it indeed, it's in the readme now!

**Comment by nphias** [comment]
I would still like the feature that creates a circular image.. not a css hack..
the canvas 2d is already being used for image crop .. so circular crop using canvas 2d is possible.. seen it in another ng image cropper repo...  but that one has another set of problems that i dont need!
I had an attempt at it .. but lost got lost in the math.. :) .. if i someone has the time and will power.. otherwise i will have to continue with Jimp

**Comment by jcasasg** [comment]
> I would still like the feature that creates a circular image.. not a css hack..
> the canvas 2d is already being used for image crop .. so circular crop using canvas 2d is possible.. seen it in another ng image cropper repo... but that one has another set of problems that i dont need!
> I had an attempt at it .. but lost got lost in the math.. :) .. if i someone has the time and will power.. otherwise i will have to continue with Jimp

+1
