### ISSUE TITLE
When  i  set  autoCrop=false.Import  ImageCropperComponent   error

### ISSUE THREAD

**Issue by 519818538** [Mawi137/ngx-image-cropper#98]
I used  it  like  this:
import { ImageCroppedEvent, ImageCropperComponent } from 'ngx-image-cropper/src/image-cropper.component';
@Component({
    selector: 'img-crop',
    templateUrl: 'img-crop.html'
})
export  class   MyComponent{
 @ViewChild(ImageCropperComponent) imgCropper: ImageCropperComponent;

}
Then  report  error:Cannot find module "ngx-image-cropper/src/image-cropper.component".

**Comment by Mawi137** [comment]
It should be `import { ImageCroppedEvent, ImageCropperComponent } from 'ngx-image-cropper';`
